// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	"context"
	notificationv1 "github.com/hvritual/biz/contracts/gen/notification/v1"
)

// MessageConfigurationApplication is generated from PB and contains no business implementation.
type MessageConfigurationApplication interface {
	CreateMessageConfigurations(context.Context, *notificationv1.CreateMessageConfigurationsRequest) (*notificationv1.MessageConfigurationReceipt, error)
	DeleteMessageConfiguration(context.Context, *notificationv1.DeleteMessageConfigurationRequest) (*notificationv1.MessageConfigurationReceipt, error)
	GetMessageConfiguration(context.Context, *notificationv1.GetMessageConfigurationRequest) (*notificationv1.MessageConfigurationDTO, error)
	ListMessageChannels(context.Context, *notificationv1.ListMessageChannelsRequest) (*notificationv1.ListMessageChannelsResponse, error)
	ListMessageConfigurations(context.Context, *notificationv1.ListMessageConfigurationsRequest) (*notificationv1.ListMessageConfigurationsResponse, error)
	ListMessageGroups(context.Context, *notificationv1.ListMessageDirectoryRequest) (*notificationv1.ListMessageDirectoryResponse, error)
	ListMessageRecipients(context.Context, *notificationv1.ListMessageDirectoryRequest) (*notificationv1.ListMessageDirectoryResponse, error)
	ListMessageTypes(context.Context, *notificationv1.ListMessageTypesRequest) (*notificationv1.ListMessageTypesResponse, error)
	UpdateMessageConfiguration(context.Context, *notificationv1.UpdateMessageConfigurationRequest) (*notificationv1.MessageConfigurationReceipt, error)
}
