// Code generated by yunka contract; DO NOT EDIT.

package rest

import (
	"errors"
	deviceopsv1 "github.com/hvritual/biz/contracts/gen/deviceops/v1"
	application "github.com/hvritual/biz/internal/deviceops/application"
	policy "github.com/hvritual/biz/internal/deviceops/policy"
	protojson "google.golang.org/protobuf/encoding/protojson"
	io "io"
	"net/http"
	execution "yunka.io/framework/execution"
	operation "yunka.io/framework/operation"
	authz "yunka.io/gateway/authz"
)

type DeviceTransferOperationHandler struct {
	application application.DeviceTransferApplication
	executor    operation.Executor
}

func RegisterDeviceTransferOperationExecutor(mux *http.ServeMux, application application.DeviceTransferApplication, executor operation.Executor) error {
	if mux == nil {
		return errors.New("contract C9 REST adapter: mux is required")
	}
	if application == nil {
		return errors.New("contract C9 REST adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 REST adapter: operation executor is required")
	}
	handler := &DeviceTransferOperationHandler{application: application, executor: executor}
	mux.HandleFunc("PATCH /v1/devices/{id}/transfer", handler.handleOperationTransferDevice)
	return nil
}

func writeDeviceTransferOperationError(writer http.ResponseWriter, err error) {
	if authz.IsDenied(err) {
		statusCode := http.StatusForbidden
		var denied *authz.DeniedError
		if errors.As(err, &denied) && (denied.Decision.Reason == authz.ReasonUnauthenticated || denied.Decision.Reason == authz.ReasonAuthenticationMethod) {
			statusCode = http.StatusUnauthorized
		}
		http.Error(writer, http.StatusText(statusCode), statusCode)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyKeyRequired) {
		http.Error(writer, "idempotency key required", http.StatusBadRequest)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyInProgress) || errors.Is(err, execution.ErrIdempotencyCompleted) {
		http.Error(writer, "idempotency conflict", http.StatusConflict)
		return
	}
	if errors.Is(err, operation.ErrExecutorUnavailable) || errors.Is(err, operation.ErrSecurityUnavailable) || errors.Is(err, operation.ErrSecurityNilContext) || errors.Is(err, operation.ErrIdempotencyUnavailable) {
		http.Error(writer, "operation execution unavailable", http.StatusInternalServerError)
		return
	}
	http.Error(writer, "application request failed", http.StatusBadRequest)
}

func (handler *DeviceTransferOperationHandler) handleOperationTransferDevice(writer http.ResponseWriter, request *http.Request) {
	wire := &deviceopsv1.TransferDeviceRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.Id = request.PathValue("id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanDeviceTransferTransferDevice(), wire, handler.application.TransferDevice)
	if err != nil {
		writeDeviceTransferOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}
