// Code generated by yunka contract; DO NOT EDIT.

package rest

import (
	"errors"
	deviceopsv1 "github.com/hvritual/biz/contracts/gen/deviceops/v1"
	application "github.com/hvritual/biz/internal/deviceops/application"
	policy "github.com/hvritual/biz/internal/deviceops/policy"
	protojson "google.golang.org/protobuf/encoding/protojson"
	io "io"
	"net/http"
	strconv "strconv"
	operation "yunka.io/framework/operation"
	authz "yunka.io/gateway/authz"
)

type OperationHandler struct {
	application application.DeviceApplication
	executor    operation.Executor
}

func RegisterOperationExecutor(mux *http.ServeMux, application application.DeviceApplication, executor operation.Executor) error {
	if mux == nil {
		return errors.New("contract C9 REST adapter: mux is required")
	}
	if application == nil {
		return errors.New("contract C9 REST adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 REST adapter: operation executor is required")
	}
	handler := &OperationHandler{application: application, executor: executor}
	mux.HandleFunc("POST /v1/devices", handler.handleOperationCreateDevice)
	mux.HandleFunc("DELETE /v1/devices/{id}", handler.handleOperationDeleteDevice)
	mux.HandleFunc("GET /v1/devices/{id}", handler.handleOperationGetDevice)
	mux.HandleFunc("GET /v1/devices", handler.handleOperationListDevices)
	mux.HandleFunc("PATCH /v1/devices/{id}", handler.handleOperationUpdateDevice)
	return nil
}

func writeOperationError(writer http.ResponseWriter, err error) {
	if authz.IsDenied(err) {
		statusCode := http.StatusForbidden
		var denied *authz.DeniedError
		if errors.As(err, &denied) && (denied.Decision.Reason == authz.ReasonUnauthenticated || denied.Decision.Reason == authz.ReasonAuthenticationMethod) {
			statusCode = http.StatusUnauthorized
		}
		http.Error(writer, http.StatusText(statusCode), statusCode)
		return
	}
	if errors.Is(err, operation.ErrExecutorUnavailable) || errors.Is(err, operation.ErrSecurityUnavailable) || errors.Is(err, operation.ErrSecurityNilContext) {
		http.Error(writer, "operation execution unavailable", http.StatusInternalServerError)
		return
	}
	http.Error(writer, "application request failed", http.StatusBadRequest)
}

func (handler *OperationHandler) handleOperationCreateDevice(writer http.ResponseWriter, request *http.Request) {
	wire := &deviceopsv1.CreateDeviceRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	output, err := operation.ExecuteTyped(request.Context(), handler.executor, policy.OperationPlanCreateDevice(), wire, handler.application.CreateDevice)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *OperationHandler) handleOperationDeleteDevice(writer http.ResponseWriter, request *http.Request) {
	wire := &deviceopsv1.DeleteDeviceRequest{}
	if raw := request.URL.Query().Get("version"); raw != "" {
		parsed, err := strconv.ParseUint(raw, 10, 64)
		if err != nil {
			http.Error(writer, "invalid request parameter", http.StatusBadRequest)
			return
		}
		wire.Version = uint64(parsed)
	}
	wire.Id = request.PathValue("id")
	output, err := operation.ExecuteTyped(request.Context(), handler.executor, policy.OperationPlanDeleteDevice(), wire, handler.application.DeleteDevice)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *OperationHandler) handleOperationGetDevice(writer http.ResponseWriter, request *http.Request) {
	wire := &deviceopsv1.GetDeviceRequest{}
	wire.Id = request.PathValue("id")
	output, err := operation.ExecuteTyped(request.Context(), handler.executor, policy.OperationPlanGetDevice(), wire, handler.application.GetDevice)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *OperationHandler) handleOperationListDevices(writer http.ResponseWriter, request *http.Request) {
	wire := &deviceopsv1.ListDevicesRequest{}
	output, err := operation.ExecuteTyped(request.Context(), handler.executor, policy.OperationPlanListDevices(), wire, handler.application.ListDevices)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *OperationHandler) handleOperationUpdateDevice(writer http.ResponseWriter, request *http.Request) {
	wire := &deviceopsv1.UpdateDeviceRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.Id = request.PathValue("id")
	output, err := operation.ExecuteTyped(request.Context(), handler.executor, policy.OperationPlanUpdateDevice(), wire, handler.application.UpdateDevice)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}
