// Generated by cmd/commercial-state-vocabulary. Do not edit.
export const commercialStateVocabulary = {
  "changeAction": [
    "RENEW",
    "STOP_RENEWAL",
    "SWITCH"
  ],
  "changeClassification": [
    "DOWNGRADE",
    "RENEW",
    "SAME_TIER",
    "STOP_RENEWAL",
    "UPGRADE"
  ],
  "decisionKind": [
    "capability",
    "field",
    "module",
    "quota"
  ],
  "effectiveMode": [
    "IMMEDIATE",
    "SCHEDULED"
  ],
  "planState": [
    "DRAFT",
    "PUBLISHED",
    "RETIRED"
  ],
  "provisioningState": [
    "APPLIED",
    "CANCELLED",
    "FAILED",
    "QUEUED",
    "READY",
    "RECONCILIATION_REQUIRED",
    "RETRY_WAIT",
    "RUNNING"
  ],
  "receiptStatus": [
    "APPLIED",
    "FAILED",
    "PROVISIONING",
    "SCHEDULED"
  ],
  "salesStatus": [
    "MODULE_SALES_STATUS_RETIRED",
    "MODULE_SALES_STATUS_SELLABLE",
    "MODULE_SALES_STATUS_UNSPECIFIED",
    "retired",
    "sellable"
  ],
  "sourceKind": [
    "addon",
    "override",
    "plan"
  ],
  "sourceState": [
    "active",
    "expired",
    "revoked",
    "scheduled"
  ],
  "subscriptionState": [
    "ACTIVE",
    "ENDED",
    "GRACE",
    "RESTRICTED",
    "TRIAL"
  ],
  "technicalStatus": [
    "MODULE_TECHNICAL_STATUS_DISABLED",
    "MODULE_TECHNICAL_STATUS_NOT_READY",
    "MODULE_TECHNICAL_STATUS_READY",
    "MODULE_TECHNICAL_STATUS_UNSPECIFIED",
    "disabled",
    "not_ready",
    "ready"
  ]
} as const

export type CommercialStateKind = keyof typeof commercialStateVocabulary
export type CommercialStateCode<K extends CommercialStateKind> = (typeof commercialStateVocabulary)[K][number]

export const commercialStateSources = {
  "contracts/proto/commercial/v1/module.proto": "7f4cdcb88eb3f4c78927ba119257c633fc273d652d7132cc413d7754b66655fb",
  "internal/commercial/application/subscriptionchanges/internal/usecase/preview.go": "0ec9da0b0d11e501d0fd49739d60aadd6290f32df5ca009008b5687d9d15755f",
  "internal/commercial/domain/entitlement/model.go": "bfeed4afbbd2dd55fe87aa3330a5cacb4f608a11a8e55764c947b06d1aa8bea1",
  "internal/commercial/domain/plan/model.go": "dfcc8f1a98ff07c1138fa4654947aa12815de9c63e473e0c6ab6efe2732f9670",
  "internal/commercial/domain/provisioning/model.go": "e9a0a72a1ba5b05ca5e6b688ac4f8a8c4a67b5d6aecd60399b5477267712dda9",
  "internal/commercial/domain/subscription/model.go": "2bd833f0e0f898c8c553e0effd4599bd2d1a77fbd850d9f53cec8a0306e02c77",
  "internal/commercial/domain/subscriptionchange/model.go": "73dd3d585c9d155e64b605122eb6b225c1a8d9586835c2cb7c96bccf732600eb",
  "internal/commercial/modulecatalog/model.go": "b72d37c54fe1e5cf229105e9a79d52ca9f5c83b9f6ac6bf613c6ac17f39ac34c"
} as const
