// Code generated by yunka contract; DO NOT EDIT.

package rpc

import (
	"context"
	"errors"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
	application "github.com/hvritual/biz/internal/access/application"
	policy "github.com/hvritual/biz/internal/access/policy"
	grpc "google.golang.org/grpc"
	grpcmetadata "google.golang.org/grpc/metadata"
	execution "yunka.io/framework/execution"
	operation "yunka.io/framework/operation"
	gatewaygrpc "yunka.io/gateway/rpc/transport/grpc"
)

type TenantDelegationManagementOperationServer struct {
	accessv1.UnimplementedTenantDelegationApplicationServer
	application application.TenantDelegationManagementApplication
	executor    operation.Executor
}

func RegisterTenantDelegationManagementOperationExecutor(registrar grpc.ServiceRegistrar, application application.TenantDelegationManagementApplication, executor operation.Executor) error {
	if registrar == nil {
		return errors.New("contract C9 RPC adapter: registrar is required")
	}
	if application == nil {
		return errors.New("contract C9 RPC adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 RPC adapter: operation executor is required")
	}
	accessv1.RegisterTenantDelegationApplicationServer(registrar, &TenantDelegationManagementOperationServer{application: application, executor: executor})
	return nil
}

func (server *TenantDelegationManagementOperationServer) GetTenantDelegation(ctx context.Context, request *accessv1.GetTenantDelegationRequest) (*accessv1.TenantDelegationDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantDelegationManagementGetTenantDelegation(), request, server.application.GetTenantDelegation)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *TenantDelegationManagementOperationServer) GrantTenantDeviceDelegation(ctx context.Context, request *accessv1.GrantTenantDeviceDelegationRequest) (*accessv1.TenantDelegationDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantDelegationManagementGrantTenantDeviceDelegation(), request, server.application.GrantTenantDeviceDelegation)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *TenantDelegationManagementOperationServer) ListTenantDelegations(ctx context.Context, request *accessv1.ListTenantDelegationsRequest) (*accessv1.ListTenantDelegationsResponse, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantDelegationManagementListTenantDelegations(), request, server.application.ListTenantDelegations)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *TenantDelegationManagementOperationServer) RevokeTenantDelegation(ctx context.Context, request *accessv1.RevokeTenantDelegationRequest) (*accessv1.TenantDelegationDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantDelegationManagementRevokeTenantDelegation(), request, server.application.RevokeTenantDelegation)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}
