// Code generated by yunka contract; DO NOT EDIT.

package rpc

import (
	"context"
	"errors"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
	application "github.com/hvritual/biz/internal/access/application"
	policy "github.com/hvritual/biz/internal/access/policy"
	grpc "google.golang.org/grpc"
	grpcmetadata "google.golang.org/grpc/metadata"
	execution "yunka.io/framework/execution"
	operation "yunka.io/framework/operation"
	gatewaygrpc "yunka.io/gateway/rpc/transport/grpc"
)

type TenantAuditManagementOperationServer struct {
	accessv1.UnimplementedTenantAuditManagementApplicationServer
	application application.TenantAuditManagementApplication
	executor    operation.Executor
}

func RegisterTenantAuditManagementOperationExecutor(registrar grpc.ServiceRegistrar, application application.TenantAuditManagementApplication, executor operation.Executor) error {
	if registrar == nil {
		return errors.New("contract C9 RPC adapter: registrar is required")
	}
	if application == nil {
		return errors.New("contract C9 RPC adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 RPC adapter: operation executor is required")
	}
	accessv1.RegisterTenantAuditManagementApplicationServer(registrar, &TenantAuditManagementOperationServer{application: application, executor: executor})
	return nil
}

func (server *TenantAuditManagementOperationServer) ExportTenantAuditRecords(ctx context.Context, request *accessv1.ExportTenantAuditRecordsRequest) (*accessv1.ExportTenantAuditRecordsResponse, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantAuditManagementExportTenantAuditRecords(), request, server.application.ExportTenantAuditRecords)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *TenantAuditManagementOperationServer) GetTenantAuditRecord(ctx context.Context, request *accessv1.GetTenantAuditRecordRequest) (*accessv1.TenantAuditRecordDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantAuditManagementGetTenantAuditRecord(), request, server.application.GetTenantAuditRecord)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *TenantAuditManagementOperationServer) ListTenantAuditRecords(ctx context.Context, request *accessv1.ListTenantAuditRecordsRequest) (*accessv1.ListTenantAuditRecordsResponse, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantAuditManagementListTenantAuditRecords(), request, server.application.ListTenantAuditRecords)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}
