// Code generated by yunka contract; DO NOT EDIT.

package rpc

import (
	"context"
	"errors"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
	application "github.com/hvritual/biz/internal/access/application"
	policy "github.com/hvritual/biz/internal/access/policy"
	grpc "google.golang.org/grpc"
	grpcmetadata "google.golang.org/grpc/metadata"
	execution "yunka.io/framework/execution"
	operation "yunka.io/framework/operation"
	gatewaygrpc "yunka.io/gateway/rpc/transport/grpc"
)

type TenantMemberBusinessScopeOperationServer struct {
	accessv1.UnimplementedTenantMemberBusinessScopeApplicationServer
	application application.TenantMemberBusinessScopeApplication
	executor    operation.Executor
}

func RegisterTenantMemberBusinessScopeOperationExecutor(registrar grpc.ServiceRegistrar, application application.TenantMemberBusinessScopeApplication, executor operation.Executor) error {
	if registrar == nil {
		return errors.New("contract C9 RPC adapter: registrar is required")
	}
	if application == nil {
		return errors.New("contract C9 RPC adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 RPC adapter: operation executor is required")
	}
	accessv1.RegisterTenantMemberBusinessScopeApplicationServer(registrar, &TenantMemberBusinessScopeOperationServer{application: application, executor: executor})
	return nil
}

func (server *TenantMemberBusinessScopeOperationServer) GetTenantMemberBusinessScope(ctx context.Context, request *accessv1.GetTenantMemberBusinessScopeRequest) (*accessv1.TenantMemberBusinessScopeDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantMemberBusinessScopeGetTenantMemberBusinessScope(), request, server.application.GetTenantMemberBusinessScope)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *TenantMemberBusinessScopeOperationServer) ListTenantMemberScopeCandidates(ctx context.Context, request *accessv1.ListTenantMemberScopeCandidatesRequest) (*accessv1.ListTenantMemberScopeCandidatesResponse, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantMemberBusinessScopeListTenantMemberScopeCandidates(), request, server.application.ListTenantMemberScopeCandidates)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *TenantMemberBusinessScopeOperationServer) SetTenantMemberBusinessScope(ctx context.Context, request *accessv1.SetTenantMemberBusinessScopeRequest) (*accessv1.TenantMemberBusinessScopeDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantMemberBusinessScopeSetTenantMemberBusinessScope(), request, server.application.SetTenantMemberBusinessScope)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}
