// Code generated by yunka contract; DO NOT EDIT.

package rpc

import (
	"context"
	"errors"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
	application "github.com/hvritual/biz/internal/access/application"
	policy "github.com/hvritual/biz/internal/access/policy"
	grpc "google.golang.org/grpc"
	grpcmetadata "google.golang.org/grpc/metadata"
	execution "github.com/hvritual/yunka.io/framework/execution"
	operation "github.com/hvritual/yunka.io/framework/operation"
	gatewaygrpc "github.com/hvritual/yunka.io/gateway/rpc/transport/grpc"
)

type TenantRolePermissionOperationServer struct {
	accessv1.UnimplementedTenantRolePermissionApplicationServer
	application application.TenantRolePermissionApplication
	executor    operation.Executor
}

func RegisterTenantRolePermissionOperationExecutor(registrar grpc.ServiceRegistrar, application application.TenantRolePermissionApplication, executor operation.Executor) error {
	if registrar == nil {
		return errors.New("contract C9 RPC adapter: registrar is required")
	}
	if application == nil {
		return errors.New("contract C9 RPC adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 RPC adapter: operation executor is required")
	}
	accessv1.RegisterTenantRolePermissionApplicationServer(registrar, &TenantRolePermissionOperationServer{application: application, executor: executor})
	return nil
}

func (server *TenantRolePermissionOperationServer) AssignTenantRoleMember(ctx context.Context, request *accessv1.AssignTenantRoleMemberRequest) (*accessv1.TenantRoleDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantRolePermissionAssignTenantRoleMember(), request, server.application.AssignTenantRoleMember)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *TenantRolePermissionOperationServer) CreateTenantRole(ctx context.Context, request *accessv1.CreateTenantRoleRequest) (*accessv1.TenantRoleDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantRolePermissionCreateTenantRole(), request, server.application.CreateTenantRole)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *TenantRolePermissionOperationServer) DisableTenantRole(ctx context.Context, request *accessv1.DisableTenantRoleRequest) (*accessv1.TenantRoleDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantRolePermissionDisableTenantRole(), request, server.application.DisableTenantRole)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *TenantRolePermissionOperationServer) EnableTenantRole(ctx context.Context, request *accessv1.EnableTenantRoleRequest) (*accessv1.TenantRoleDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantRolePermissionEnableTenantRole(), request, server.application.EnableTenantRole)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *TenantRolePermissionOperationServer) GetTenantRole(ctx context.Context, request *accessv1.GetTenantRoleRequest) (*accessv1.TenantRoleDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantRolePermissionGetTenantRole(), request, server.application.GetTenantRole)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *TenantRolePermissionOperationServer) ListTenantRoles(ctx context.Context, request *accessv1.ListTenantRolesRequest) (*accessv1.ListTenantRolesResponse, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantRolePermissionListTenantRoles(), request, server.application.ListTenantRoles)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *TenantRolePermissionOperationServer) RevokeTenantRoleMember(ctx context.Context, request *accessv1.RevokeTenantRoleMemberRequest) (*accessv1.TenantRoleDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantRolePermissionRevokeTenantRoleMember(), request, server.application.RevokeTenantRoleMember)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *TenantRolePermissionOperationServer) SetTenantRolePermissions(ctx context.Context, request *accessv1.SetTenantRolePermissionsRequest) (*accessv1.TenantRoleDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantRolePermissionSetTenantRolePermissions(), request, server.application.SetTenantRolePermissions)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *TenantRolePermissionOperationServer) UpdateTenantRole(ctx context.Context, request *accessv1.UpdateTenantRoleRequest) (*accessv1.TenantRoleDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanTenantRolePermissionUpdateTenantRole(), request, server.application.UpdateTenantRole)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}
