package application

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"sort"
	"strings"
	"time"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
	deviceopsv1 "github.com/hvritual/biz/contracts/gen/deviceops/v1"
	"github.com/hvritual/biz/internal/access/domain"
	"github.com/hvritual/biz/internal/access/ports"
	"yunka.io/framework/requestscope"
)

func (s *TenantRolePermissionService) ListTenantDataPolicies(ctx context.Context,_ *accessv1.ListTenantDataPoliciesRequest)(*accessv1.ListTenantDataPoliciesResponse,error){tenantID,err:=trustedTenantID(ctx);if err!=nil{return nil,err};items,err:=requestscope.JoinValue(ctx,s.repositories,func(v *requestscope.View[ports.TenantRoleRepositories])([]domain.DataPolicy,error){return v.Repositories().DataPolicy.List(v.Context(),tenantID)});if err!=nil{return nil,err};out:=&accessv1.ListTenantDataPoliciesResponse{Policies:make([]*accessv1.TenantDataPolicyDTO,0,len(items))};for _,p:=range items{out.Policies=append(out.Policies,tenantDataPolicyDTO(p,time.Now().UTC()))};return out,nil}
func (s *TenantRolePermissionService) GetTenantDataPolicy(ctx context.Context,r *accessv1.GetTenantDataPolicyRequest)(*accessv1.TenantDataPolicyDTO,error){if r==nil||strings.TrimSpace(r.GetPolicyId())==""{return nil,ErrInvalidTenantRoleRequest};tenantID,err:=trustedTenantID(ctx);if err!=nil{return nil,err};p,err:=requestscope.JoinValue(ctx,s.repositories,func(v *requestscope.View[ports.TenantRoleRepositories])(domain.DataPolicy,error){return v.Repositories().DataPolicy.Get(v.Context(),tenantID,strings.TrimSpace(r.GetPolicyId()))});if err!=nil{return nil,err};return tenantDataPolicyDTO(p,time.Now().UTC()),nil}
func (s *TenantRolePermissionService) CreateTenantDataPolicy(ctx context.Context,r *accessv1.CreateTenantDataPolicyRequest)(*accessv1.TenantDataPolicyDTO,error){if r==nil{return nil,ErrInvalidTenantRoleRequest};tenantID,err:=trustedTenantID(ctx);if err!=nil{return nil,err};sites,err:=normalizePolicySites(r.GetSiteIds());if err!=nil{return nil,err};if err=s.validatePolicySites(ctx,sites);err!=nil{return nil,err};nb,exp,err:=policyWindow(r.GetNotBefore(),r.GetExpiresAt());if err!=nil{return nil,err};id:=strings.TrimSpace(r.GetPolicyId());if id==""{id=newTenantDataPolicyID()};p,err:=domain.NewDataPolicy(id,tenantID,r.GetName(),sites,nb,exp,time.Now().UTC());if err!=nil{return nil,err};err=requestscope.JoinDo(ctx,s.repositories,func(v *requestscope.View[ports.TenantRoleRepositories])error{return v.Repositories().DataPolicy.Create(v.Context(),&p)});if err!=nil{return nil,err};return tenantDataPolicyDTO(p,time.Now().UTC()),nil}
func (s *TenantRolePermissionService) UpdateTenantDataPolicy(ctx context.Context,r *accessv1.UpdateTenantDataPolicyRequest)(*accessv1.TenantDataPolicyDTO,error){if r==nil||strings.TrimSpace(r.GetPolicyId())==""||r.GetVersion()==0{return nil,ErrInvalidTenantRoleRequest};tenantID,err:=trustedTenantID(ctx);if err!=nil{return nil,err};sites,err:=normalizePolicySites(r.GetSiteIds());if err!=nil{return nil,err};if err=s.validatePolicySites(ctx,sites);err!=nil{return nil,err};nb,exp,err:=policyWindow(r.GetNotBefore(),r.GetExpiresAt());if err!=nil{return nil,err};p,err:=requestscope.JoinValue(ctx,s.repositories,func(v *requestscope.View[ports.TenantRoleRepositories])(domain.DataPolicy,error){current,err:=v.Repositories().DataPolicy.Get(v.Context(),tenantID,strings.TrimSpace(r.GetPolicyId()));if err!=nil{return domain.DataPolicy{},err};if current.Version!=r.GetVersion(){return domain.DataPolicy{},ports.ErrTenantDataPolicyConflict};if err=current.Apply(r.GetName(),sites,nb,exp,time.Now().UTC());err!=nil{return domain.DataPolicy{},err};if err=v.Repositories().DataPolicy.Update(v.Context(),&current,r.GetVersion());err!=nil{return domain.DataPolicy{},err};return current,nil});if err!=nil{return nil,err};return tenantDataPolicyDTO(p,time.Now().UTC()),nil}
func (s *TenantRolePermissionService) RevokeTenantDataPolicy(ctx context.Context,r *accessv1.RevokeTenantDataPolicyRequest)(*accessv1.TenantDataPolicyDTO,error){if r==nil||strings.TrimSpace(r.GetPolicyId())==""||r.GetVersion()==0{return nil,ErrInvalidTenantRoleRequest};tenantID,err:=trustedTenantID(ctx);if err!=nil{return nil,err};p,err:=requestscope.JoinValue(ctx,s.repositories,func(v *requestscope.View[ports.TenantRoleRepositories])(domain.DataPolicy,error){return v.Repositories().DataPolicy.Revoke(v.Context(),tenantID,strings.TrimSpace(r.GetPolicyId()),r.GetVersion())});if err!=nil{return nil,err};return tenantDataPolicyDTO(p,time.Now().UTC()),nil}
func (s *TenantRolePermissionService) SetTenantRoleDataPolicy(ctx context.Context,r *accessv1.SetTenantRoleDataPolicyRequest)(*accessv1.TenantRoleDTO,error){if r==nil||strings.TrimSpace(r.GetRoleId())==""||r.GetVersion()==0{return nil,ErrInvalidTenantRoleRequest};policyID:=strings.TrimSpace(r.GetPolicyId());if (policyID==""&&r.GetPolicyVersion()!=0)||(policyID!=""&&r.GetPolicyVersion()==0){return nil,ErrInvalidTenantRoleRequest};tenantID,err:=trustedTenantID(ctx);if err!=nil{return nil,err};role,err:=requestscope.JoinValue(ctx,s.repositories,func(v *requestscope.View[ports.TenantRoleRepositories])(domain.Role,error){return v.Repositories().Role.SetDataPolicy(v.Context(),tenantID,strings.TrimSpace(r.GetRoleId()),r.GetVersion(),policyID,r.GetPolicyVersion(),time.Now().UTC())});if err!=nil{return nil,err};return tenantRoleDTO(role),nil}
func (s *TenantRolePermissionService) validatePolicySites(ctx context.Context,ids []string)error{if len(ids)==0{return nil};if s.sites==nil{return ports.ErrTenantDataPolicyUnavailable};response,err:=s.sites.ListAssignableRoleSites(ctx,&deviceopsv1.SiteScopeDirectoryRequest{SiteIds:ids,Resolve:true});if err!=nil{return err};if response==nil||len(response.GetSites())!=len(ids)||int(response.GetTotal())!=len(ids){return ports.ErrTenantDataPolicyUnavailable};seen:=map[string]struct{}{};for _,site:=range response.GetSites(){if site==nil{return ports.ErrTenantDataPolicyUnavailable};seen[strings.TrimSpace(site.GetId())]=struct{}{}};for _,id:=range ids{if _,ok:=seen[id];!ok{return ports.ErrTenantDataPolicyUnavailable}};return nil}
func normalizePolicySites(values []string)([]string,error){seen:=map[string]struct{}{};out:=make([]string,0,len(values));for _,v:=range values{v=strings.TrimSpace(v);if v==""||len(v)>160{return nil,domain.ErrInvalidTenantDataPolicy};if _,ok:=seen[v];ok{continue};seen[v]=struct{}{};out=append(out,v)};sort.Strings(out);return out,nil}
func policyWindow(nbValue,expValue string)(*time.Time,*time.Time,error){parse:=func(v string)(*time.Time,error){v=strings.TrimSpace(v);if v==""{return nil,nil};p,err:=time.Parse(time.RFC3339,v);if err!=nil{return nil,domain.ErrInvalidTenantDataPolicy};p=p.UTC();return &p,nil};nb,err:=parse(nbValue);if err!=nil{return nil,nil,err};exp,err:=parse(expValue);if err!=nil{return nil,nil,err};if nb!=nil&&exp!=nil&&!exp.After(*nb){return nil,nil,domain.ErrInvalidTenantDataPolicy};return nb,exp,nil}
func tenantDataPolicyDTO(p domain.DataPolicy,now time.Time)*accessv1.TenantDataPolicyDTO{effective,reason:=p.EffectiveAt(now);return &accessv1.TenantDataPolicyDTO{Id:p.ID,Name:p.Name,Status:p.Status,SiteIds:append([]string(nil),p.SiteIDs...),Version:p.Version,NotBefore:formatPolicyTime(p.NotBefore),ExpiresAt:formatPolicyTime(p.ExpiresAt),Effective:effective,InvalidReason:reason}}
func tenantDataPolicyReferenceDTO(r *domain.DataPolicyReference)*accessv1.TenantDataPolicyReferenceDTO{if r==nil{return nil};return &accessv1.TenantDataPolicyReferenceDTO{PolicyId:r.PolicyID,PolicyName:r.PolicyName,PolicyVersion:r.PolicyVersion,AcceptedVersion:r.AcceptedVersion,Effective:r.Effective,InvalidReason:r.InvalidReason}}
func formatPolicyTime(v *time.Time)string{if v==nil{return ""};return v.UTC().Format(time.RFC3339)}
func newTenantDataPolicyID()string{var v [16]byte;if _,err:=rand.Read(v[:]);err!=nil{panic(err)};return "policy-"+hex.EncodeToString(v[:])}
