// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	context "context"
	errors "errors"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
	accesspolicy "github.com/hvritual/biz/internal/access/policy"
	operation "github.com/hvritual/yunka.io/framework/operation"
)

type TenantLifecycleToAccessTenantMemberLifecycleChildCapability interface {
	BootstrapTenantOwnerMember(context.Context, *accessv1.BootstrapTenantOwnerMemberRequest) (*accessv1.TenantMemberDTO, error)
}

type c9TenantLifecycleToAccessTenantMemberLifecycleChildCapability struct {
	application TenantMemberLifecycleApplication
	executor    operation.Executor
}

func NewTenantLifecycleToAccessTenantMemberLifecycleChildCapability(application TenantMemberLifecycleApplication, executor operation.Executor) (TenantLifecycleToAccessTenantMemberLifecycleChildCapability, error) {
	if application == nil {
		return nil, errors.New("contract C9 child capability: target application is required")
	}
	if executor == nil {
		return nil, errors.New("contract C9 child capability: operation executor is required")
	}
	return &c9TenantLifecycleToAccessTenantMemberLifecycleChildCapability{application: application, executor: executor}, nil
}

func (capability *c9TenantLifecycleToAccessTenantMemberLifecycleChildCapability) BootstrapTenantOwnerMember(ctx context.Context, request *accessv1.BootstrapTenantOwnerMemberRequest) (*accessv1.TenantMemberDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantMemberLifecycleBootstrapTenantOwnerMember(), request, capability.application.BootstrapTenantOwnerMember)
}

type TenantLifecycleToAccessTenantRolePermissionChildCapability interface {
	BootstrapTenantOwnerRole(context.Context, *accessv1.BootstrapTenantOwnerRoleRequest) (*accessv1.TenantRoleDTO, error)
}

type c9TenantLifecycleToAccessTenantRolePermissionChildCapability struct {
	application TenantRolePermissionApplication
	executor    operation.Executor
}

func NewTenantLifecycleToAccessTenantRolePermissionChildCapability(application TenantRolePermissionApplication, executor operation.Executor) (TenantLifecycleToAccessTenantRolePermissionChildCapability, error) {
	if application == nil {
		return nil, errors.New("contract C9 child capability: target application is required")
	}
	if executor == nil {
		return nil, errors.New("contract C9 child capability: operation executor is required")
	}
	return &c9TenantLifecycleToAccessTenantRolePermissionChildCapability{application: application, executor: executor}, nil
}

func (capability *c9TenantLifecycleToAccessTenantRolePermissionChildCapability) BootstrapTenantOwnerRole(ctx context.Context, request *accessv1.BootstrapTenantOwnerRoleRequest) (*accessv1.TenantRoleDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantRolePermissionBootstrapTenantOwnerRole(), request, capability.application.BootstrapTenantOwnerRole)
}

// TenantLifecycleCapabilities exposes edge-owned C9 child-Operation wrappers for declared operation dependencies.
type TenantLifecycleCapabilities interface {
	AccessTenantMemberLifecycle() TenantLifecycleToAccessTenantMemberLifecycleChildCapability
	AccessTenantRolePermission() TenantLifecycleToAccessTenantRolePermissionChildCapability
}
