// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	"context"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
)

// TenantMemberBusinessScopeApplication is generated from PB and contains no business implementation.
type TenantMemberBusinessScopeApplication interface {
	GetTenantMemberBusinessScope(context.Context, *accessv1.GetTenantMemberBusinessScopeRequest) (*accessv1.TenantMemberBusinessScopeDTO, error)
	ListTenantMemberScopeCandidates(context.Context, *accessv1.ListTenantMemberScopeCandidatesRequest) (*accessv1.ListTenantMemberScopeCandidatesResponse, error)
	SetTenantMemberBusinessScope(context.Context, *accessv1.SetTenantMemberBusinessScopeRequest) (*accessv1.TenantMemberBusinessScopeDTO, error)
}
