// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	"context"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
)

// TenantRolePermissionApplication is generated from PB and contains no business implementation.
type TenantRolePermissionApplication interface {
	AssertTenantMemberDeactivationAllowed(context.Context, *accessv1.AssertTenantMemberDeactivationAllowedRequest) (*accessv1.AssertTenantMemberDeactivationAllowedResponse, error)
	AssignTenantRoleMember(context.Context, *accessv1.AssignTenantRoleMemberRequest) (*accessv1.TenantRoleDTO, error)
	BootstrapTenantOwnerRole(context.Context, *accessv1.BootstrapTenantOwnerRoleRequest) (*accessv1.TenantRoleDTO, error)
	CreateTenantDataPolicy(context.Context, *accessv1.CreateTenantDataPolicyRequest) (*accessv1.TenantDataPolicyDTO, error)
	CreateTenantRole(context.Context, *accessv1.CreateTenantRoleRequest) (*accessv1.TenantRoleDTO, error)
	DeleteTenantRole(context.Context, *accessv1.DeleteTenantRoleRequest) (*accessv1.TenantRoleDTO, error)
	DisableTenantRole(context.Context, *accessv1.DisableTenantRoleRequest) (*accessv1.TenantRoleDTO, error)
	EnableTenantRole(context.Context, *accessv1.EnableTenantRoleRequest) (*accessv1.TenantRoleDTO, error)
	GetTenantDataPolicy(context.Context, *accessv1.GetTenantDataPolicyRequest) (*accessv1.TenantDataPolicyDTO, error)
	GetTenantRole(context.Context, *accessv1.GetTenantRoleRequest) (*accessv1.TenantRoleDTO, error)
	ListTenantDataPolicies(context.Context, *accessv1.ListTenantDataPoliciesRequest) (*accessv1.ListTenantDataPoliciesResponse, error)
	ListTenantRoles(context.Context, *accessv1.ListTenantRolesRequest) (*accessv1.ListTenantRolesResponse, error)
	RevokeTenantDataPolicy(context.Context, *accessv1.RevokeTenantDataPolicyRequest) (*accessv1.TenantDataPolicyDTO, error)
	RevokeTenantRoleMember(context.Context, *accessv1.RevokeTenantRoleMemberRequest) (*accessv1.TenantRoleDTO, error)
	SetTenantRoleDataPolicy(context.Context, *accessv1.SetTenantRoleDataPolicyRequest) (*accessv1.TenantRoleDTO, error)
	SetTenantRolePermissions(context.Context, *accessv1.SetTenantRolePermissionsRequest) (*accessv1.TenantRoleDTO, error)
	UpdateTenantDataPolicy(context.Context, *accessv1.UpdateTenantDataPolicyRequest) (*accessv1.TenantDataPolicyDTO, error)
	UpdateTenantRole(context.Context, *accessv1.UpdateTenantRoleRequest) (*accessv1.TenantRoleDTO, error)
}
