// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	"context"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
)

// TenantDepartmentManagementApplication is generated from PB and contains no business implementation.
type TenantDepartmentManagementApplication interface {
	AssertTenantMemberDepartmentAssignmentAllowed(context.Context, *accessv1.AssertTenantMemberDepartmentAssignmentAllowedRequest) (*accessv1.AssertTenantMemberDepartmentAssignmentAllowedResponse, error)
	CreateTenantDepartment(context.Context, *accessv1.CreateTenantDepartmentRequest) (*accessv1.TenantDepartmentDTO, error)
	DisableTenantDepartment(context.Context, *accessv1.DisableTenantDepartmentRequest) (*accessv1.TenantDepartmentDTO, error)
	EnableTenantDepartment(context.Context, *accessv1.EnableTenantDepartmentRequest) (*accessv1.TenantDepartmentDTO, error)
	GetTenantDepartment(context.Context, *accessv1.GetTenantDepartmentRequest) (*accessv1.TenantDepartmentDTO, error)
	ListTenantDepartments(context.Context, *accessv1.ListTenantDepartmentsRequest) (*accessv1.ListTenantDepartmentsResponse, error)
	UpdateTenantDepartment(context.Context, *accessv1.UpdateTenantDepartmentRequest) (*accessv1.TenantDepartmentDTO, error)
}
