// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	context "context"
	errors "errors"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
	accesspolicy "github.com/hvritual/biz/internal/access/policy"
	operation "yunka.io/framework/operation"
)

type AccessTenantMemberLifecycleChildCapability interface {
	ActivateTenantMember(context.Context, *accessv1.ActivateTenantMemberRequest) (*accessv1.TenantMemberDTO, error)
	BootstrapTenantOwnerMember(context.Context, *accessv1.BootstrapTenantOwnerMemberRequest) (*accessv1.TenantMemberDTO, error)
	GetTenantMember(context.Context, *accessv1.GetTenantMemberRequest) (*accessv1.TenantMemberDTO, error)
	InviteTenantMember(context.Context, *accessv1.InviteTenantMemberRequest) (*accessv1.TenantMemberDTO, error)
	ListTenantMembers(context.Context, *accessv1.ListTenantMembersRequest) (*accessv1.ListTenantMembersResponse, error)
	RemoveTenantMember(context.Context, *accessv1.RemoveTenantMemberRequest) (*accessv1.TenantMemberDTO, error)
	SuspendTenantMember(context.Context, *accessv1.SuspendTenantMemberRequest) (*accessv1.TenantMemberDTO, error)
}

type c9AccessTenantMemberLifecycleChildCapability struct {
	application TenantMemberLifecycleApplication
	executor    operation.Executor
}

func NewAccessTenantMemberLifecycleChildCapability(application TenantMemberLifecycleApplication, executor operation.Executor) (AccessTenantMemberLifecycleChildCapability, error) {
	if application == nil {
		return nil, errors.New("contract C9 child capability: target application is required")
	}
	if executor == nil {
		return nil, errors.New("contract C9 child capability: operation executor is required")
	}
	return &c9AccessTenantMemberLifecycleChildCapability{application: application, executor: executor}, nil
}

func (capability *c9AccessTenantMemberLifecycleChildCapability) ActivateTenantMember(ctx context.Context, request *accessv1.ActivateTenantMemberRequest) (*accessv1.TenantMemberDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantMemberLifecycleActivateTenantMember(), request, capability.application.ActivateTenantMember)
}

func (capability *c9AccessTenantMemberLifecycleChildCapability) BootstrapTenantOwnerMember(ctx context.Context, request *accessv1.BootstrapTenantOwnerMemberRequest) (*accessv1.TenantMemberDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantMemberLifecycleBootstrapTenantOwnerMember(), request, capability.application.BootstrapTenantOwnerMember)
}

func (capability *c9AccessTenantMemberLifecycleChildCapability) GetTenantMember(ctx context.Context, request *accessv1.GetTenantMemberRequest) (*accessv1.TenantMemberDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantMemberLifecycleGetTenantMember(), request, capability.application.GetTenantMember)
}

func (capability *c9AccessTenantMemberLifecycleChildCapability) InviteTenantMember(ctx context.Context, request *accessv1.InviteTenantMemberRequest) (*accessv1.TenantMemberDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantMemberLifecycleInviteTenantMember(), request, capability.application.InviteTenantMember)
}

func (capability *c9AccessTenantMemberLifecycleChildCapability) ListTenantMembers(ctx context.Context, request *accessv1.ListTenantMembersRequest) (*accessv1.ListTenantMembersResponse, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantMemberLifecycleListTenantMembers(), request, capability.application.ListTenantMembers)
}

func (capability *c9AccessTenantMemberLifecycleChildCapability) RemoveTenantMember(ctx context.Context, request *accessv1.RemoveTenantMemberRequest) (*accessv1.TenantMemberDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantMemberLifecycleRemoveTenantMember(), request, capability.application.RemoveTenantMember)
}

func (capability *c9AccessTenantMemberLifecycleChildCapability) SuspendTenantMember(ctx context.Context, request *accessv1.SuspendTenantMemberRequest) (*accessv1.TenantMemberDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantMemberLifecycleSuspendTenantMember(), request, capability.application.SuspendTenantMember)
}

type AccessTenantRolePermissionChildCapability interface {
	AssignTenantRoleMember(context.Context, *accessv1.AssignTenantRoleMemberRequest) (*accessv1.TenantRoleDTO, error)
	BootstrapTenantOwnerRole(context.Context, *accessv1.BootstrapTenantOwnerRoleRequest) (*accessv1.TenantRoleDTO, error)
	CreateTenantRole(context.Context, *accessv1.CreateTenantRoleRequest) (*accessv1.TenantRoleDTO, error)
	DisableTenantRole(context.Context, *accessv1.DisableTenantRoleRequest) (*accessv1.TenantRoleDTO, error)
	EnableTenantRole(context.Context, *accessv1.EnableTenantRoleRequest) (*accessv1.TenantRoleDTO, error)
	GetTenantRole(context.Context, *accessv1.GetTenantRoleRequest) (*accessv1.TenantRoleDTO, error)
	ListTenantRoles(context.Context, *accessv1.ListTenantRolesRequest) (*accessv1.ListTenantRolesResponse, error)
	RevokeTenantRoleMember(context.Context, *accessv1.RevokeTenantRoleMemberRequest) (*accessv1.TenantRoleDTO, error)
	SetTenantRolePermissions(context.Context, *accessv1.SetTenantRolePermissionsRequest) (*accessv1.TenantRoleDTO, error)
	UpdateTenantRole(context.Context, *accessv1.UpdateTenantRoleRequest) (*accessv1.TenantRoleDTO, error)
}

type c9AccessTenantRolePermissionChildCapability struct {
	application TenantRolePermissionApplication
	executor    operation.Executor
}

func NewAccessTenantRolePermissionChildCapability(application TenantRolePermissionApplication, executor operation.Executor) (AccessTenantRolePermissionChildCapability, error) {
	if application == nil {
		return nil, errors.New("contract C9 child capability: target application is required")
	}
	if executor == nil {
		return nil, errors.New("contract C9 child capability: operation executor is required")
	}
	return &c9AccessTenantRolePermissionChildCapability{application: application, executor: executor}, nil
}

func (capability *c9AccessTenantRolePermissionChildCapability) AssignTenantRoleMember(ctx context.Context, request *accessv1.AssignTenantRoleMemberRequest) (*accessv1.TenantRoleDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantRolePermissionAssignTenantRoleMember(), request, capability.application.AssignTenantRoleMember)
}

func (capability *c9AccessTenantRolePermissionChildCapability) BootstrapTenantOwnerRole(ctx context.Context, request *accessv1.BootstrapTenantOwnerRoleRequest) (*accessv1.TenantRoleDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantRolePermissionBootstrapTenantOwnerRole(), request, capability.application.BootstrapTenantOwnerRole)
}

func (capability *c9AccessTenantRolePermissionChildCapability) CreateTenantRole(ctx context.Context, request *accessv1.CreateTenantRoleRequest) (*accessv1.TenantRoleDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantRolePermissionCreateTenantRole(), request, capability.application.CreateTenantRole)
}

func (capability *c9AccessTenantRolePermissionChildCapability) DisableTenantRole(ctx context.Context, request *accessv1.DisableTenantRoleRequest) (*accessv1.TenantRoleDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantRolePermissionDisableTenantRole(), request, capability.application.DisableTenantRole)
}

func (capability *c9AccessTenantRolePermissionChildCapability) EnableTenantRole(ctx context.Context, request *accessv1.EnableTenantRoleRequest) (*accessv1.TenantRoleDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantRolePermissionEnableTenantRole(), request, capability.application.EnableTenantRole)
}

func (capability *c9AccessTenantRolePermissionChildCapability) GetTenantRole(ctx context.Context, request *accessv1.GetTenantRoleRequest) (*accessv1.TenantRoleDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantRolePermissionGetTenantRole(), request, capability.application.GetTenantRole)
}

func (capability *c9AccessTenantRolePermissionChildCapability) ListTenantRoles(ctx context.Context, request *accessv1.ListTenantRolesRequest) (*accessv1.ListTenantRolesResponse, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantRolePermissionListTenantRoles(), request, capability.application.ListTenantRoles)
}

func (capability *c9AccessTenantRolePermissionChildCapability) RevokeTenantRoleMember(ctx context.Context, request *accessv1.RevokeTenantRoleMemberRequest) (*accessv1.TenantRoleDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantRolePermissionRevokeTenantRoleMember(), request, capability.application.RevokeTenantRoleMember)
}

func (capability *c9AccessTenantRolePermissionChildCapability) SetTenantRolePermissions(ctx context.Context, request *accessv1.SetTenantRolePermissionsRequest) (*accessv1.TenantRoleDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantRolePermissionSetTenantRolePermissions(), request, capability.application.SetTenantRolePermissions)
}

func (capability *c9AccessTenantRolePermissionChildCapability) UpdateTenantRole(ctx context.Context, request *accessv1.UpdateTenantRoleRequest) (*accessv1.TenantRoleDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantRolePermissionUpdateTenantRole(), request, capability.application.UpdateTenantRole)
}

// TenantLifecycleCapabilities exposes only C9 child-Operation wrappers for declared application dependencies.
type TenantLifecycleCapabilities interface {
	AccessTenantMemberLifecycle() AccessTenantMemberLifecycleChildCapability
	AccessTenantRolePermission() AccessTenantRolePermissionChildCapability
}
