// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	"context"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
)

// TenantProfileManagementApplication is generated from PB and contains no business implementation.
type TenantProfileManagementApplication interface {
	GetTenantBranding(context.Context, *accessv1.GetTenantBrandingRequest) (*accessv1.TenantBrandingDTO, error)
	GetTenantProfile(context.Context, *accessv1.GetTenantProfileRequest) (*accessv1.TenantProfileDTO, error)
	UpdateTenantBranding(context.Context, *accessv1.UpdateTenantBrandingRequest) (*accessv1.TenantBrandingDTO, error)
	UpdateTenantProfile(context.Context, *accessv1.UpdateTenantProfileRequest) (*accessv1.TenantProfileDTO, error)
}
