// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	context "context"
	errors "errors"
	deviceopsv1 "github.com/hvritual/biz/contracts/gen/deviceops/v1"
	deviceopspolicy "github.com/hvritual/biz/internal/deviceops/policy"
	operation "yunka.io/framework/operation"
)

type TenantMemberBusinessScopeToDeviceopsSiteManagementChildCapability interface {
	ListAssignableMemberSites(context.Context, *deviceopsv1.SiteScopeDirectoryRequest) (*deviceopsv1.SiteScopeDirectoryResponse, error)
}

// TenantMemberBusinessScopeToDeviceopsSiteManagementTargetApplication is the consumer-edge-owned view of the target Application.
type TenantMemberBusinessScopeToDeviceopsSiteManagementTargetApplication interface {
	ListAssignableMemberSites(context.Context, *deviceopsv1.SiteScopeDirectoryRequest) (*deviceopsv1.SiteScopeDirectoryResponse, error)
}

type c9TenantMemberBusinessScopeToDeviceopsSiteManagementChildCapability struct {
	application TenantMemberBusinessScopeToDeviceopsSiteManagementTargetApplication
	executor    operation.Executor
}

func NewTenantMemberBusinessScopeToDeviceopsSiteManagementChildCapability(application TenantMemberBusinessScopeToDeviceopsSiteManagementTargetApplication, executor operation.Executor) (TenantMemberBusinessScopeToDeviceopsSiteManagementChildCapability, error) {
	if application == nil {
		return nil, errors.New("contract C9 child capability: target application is required")
	}
	if executor == nil {
		return nil, errors.New("contract C9 child capability: operation executor is required")
	}
	return &c9TenantMemberBusinessScopeToDeviceopsSiteManagementChildCapability{application: application, executor: executor}, nil
}

func (capability *c9TenantMemberBusinessScopeToDeviceopsSiteManagementChildCapability) ListAssignableMemberSites(ctx context.Context, request *deviceopsv1.SiteScopeDirectoryRequest) (*deviceopsv1.SiteScopeDirectoryResponse, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, deviceopspolicy.OperationPlanSiteManagementListAssignableMemberSites(), request, capability.application.ListAssignableMemberSites)
}

// TenantMemberBusinessScopeCapabilities exposes edge-owned C9 child-Operation wrappers for declared operation dependencies.
type TenantMemberBusinessScopeCapabilities interface {
	DeviceopsSiteManagement() TenantMemberBusinessScopeToDeviceopsSiteManagementChildCapability
}
