// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	context "context"
	errors "errors"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
	deviceopsv1 "github.com/hvritual/biz/contracts/gen/deviceops/v1"
	accesspolicy "github.com/hvritual/biz/internal/access/policy"
	deviceopsapplication "github.com/hvritual/biz/internal/deviceops/application"
	deviceopspolicy "github.com/hvritual/biz/internal/deviceops/policy"
	operation "yunka.io/framework/operation"
)

type TenantDelegationManagementToAccessTenantLifecycleChildCapability interface {
	AssertTenantActive(context.Context, *accessv1.AssertTenantActiveRequest) (*accessv1.AssertTenantActiveResponse, error)
}

type c9TenantDelegationManagementToAccessTenantLifecycleChildCapability struct {
	application TenantLifecycleApplication
	executor    operation.Executor
}

func NewTenantDelegationManagementToAccessTenantLifecycleChildCapability(application TenantLifecycleApplication, executor operation.Executor) (TenantDelegationManagementToAccessTenantLifecycleChildCapability, error) {
	if application == nil {
		return nil, errors.New("contract C9 child capability: target application is required")
	}
	if executor == nil {
		return nil, errors.New("contract C9 child capability: operation executor is required")
	}
	return &c9TenantDelegationManagementToAccessTenantLifecycleChildCapability{application: application, executor: executor}, nil
}

func (capability *c9TenantDelegationManagementToAccessTenantLifecycleChildCapability) AssertTenantActive(ctx context.Context, request *accessv1.AssertTenantActiveRequest) (*accessv1.AssertTenantActiveResponse, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantLifecycleAssertTenantActive(), request, capability.application.AssertTenantActive)
}

type TenantDelegationManagementToDeviceopsDeviceManagementChildCapability interface {
	AssertDeviceOwnedByActorTenant(context.Context, *deviceopsv1.AssertDeviceOwnedByActorTenantRequest) (*deviceopsv1.AssertDeviceOwnedByActorTenantResponse, error)
}

type c9TenantDelegationManagementToDeviceopsDeviceManagementChildCapability struct {
	application deviceopsapplication.DeviceManagementApplication
	executor    operation.Executor
}

func NewTenantDelegationManagementToDeviceopsDeviceManagementChildCapability(application deviceopsapplication.DeviceManagementApplication, executor operation.Executor) (TenantDelegationManagementToDeviceopsDeviceManagementChildCapability, error) {
	if application == nil {
		return nil, errors.New("contract C9 child capability: target application is required")
	}
	if executor == nil {
		return nil, errors.New("contract C9 child capability: operation executor is required")
	}
	return &c9TenantDelegationManagementToDeviceopsDeviceManagementChildCapability{application: application, executor: executor}, nil
}

func (capability *c9TenantDelegationManagementToDeviceopsDeviceManagementChildCapability) AssertDeviceOwnedByActorTenant(ctx context.Context, request *deviceopsv1.AssertDeviceOwnedByActorTenantRequest) (*deviceopsv1.AssertDeviceOwnedByActorTenantResponse, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, deviceopspolicy.OperationPlanDeviceManagementAssertDeviceOwnedByActorTenant(), request, capability.application.AssertDeviceOwnedByActorTenant)
}

// TenantDelegationManagementCapabilities exposes edge-owned C9 child-Operation wrappers for declared operation dependencies.
type TenantDelegationManagementCapabilities interface {
	AccessTenantLifecycle() TenantDelegationManagementToAccessTenantLifecycleChildCapability
	DeviceopsDeviceManagement() TenantDelegationManagementToDeviceopsDeviceManagementChildCapability
}
