// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	"context"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
)

// TenantDelegationApplication is generated from PB and contains no business implementation.
type TenantDelegationManagementApplication interface {
	GetTenantDelegation(context.Context, *accessv1.GetTenantDelegationRequest) (*accessv1.TenantDelegationDTO, error)
	GrantTenantDeviceDelegation(context.Context, *accessv1.GrantTenantDeviceDelegationRequest) (*accessv1.TenantDelegationDTO, error)
	ListTenantDelegations(context.Context, *accessv1.ListTenantDelegationsRequest) (*accessv1.ListTenantDelegationsResponse, error)
	RevokeTenantDelegation(context.Context, *accessv1.RevokeTenantDelegationRequest) (*accessv1.TenantDelegationDTO, error)
}
