// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	"context"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
)

// TenantLifecycleApplication is generated from PB and contains no business implementation.
type TenantLifecycleApplication interface {
	ActivateTenant(context.Context, *accessv1.ActivateTenantRequest) (*accessv1.TenantDTO, error)
	CloseTenant(context.Context, *accessv1.CloseTenantRequest) (*accessv1.TenantDTO, error)
	CreateTenant(context.Context, *accessv1.CreateTenantRequest) (*accessv1.TenantDTO, error)
	GetTenant(context.Context, *accessv1.GetTenantRequest) (*accessv1.TenantDTO, error)
	ListTenants(context.Context, *accessv1.ListTenantsRequest) (*accessv1.ListTenantsResponse, error)
	SuspendTenant(context.Context, *accessv1.SuspendTenantRequest) (*accessv1.TenantDTO, error)
	UpdateTenant(context.Context, *accessv1.UpdateTenantRequest) (*accessv1.TenantDTO, error)
}
