<script setup lang="ts">
import { UiButton } from '@/ui/base'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import type { Member } from '@/types/enterprise'
import { useEnterpriseStore } from '@/stores/enterprise'
import { formatDateOnly, formatDateTime } from '@/i18n'
import StatusBadge from '@/ui/common/StatusBadge.vue'
import AvatarMark from '@/ui/common/AvatarMark.vue'
import AppIcon from '@/ui/common/AppIcon.vue'
import MemberRoleTags from './MemberRoleTags.vue'
const props=defineProps<{member:Member}>(),emit=defineEmits<{logs:[]}>(),store=useEnterpriseStore(),{t}=useI18n()
const department=computed(()=>store.departments.find(d=>d.id===props.member.departmentId)),leader=computed(()=>store.members.find(m=>m.id===department.value?.leaderId)),recent=computed(()=>store.logs.filter(l=>l.target===props.member.name).slice(0,3))
const scopeKey=computed(()=>props.member.scope==='department_tree'?'department':props.member.scope==='self'?'own':props.member.scope)
const scopeLabel=computed(()=>t(`members.scopes.${scopeKey.value}`))
const scopeDescription=computed(()=>({all:t('members.profile.scopeAll'),department:t(props.member.scope==='department_tree'?'members.profile.scopeDepartmentTree':'members.profile.scopeDepartment'),own:t('members.profile.scopeSelf'),custom:t('members.profile.scopeCustom')} as Record<string,string>)[scopeKey.value]??t('members.profile.scopeCustom'))
const statusLabel=computed(()=>t(`members.statuses.${props.member.status}`))
const joined=computed(()=>props.member.joinedAt?formatDateOnly(props.member.joinedAt):(store.previewMode?t('members.profile.notRecorded'):t('members.profile.serverUnsupported')))
const lastLogin=computed(()=>props.member.lastLogin?formatDateTime(props.member.lastLogin,store.company.timezone||'Asia/Shanghai'):t('members.neverLoggedIn'))
</script>
<template>
  <section class="detail-section"><h3>{{ t('members.profile.personal') }}</h3><dl class="member-facts"><dt>{{ t('members.action.name') }}</dt><dd>{{ member.name }}</dd><dt>{{ t('members.profile.phone') }}</dt><dd>{{ member.phone||t('members.profile.notFilled') }}</dd><dt>{{ t('members.action.email') }}</dt><dd>{{ member.email }}</dd><dt>{{ t('members.profile.employeeId') }}</dt><dd>{{ member.employeeId||t('members.profile.notFilled') }}</dd><dt>{{ t('members.profile.accountStatus') }}</dt><dd><StatusBadge :text="statusLabel" :tone="member.status==='active'?'success':member.status==='suspended'?'danger':'neutral'"/></dd><dt>{{ t('members.profile.joinedAt') }}</dt><dd class="numeric">{{ joined }}</dd><dt>{{ t('members.profile.lastLogin') }}</dt><dd class="numeric">{{ lastLogin }}</dd><dt>{{ t('members.profile.note') }}</dt><dd>{{ member.note||(store.previewMode?t('members.profile.noNote'):t('members.profile.serverUnsupported')) }}</dd></dl></section>
  <section class="detail-section"><h3>{{ t('members.profile.organizationInfo') }}</h3><dl class="member-facts"><dt>{{ t('members.department') }}</dt><dd class="fact-with-icon"><span class="fact-icon"><AppIcon name="organization" :size="16"/></span>{{ store.departmentName(member.departmentId) }}</dd><dt>{{ t('members.profile.departmentHead') }}</dt><dd class="fact-with-icon"><AvatarMark v-if="leader" :name="leader.name" :size="24" tone="solid"/>{{ leader?.name||t('members.profile.notSet') }}</dd><dt>{{ t('members.profile.position') }}</dt><dd>{{ member.position }}</dd></dl></section>
  <section class="detail-section"><h3>{{ t('members.profile.rolePermissions') }}</h3><div v-for="role in store.roles.filter(r=>member.roleIds.includes(r.id))" :key="role.id" class="role-summary"><MemberRoleTags :ids="[role.id]"/><p>{{ role.description }}</p></div></section>
  <section class="detail-section"><h3>{{ t('members.profile.dataPermissions') }}</h3><span class="scope-label">{{ scopeLabel }}</span><p class="detail-hint">{{ scopeDescription }}</p></section>
  <section class="detail-section activity-section"><div class="row-between"><h3>{{ t('members.profile.recentActivity') }}</h3><UiButton class="btn-link" @click="emit('logs')">{{ t('members.profile.viewMore') }}<AppIcon name="right" :size="12"/></UiButton></div><ol class="member-timeline"><li v-for="log in recent" :key="log.id"><span>{{ log.time }}</span><strong>{{ log.action }}</strong><small>{{ log.actor }} · {{ log.reason||t('members.detail.previewAction') }}</small></li><li v-if="store.previewMode"><span>{{ joined }}</span><strong>{{ t('members.profile.joinedCompany') }}</strong><small>{{ t('members.profile.relationshipRecord') }}</small></li></ol></section>
</template>
<style scoped>
.detail-section{padding:18px 0;border-bottom:1px solid var(--color-border)}.detail-section:first-child{padding-top:16px}.detail-section h3{font-size:13px;margin-bottom:14px}.member-facts{margin:0;display:grid;grid-template-columns:90px minmax(0,1fr);gap:10px;font-size:12px;align-items:center}.member-facts dt{color:var(--color-text-muted)}.member-facts dd{margin:0;overflow-wrap:anywhere;min-width:0}.member-facts :deep(.status-badge){font-size:11px}.fact-with-icon{display:flex;align-items:center;gap:8px}.fact-icon{display:grid;place-items:center;width:25px;height:25px;color:var(--color-primary);background:var(--color-primary-soft);border-radius:5px}.role-summary{display:flex;align-items:flex-start;gap:10px}.role-summary+.role-summary{margin-top:10px}.role-summary p,.detail-hint{font-size:11px;color:var(--color-text-muted);line-height:1.8}.role-summary :deep(.member-role-tags){flex-shrink:0}.scope-label{display:inline-flex;color:var(--color-success);background:var(--color-success-soft);padding:3px 8px;border-radius:4px;font-size:11px}.detail-hint{margin-top:8px}.activity-section{border-bottom:0}.activity-section .row-between{margin-bottom:14px}.activity-section h3{margin:0}.activity-section .btn-link{font-size:11px}.member-timeline{list-style:none;margin:0 0 0 3px;padding:0 0 0 17px;border-left:1px solid var(--color-border)}.member-timeline li{position:relative;padding-bottom:16px;display:flex;gap:3px 10px;flex-wrap:wrap;font-size:11px}.member-timeline li::before{content:'';position:absolute;left:-21px;top:6px;width:7px;height:7px;border-radius:50%;background:var(--color-primary);box-shadow:0 0 0 3px var(--color-surface)}.member-timeline span,.member-timeline small{color:var(--color-text-muted);font-size:10px}.member-timeline strong{font-weight:500}.member-timeline small{width:100%}
</style>
