<script setup lang="ts">
import { UiButton, UiInput, UiOption, UiSelect, UiTextarea } from '@/ui/base'
import { computed, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import type { Member, MemberAction, DataScope } from '@/types/enterprise'
import { memberActionError } from '@/services/memberPolicy'
import { useEnterpriseStore } from '@/stores/enterprise'
import { useUiStore } from '@/stores/ui'
import UiDialog from '@/ui/common/UiDialog.vue'
import AppIcon from '@/ui/common/AppIcon.vue'
import AvatarMark from '@/ui/common/AvatarMark.vue'
const props=defineProps<{open:boolean;action:MemberAction;member:Member|null}>(),emit=defineEmits<{close:[]}>(),store=useEnterpriseStore(),ui=useUiStore(),{t}=useI18n()
const draft=ref<Member|null>(null),reason=ref(''),error=ref(''),confirmed=ref(false),busy=ref(false)
const structural=computed(()=>['create','invite','edit'].includes(props.action)),danger=computed(()=>['suspend','remove'].includes(props.action)),blocking=computed(()=>props.member?memberActionError(props.action,props.member,store.members,store.roles,draft.value?.roleIds):null)
const title=computed(()=>t(`members.action.titles.${props.action}`))
const scopes=['all','department','own','custom'] as const
function scopeKey(scope:DataScope){return scope==='department_tree'?'department':scope==='self'?'own':scope}
function scopeLabel(scope:DataScope){return t(`members.scopes.${scopeKey(scope)}`)}
function newMemberDraft(action:MemberAction):Member{const department=store.departments.find(item=>item.enabled),role=store.roles.find(item=>item.enabled&&!item.builtin)??store.roles.find(item=>item.enabled);return{id:crypto.randomUUID(),name:'',email:'',phone:'',employeeId:'',departmentId:department?.id??'',position:'',roleIds:role?[role.id]:[],scope:role?.scope??'custom',status:action==='invite'?'invited':'active',online:false,joinedAt:store.previewMode?new Date().toISOString().slice(0,10):'',lastLogin:null,version:0,mfa:false,note:''}}
watch(()=>[props.open,props.action,props.member] as const,()=>{error.value='';reason.value='';confirmed.value=false;draft.value=props.member?(JSON.parse(JSON.stringify(props.member)) as Member):newMemberDraft(props.action)},{immediate:true})
function toggleRole(id:string){if(!draft.value)return;const ids=draft.value.roleIds;draft.value.roleIds=ids.includes(id)?ids.filter(i=>i!==id):[...ids,id]}
async function submit(){if(!draft.value)return;error.value='';if(blocking.value){error.value=blocking.value;return}if((danger.value||props.action==='reset')&&!confirmed.value){error.value=t('members.action.confirmImpact');return}busy.value=true;try{if(structural.value||props.action==='role')await store.saveMember(draft.value,props.action,props.member?.version??0);else if(['suspend','activate','remove'].includes(props.action))await store.changeStatus(draft.value.id,props.action as 'suspend'|'activate'|'remove',props.member!.version,reason.value);else if(props.action==='reset')await store.requestPasswordReset(draft.value,reason.value);const message=store.previewMode?props.action==='reset'?t('members.action.previewResetToast'):props.action==='invite'?t('members.action.previewInviteToast'):t('members.action.previewSaveToast'):t('members.action.serverSaveToast');ui.toast(message,props.action==='reset'||props.action==='invite'?'info':'success');emit('close')}catch(e){error.value=e instanceof Error?e.message:t('members.action.failure')}finally{busy.value=false}}
</script>
<template>
  <UiDialog :open="open" :title="title" :width="structural||action==='role'?'820px':'560px'" @close="emit('close')"><div v-if="draft" class="page-stack"><div v-if="member" class="member-summary"><AvatarMark :name="member.name" :size="44"/><div><h3>{{ member.name }}</h3><p>{{ store.departmentName(member.departmentId) }} · {{ member.email }}</p></div></div><div v-if="blocking" class="notice-box danger"><AppIcon name="shield"/>{{ blocking }}</div>
    <form v-if="structural" id="member-form" @submit.prevent="submit"><section class="form-section"><h3>{{ t('members.action.basic') }}</h3><div class="form-grid"><label class="field"><span class="required">{{ t('members.action.name') }}</span><UiInput v-model="draft.name" class="input" maxlength="40" required :placeholder="t('members.action.namePlaceholder')"/></label><label class="field"><span class="required">{{ t('members.action.email') }}</span><UiInput v-model="draft.email" class="input" type="email" required :readonly="!store.previewMode&&action==='edit'" placeholder="name@example.com"/><small v-if="action==='edit'&&store.previewMode">{{ t('members.action.editPreviewEmail') }}</small><small v-else-if="action==='edit'">{{ t('members.action.editServerEmail') }}</small></label><label class="field"><span>{{ t('members.action.phone') }}</span><UiInput v-model="draft.phone" class="input" maxlength="20" :placeholder="t('members.action.optional')"/></label><label class="field"><span>{{ t('members.action.employeeId') }}</span><UiInput v-model="draft.employeeId" class="input" maxlength="40" :placeholder="t('members.action.employeeIdPlaceholder')"/></label></div></section>
    <section class="form-section"><h3>{{ t('members.action.organizationPosition') }}</h3><div class="form-grid"><label class="field"><span class="required">{{ t('members.action.department') }}</span><UiSelect v-model="draft.departmentId" class="select"><UiOption v-for="d in store.departments" :key="d.id" :value="d.id">{{ d.name }}</UiOption></UiSelect></label><label class="field"><span>{{ t('members.action.position') }}</span><UiInput v-model="draft.position" class="input" maxlength="40"/></label><label class="field"><span>{{ t('members.action.joinedAt') }}</span><UiInput v-if="store.previewMode" v-model="draft.joinedAt" class="input" type="date"/><UiInput v-else class="input" :value="t('members.action.serverUnsupported')" readonly/><small v-if="!store.previewMode">{{ t('members.action.joinedUnsupported') }}</small></label><label class="field"><span>{{ t('members.action.scope') }}</span><UiSelect v-if="store.previewMode" v-model="draft.scope" class="select"><UiOption v-for="key in scopes" :key="key" :value="key">{{ t(`members.scopes.${key}`) }}</UiOption></UiSelect><UiInput v-else class="input" :value="member?scopeLabel(draft.scope):t('members.action.scopeDerived')" readonly/><small v-if="!store.previewMode">{{ t('members.action.scopeUnsupported') }}</small></label></div></section>
    <section v-if="action!=='edit'" class="form-section"><h3>{{ t('members.action.roles') }}</h3><div class="role-options"><label v-for="r in store.roles.filter(r=>r.enabled)" :key="r.id" :class="['role-option',{chosen:draft.roleIds.includes(r.id)}]"><UiInput type="checkbox" :checked="draft.roleIds.includes(r.id)" @change="toggleRole(r.id)"/><span>{{ r.name }}</span></label></div></section><section class="form-section"><label v-if="store.previewMode" class="field"><span>{{ t('members.action.note') }}</span><UiTextarea v-model="draft.note" class="textarea" rows="2" maxlength="500" :placeholder="t('members.action.notePlaceholder')"/></label><div v-else class="notice-box">{{ t('members.action.noteUnsupported') }}</div></section></form>
    <template v-else-if="action==='role'"><div class="notice-box"><AppIcon name="shield"/>{{ store.previewMode?t('members.action.previewRoleNotice'):t('members.action.serverRoleNotice') }}</div><h3>{{ t('members.action.chooseRole') }}</h3><div class="role-options"><label v-for="r in store.roles.filter(r=>r.enabled)" :key="r.id" :class="['role-option',{chosen:draft.roleIds.includes(r.id)}]"><UiInput type="checkbox" :checked="draft.roleIds.includes(r.id)" @change="toggleRole(r.id)"/><span>{{ r.name }}</span></label></div><label class="field"><span>{{ t('members.action.targetScope') }}</span><UiSelect v-if="store.previewMode" v-model="draft.scope" class="select"><UiOption v-for="key in scopes" :key="key" :value="key">{{ t(`members.scopes.${key}`) }}</UiOption></UiSelect><UiInput v-else class="input" :value="t('members.action.scopeDerived')" readonly/></label><div class="change-preview"><div><small>{{ t('members.action.before') }}</small><strong>{{ member?.roleIds.map(store.roleName).join(', ') }}</strong><p>{{ scopeLabel(member!.scope) }}</p></div><AppIcon name="arrow"/><div><small>{{ t('members.action.after') }}</small><strong>{{ draft.roleIds.map(store.roleName).join(', ')||t('members.action.noSelection') }}</strong><p>{{ store.previewMode?scopeLabel(draft.scope as DataScope):t('members.action.serverDerived') }}</p></div></div></template>
    <template v-else-if="action==='reset'"><div class="notice-box warning"><AppIcon name="key"/><span>{{ t('members.action.resetNotice') }}</span></div><label class="field"><span>{{ t('members.action.recipient') }}</span><UiInput class="input" :value="draft.email" readonly/></label><label class="field"><span class="required">{{ t('members.action.reason') }}</span><UiTextarea v-model="reason" class="textarea" maxlength="300" :placeholder="t('members.action.resetReasonPlaceholder')"/></label><label class="option-line"><UiInput v-model="confirmed" type="checkbox"/>{{ t('members.action.resetConfirm') }}</label><p class="muted">{{ t('members.action.resetPolicy') }}</p></template>
    <template v-else><div :class="['notice-box',danger?'danger':'warning']"><AppIcon :name="danger?'lock':'shield'"/><span>{{ action==='suspend'?t('members.action.suspendNotice'):action==='remove'?t('members.action.removeNotice'):t('members.action.activateNotice') }}</span></div><label v-if="danger" class="option-line"><UiInput v-model="confirmed" type="checkbox"/>{{ action==='remove'?t('members.action.removeConfirm'):t('members.action.suspendConfirm') }}</label><label class="field"><span class="required">{{ t('members.action.reason') }}</span><UiTextarea v-model="reason" class="textarea" maxlength="300" :placeholder="t('members.action.reasonPlaceholder')"/></label><p class="muted">{{ t('members.action.currentRoleScope',{roles:draft.roleIds.map(store.roleName).join(', '),scope:scopeLabel(draft.scope)}) }}</p></template>
    <div v-if="action==='invite'" class="notice-box"><AppIcon name="mail"/>{{ store.previewMode?t('members.action.invitePreview'):t('members.action.inviteServer') }}</div><p v-if="error" class="form-error" role="alert">{{ error }}</p></div>
    <template #footer><UiButton class="btn" @click="emit('close')">{{ t('common.cancel') }}</UiButton><UiButton :class="['btn',danger?'btn-danger':'btn-primary']" :disabled="busy||Boolean(blocking)" @click="submit">{{ busy?t('common.processing'):action==='reset'?t('members.action.resetRequest'):action==='invite'?t('members.action.createInvite'):action==='suspend'?t('members.action.confirmSuspend'):action==='activate'?t('members.action.confirmActivate'):action==='remove'?t('members.action.confirmRemove'):t('members.action.saveChanges') }}</UiButton></template></UiDialog>
</template>
<style scoped>
.member-summary{display:flex;align-items:center;gap:12px;padding:13px 16px;border-radius:10px;background:var(--color-surface-soft)}.member-summary p{font-size:12px;color:var(--color-text-muted);margin-top:3px}.role-options{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.role-option{display:flex;gap:9px;align-items:center;border:1px solid var(--color-border);border-radius:8px;padding:12px;font-size:13px}.role-option.chosen{background:var(--color-primary-soft);border-color:var(--color-primary);color:var(--color-primary)}.change-preview{display:grid;grid-template-columns:1fr 24px 1fr;gap:18px;align-items:center;padding:18px;background:var(--color-surface-soft);border-radius:10px}.change-preview small{display:block;color:var(--color-text-muted);margin-bottom:6px}.change-preview strong{display:block;font-size:14px}.change-preview p{font-size:12px;color:var(--color-text-secondary);margin-top:6px}@media(max-width:767px){.role-options{grid-template-columns:repeat(2,minmax(0,1fr))}.role-option{padding:10px;font-size:12px}}
</style>
