// Code generated by yunka assembly compiler; DO NOT EDIT.

package assembly

import (
	"context"
	errors "errors"
	fmt "fmt"
	deviceopsapplication "github.com/hvritual/biz/internal/deviceops/application"
	deviceopsrest "github.com/hvritual/biz/internal/deviceops/transport/rest"
	deviceopsrpc "github.com/hvritual/biz/internal/deviceops/transport/rpc"
	grpc "google.golang.org/grpc"
	http "net/http"
	"yunka.io/framework/core"
	modulecatalog "yunka.io/framework/core/modulecatalog"
	kernel "yunka.io/framework/kernel"
	operation "yunka.io/framework/operation"
	platform "yunka.io/framework/platform"
)

const AssemblyPlanDigest = "1d2d31c9b0c723aaadaede2ed0eb8d627a1684a74f1c5988b1b4d1468cdb5514"

type DeviceopsDeviceManagementDependencies struct {
}

type DeviceopsDeviceTransferDependencies struct {
	DeviceopsDeviceManagement deviceopsapplication.DeviceopsDeviceManagementChildCapability
	DeviceopsSiteManagement   deviceopsapplication.DeviceopsSiteManagementChildCapability
}

type DeviceopsSiteManagementDependencies struct {
}

type ApplicationFactories interface {
	BuildDeviceopsDeviceManagement(DeviceopsDeviceManagementDependencies) (deviceopsapplication.DeviceManagementApplication, error)
	BuildDeviceopsDeviceTransfer(DeviceopsDeviceTransferDependencies) (deviceopsapplication.DeviceTransferApplication, error)
	BuildDeviceopsSiteManagement(DeviceopsSiteManagementDependencies) (deviceopsapplication.SiteManagementApplication, error)
}

type Applications struct {
	DeviceopsDeviceManagement deviceopsapplication.DeviceManagementApplication
	DeviceopsDeviceTransfer   deviceopsapplication.DeviceTransferApplication
	DeviceopsSiteManagement   deviceopsapplication.SiteManagementApplication
}

func BuildApplications(factories ApplicationFactories, executor operation.Executor) (Applications, error) {
	if factories == nil {
		return Applications{}, errors.New("yunka assembly: application factories are required")
	}
	if executor == nil {
		return Applications{}, errors.New("yunka assembly: operation executor is required for child capabilities")
	}
	var applications Applications
	var err error
	applications.DeviceopsDeviceManagement, err = factories.BuildDeviceopsDeviceManagement(DeviceopsDeviceManagementDependencies{})
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build application deviceops/device_management: %w", err)
	}
	if applications.DeviceopsDeviceManagement == nil {
		return Applications{}, errors.New("yunka assembly: application factory returned nil for deviceops/device_management")
	}
	applications.DeviceopsSiteManagement, err = factories.BuildDeviceopsSiteManagement(DeviceopsSiteManagementDependencies{})
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build application deviceops/site_management: %w", err)
	}
	if applications.DeviceopsSiteManagement == nil {
		return Applications{}, errors.New("yunka assembly: application factory returned nil for deviceops/site_management")
	}
	deviceopsDeviceTransferDeviceopsDeviceManagementCapability, err := deviceopsapplication.NewDeviceopsDeviceManagementChildCapability(applications.DeviceopsDeviceManagement, executor)
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build deviceops/device_transfer dependency deviceops/device_management: %w", err)
	}
	deviceopsDeviceTransferDeviceopsSiteManagementCapability, err := deviceopsapplication.NewDeviceopsSiteManagementChildCapability(applications.DeviceopsSiteManagement, executor)
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build deviceops/device_transfer dependency deviceops/site_management: %w", err)
	}
	applications.DeviceopsDeviceTransfer, err = factories.BuildDeviceopsDeviceTransfer(DeviceopsDeviceTransferDependencies{DeviceopsDeviceManagement: deviceopsDeviceTransferDeviceopsDeviceManagementCapability, DeviceopsSiteManagement: deviceopsDeviceTransferDeviceopsSiteManagementCapability})
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build application deviceops/device_transfer: %w", err)
	}
	if applications.DeviceopsDeviceTransfer == nil {
		return Applications{}, errors.New("yunka assembly: application factory returned nil for deviceops/device_transfer")
	}
	return applications, nil
}

type KernelDependencies struct {
	Platform *platform.Provider
	Catalog  *modulecatalog.Catalog
}

func KernelOptions(dependencies KernelDependencies) kernel.Options {
	return kernel.Options{Platform: dependencies.Platform, Catalog: dependencies.Catalog}
}

func ExpectedModuleRequirements() modulecatalog.RequirementSet {
	return modulecatalog.RequirementSet{
		Modules:   []string{"deviceops"},
		Configs:   []modulecatalog.ConfigRequirement{{Module: "deviceops", Key: "modules.deviceops"}},
		Logger:    true,
		Databases: []modulecatalog.DatabaseRequirement{{Name: "primary"}},
	}
}

type TransportBindings struct {
	HTTP *http.ServeMux
	RPC  grpc.ServiceRegistrar
}

func RegisterTransports(bindings TransportBindings, applications Applications, executor operation.Executor) error {
	if executor == nil {
		return errors.New("yunka assembly: operation executor is required for transport registration")
	}
	if bindings.HTTP == nil {
		return errors.New("yunka assembly: HTTP mux is required")
	}
	if bindings.RPC == nil {
		return errors.New("yunka assembly: gRPC registrar is required")
	}
	if applications.DeviceopsDeviceManagement == nil {
		return errors.New("yunka assembly: application deviceops/device_management is required for transport registration")
	}
	if err := deviceopsrest.RegisterDeviceManagementOperationExecutor(bindings.HTTP, applications.DeviceopsDeviceManagement, executor); err != nil {
		return fmt.Errorf("yunka assembly: register HTTP deviceops/device_management: %w", err)
	}
	if err := deviceopsrpc.RegisterDeviceManagementOperationExecutor(bindings.RPC, applications.DeviceopsDeviceManagement, executor); err != nil {
		return fmt.Errorf("yunka assembly: register gRPC deviceops/device_management: %w", err)
	}
	if applications.DeviceopsDeviceTransfer == nil {
		return errors.New("yunka assembly: application deviceops/device_transfer is required for transport registration")
	}
	if err := deviceopsrest.RegisterDeviceTransferOperationExecutor(bindings.HTTP, applications.DeviceopsDeviceTransfer, executor); err != nil {
		return fmt.Errorf("yunka assembly: register HTTP deviceops/device_transfer: %w", err)
	}
	if err := deviceopsrpc.RegisterDeviceTransferOperationExecutor(bindings.RPC, applications.DeviceopsDeviceTransfer, executor); err != nil {
		return fmt.Errorf("yunka assembly: register gRPC deviceops/device_transfer: %w", err)
	}
	return nil
}

type RuntimeBindings struct {
	Factories ApplicationFactories
	Executor  operation.Executor
}

// RuntimeBinder constructs consumer-owned execution/application bindings only after kernel.New has prepared the App-owned Platform Provider.
// It does not own lifecycle, discover services, or introduce a second authorization/transaction runtime.
type RuntimeBinder func(context.Context, *platform.Provider) (RuntimeBindings, error)

type BootstrapOptions struct {
	Platform          *platform.Provider
	Factories         ApplicationFactories
	Executor          operation.Executor
	BindRuntime       RuntimeBinder
	Transports        TransportBindings
	RuntimeComponents []core.RuntimeComponent
}

func RuntimeInventory() core.RuntimeInventory {
	return core.RuntimeInventory{
		Routes:              []string{"/v1/devices", "/v1/devices/{id}", "/v1/devices/{id}/transfer"},
		RPCClientConfigured: false,
		RPCServerCount:      1,
	}
}

func Bootstrap(ctx context.Context, options BootstrapOptions) (kernel.BootstrapResult[Applications], error) {
	if options.BindRuntime != nil && (options.Factories != nil || options.Executor != nil) {
		return kernel.BootstrapResult[Applications]{}, fmt.Errorf("yunka assembly: BindRuntime cannot be combined with prebuilt Factories or Executor")
	}
	catalog, err := NewCatalog()
	if err != nil {
		return kernel.BootstrapResult[Applications]{}, fmt.Errorf("yunka assembly: build module catalog: %w", err)
	}
	kernelOptions := KernelOptions(KernelDependencies{Platform: options.Platform, Catalog: catalog})
	kernelOptions.RuntimeComponents = append([]core.RuntimeComponent(nil), options.RuntimeComponents...)
	kernelOptions.RuntimeInventory = RuntimeInventory()
	var runtime RuntimeBindings
	return kernel.Bootstrap(ctx, kernel.BootstrapOptions[Applications]{
		Kernel: kernelOptions,
		Build: func() (Applications, error) {
			if options.BindRuntime == nil {
				runtime = RuntimeBindings{Factories: options.Factories, Executor: options.Executor}
				return BuildApplications(options.Factories, options.Executor)
			}
			if options.Platform == nil {
				return Applications{}, fmt.Errorf("yunka assembly: Platform is required for BindRuntime")
			}
			runtime, err = options.BindRuntime(ctx, options.Platform)
			if err != nil {
				return Applications{}, fmt.Errorf("yunka assembly: bind runtime after Platform preparation: %w", err)
			}
			return BuildApplications(runtime.Factories, runtime.Executor)
		},
		Register: func(applications Applications) error {
			if options.BindRuntime == nil {
				return RegisterTransports(options.Transports, applications, options.Executor)
			}
			return RegisterTransports(options.Transports, applications, runtime.Executor)
		},
	})
}
