// Code generated by yunka assembly compiler; DO NOT EDIT.

package assembly

import (
	"context"
	errors "errors"
	fmt "fmt"
	accessapplication "github.com/hvritual/biz/internal/access/application"
	accessrest "github.com/hvritual/biz/internal/access/transport/rest"
	accessrpc "github.com/hvritual/biz/internal/access/transport/rpc"
	deviceopsapplication "github.com/hvritual/biz/internal/deviceops/application"
	deviceopsrest "github.com/hvritual/biz/internal/deviceops/transport/rest"
	deviceopsrpc "github.com/hvritual/biz/internal/deviceops/transport/rpc"
	grpc "google.golang.org/grpc"
	http "net/http"
	"yunka.io/framework/core"
	modulecatalog "yunka.io/framework/core/modulecatalog"
	kernel "yunka.io/framework/kernel"
	operation "yunka.io/framework/operation"
	platform "yunka.io/framework/platform"
)

const AssemblyPlanDigest = "efaabb66684cc5dd4118fce53b52608ffa6b56bda837e7fdaea096d3e490a5d3"

type AccessTenantLifecycleDependencies struct {
	AccessTenantMemberLifecycle accessapplication.TenantLifecycleToAccessTenantMemberLifecycleChildCapability
	AccessTenantRolePermission  accessapplication.TenantLifecycleToAccessTenantRolePermissionChildCapability
}

type AccessTenantMemberLifecycleDependencies struct {
	AccessTenantRolePermission accessapplication.TenantMemberLifecycleToAccessTenantRolePermissionChildCapability
}

type AccessTenantRolePermissionDependencies struct {
}

type DeviceopsDeviceManagementDependencies struct {
}

type DeviceopsDeviceTransferDependencies struct {
	DeviceopsDeviceManagement deviceopsapplication.DeviceTransferToDeviceopsDeviceManagementChildCapability
	DeviceopsSiteManagement   deviceopsapplication.DeviceTransferToDeviceopsSiteManagementChildCapability
}

type DeviceopsSiteManagementDependencies struct {
}

type ApplicationFactories interface {
	BuildAccessTenantLifecycle(AccessTenantLifecycleDependencies) (accessapplication.TenantLifecycleApplication, error)
	BuildAccessTenantMemberLifecycle(AccessTenantMemberLifecycleDependencies) (accessapplication.TenantMemberLifecycleApplication, error)
	BuildAccessTenantRolePermission(AccessTenantRolePermissionDependencies) (accessapplication.TenantRolePermissionApplication, error)
	BuildDeviceopsDeviceManagement(DeviceopsDeviceManagementDependencies) (deviceopsapplication.DeviceManagementApplication, error)
	BuildDeviceopsDeviceTransfer(DeviceopsDeviceTransferDependencies) (deviceopsapplication.DeviceTransferApplication, error)
	BuildDeviceopsSiteManagement(DeviceopsSiteManagementDependencies) (deviceopsapplication.SiteManagementApplication, error)
}

type Applications struct {
	AccessTenantLifecycle       accessapplication.TenantLifecycleApplication
	AccessTenantMemberLifecycle accessapplication.TenantMemberLifecycleApplication
	AccessTenantRolePermission  accessapplication.TenantRolePermissionApplication
	DeviceopsDeviceManagement   deviceopsapplication.DeviceManagementApplication
	DeviceopsDeviceTransfer     deviceopsapplication.DeviceTransferApplication
	DeviceopsSiteManagement     deviceopsapplication.SiteManagementApplication
}

func BuildApplications(factories ApplicationFactories, executor operation.Executor) (Applications, error) {
	if factories == nil {
		return Applications{}, errors.New("yunka assembly: application factories are required")
	}
	if executor == nil {
		return Applications{}, errors.New("yunka assembly: operation executor is required for child capabilities")
	}
	var applications Applications
	var err error
	applications.AccessTenantRolePermission, err = factories.BuildAccessTenantRolePermission(AccessTenantRolePermissionDependencies{})
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build application access/tenant_role_permission: %w", err)
	}
	if applications.AccessTenantRolePermission == nil {
		return Applications{}, errors.New("yunka assembly: application factory returned nil for access/tenant_role_permission")
	}
	accessTenantMemberLifecycleAccessTenantRolePermissionCapability, err := accessapplication.NewTenantMemberLifecycleToAccessTenantRolePermissionChildCapability(applications.AccessTenantRolePermission, executor)
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build access/tenant_member_lifecycle dependency access/tenant_role_permission: %w", err)
	}
	applications.AccessTenantMemberLifecycle, err = factories.BuildAccessTenantMemberLifecycle(AccessTenantMemberLifecycleDependencies{AccessTenantRolePermission: accessTenantMemberLifecycleAccessTenantRolePermissionCapability})
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build application access/tenant_member_lifecycle: %w", err)
	}
	if applications.AccessTenantMemberLifecycle == nil {
		return Applications{}, errors.New("yunka assembly: application factory returned nil for access/tenant_member_lifecycle")
	}
	accessTenantLifecycleAccessTenantMemberLifecycleCapability, err := accessapplication.NewTenantLifecycleToAccessTenantMemberLifecycleChildCapability(applications.AccessTenantMemberLifecycle, executor)
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build access/tenant_lifecycle dependency access/tenant_member_lifecycle: %w", err)
	}
	accessTenantLifecycleAccessTenantRolePermissionCapability, err := accessapplication.NewTenantLifecycleToAccessTenantRolePermissionChildCapability(applications.AccessTenantRolePermission, executor)
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build access/tenant_lifecycle dependency access/tenant_role_permission: %w", err)
	}
	applications.AccessTenantLifecycle, err = factories.BuildAccessTenantLifecycle(AccessTenantLifecycleDependencies{AccessTenantMemberLifecycle: accessTenantLifecycleAccessTenantMemberLifecycleCapability, AccessTenantRolePermission: accessTenantLifecycleAccessTenantRolePermissionCapability})
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build application access/tenant_lifecycle: %w", err)
	}
	if applications.AccessTenantLifecycle == nil {
		return Applications{}, errors.New("yunka assembly: application factory returned nil for access/tenant_lifecycle")
	}
	applications.DeviceopsDeviceManagement, err = factories.BuildDeviceopsDeviceManagement(DeviceopsDeviceManagementDependencies{})
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build application deviceops/device_management: %w", err)
	}
	if applications.DeviceopsDeviceManagement == nil {
		return Applications{}, errors.New("yunka assembly: application factory returned nil for deviceops/device_management")
	}
	applications.DeviceopsSiteManagement, err = factories.BuildDeviceopsSiteManagement(DeviceopsSiteManagementDependencies{})
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build application deviceops/site_management: %w", err)
	}
	if applications.DeviceopsSiteManagement == nil {
		return Applications{}, errors.New("yunka assembly: application factory returned nil for deviceops/site_management")
	}
	deviceopsDeviceTransferDeviceopsDeviceManagementCapability, err := deviceopsapplication.NewDeviceTransferToDeviceopsDeviceManagementChildCapability(applications.DeviceopsDeviceManagement, executor)
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build deviceops/device_transfer dependency deviceops/device_management: %w", err)
	}
	deviceopsDeviceTransferDeviceopsSiteManagementCapability, err := deviceopsapplication.NewDeviceTransferToDeviceopsSiteManagementChildCapability(applications.DeviceopsSiteManagement, executor)
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build deviceops/device_transfer dependency deviceops/site_management: %w", err)
	}
	applications.DeviceopsDeviceTransfer, err = factories.BuildDeviceopsDeviceTransfer(DeviceopsDeviceTransferDependencies{DeviceopsDeviceManagement: deviceopsDeviceTransferDeviceopsDeviceManagementCapability, DeviceopsSiteManagement: deviceopsDeviceTransferDeviceopsSiteManagementCapability})
	if err != nil {
		return Applications{}, fmt.Errorf("yunka assembly: build application deviceops/device_transfer: %w", err)
	}
	if applications.DeviceopsDeviceTransfer == nil {
		return Applications{}, errors.New("yunka assembly: application factory returned nil for deviceops/device_transfer")
	}
	return applications, nil
}

type KernelDependencies struct {
	Platform *platform.Provider
	Catalog  *modulecatalog.Catalog
}

func KernelOptions(dependencies KernelDependencies) kernel.Options {
	return kernel.Options{Platform: dependencies.Platform, Catalog: dependencies.Catalog}
}

func ExpectedModuleRequirements() modulecatalog.RequirementSet {
	return modulecatalog.RequirementSet{
		Modules:   []string{"access", "deviceops"},
		Configs:   []modulecatalog.ConfigRequirement{{Module: "deviceops", Key: "modules.deviceops"}},
		Logger:    true,
		Databases: []modulecatalog.DatabaseRequirement{{Name: "primary"}},
	}
}

type TransportBindings struct {
	HTTP *http.ServeMux
	RPC  grpc.ServiceRegistrar
}

func RegisterTransports(bindings TransportBindings, applications Applications, executor operation.Executor) error {
	if executor == nil {
		return errors.New("yunka assembly: operation executor is required for transport registration")
	}
	if bindings.HTTP == nil {
		return errors.New("yunka assembly: HTTP mux is required")
	}
	if bindings.RPC == nil {
		return errors.New("yunka assembly: gRPC registrar is required")
	}
	if applications.AccessTenantLifecycle == nil {
		return errors.New("yunka assembly: application access/tenant_lifecycle is required for transport registration")
	}
	if err := accessrest.RegisterTenantLifecycleOperationExecutor(bindings.HTTP, applications.AccessTenantLifecycle, executor); err != nil {
		return fmt.Errorf("yunka assembly: register HTTP access/tenant_lifecycle: %w", err)
	}
	if err := accessrpc.RegisterTenantLifecycleOperationExecutor(bindings.RPC, applications.AccessTenantLifecycle, executor); err != nil {
		return fmt.Errorf("yunka assembly: register gRPC access/tenant_lifecycle: %w", err)
	}
	if applications.AccessTenantMemberLifecycle == nil {
		return errors.New("yunka assembly: application access/tenant_member_lifecycle is required for transport registration")
	}
	if err := accessrest.RegisterTenantMemberLifecycleOperationExecutor(bindings.HTTP, applications.AccessTenantMemberLifecycle, executor); err != nil {
		return fmt.Errorf("yunka assembly: register HTTP access/tenant_member_lifecycle: %w", err)
	}
	if err := accessrpc.RegisterTenantMemberLifecycleOperationExecutor(bindings.RPC, applications.AccessTenantMemberLifecycle, executor); err != nil {
		return fmt.Errorf("yunka assembly: register gRPC access/tenant_member_lifecycle: %w", err)
	}
	if applications.AccessTenantRolePermission == nil {
		return errors.New("yunka assembly: application access/tenant_role_permission is required for transport registration")
	}
	if err := accessrest.RegisterTenantRolePermissionOperationExecutor(bindings.HTTP, applications.AccessTenantRolePermission, executor); err != nil {
		return fmt.Errorf("yunka assembly: register HTTP access/tenant_role_permission: %w", err)
	}
	if err := accessrpc.RegisterTenantRolePermissionOperationExecutor(bindings.RPC, applications.AccessTenantRolePermission, executor); err != nil {
		return fmt.Errorf("yunka assembly: register gRPC access/tenant_role_permission: %w", err)
	}
	if applications.DeviceopsDeviceManagement == nil {
		return errors.New("yunka assembly: application deviceops/device_management is required for transport registration")
	}
	if err := deviceopsrest.RegisterDeviceManagementOperationExecutor(bindings.HTTP, applications.DeviceopsDeviceManagement, executor); err != nil {
		return fmt.Errorf("yunka assembly: register HTTP deviceops/device_management: %w", err)
	}
	if err := deviceopsrpc.RegisterDeviceManagementOperationExecutor(bindings.RPC, applications.DeviceopsDeviceManagement, executor); err != nil {
		return fmt.Errorf("yunka assembly: register gRPC deviceops/device_management: %w", err)
	}
	if applications.DeviceopsDeviceTransfer == nil {
		return errors.New("yunka assembly: application deviceops/device_transfer is required for transport registration")
	}
	if err := deviceopsrest.RegisterDeviceTransferOperationExecutor(bindings.HTTP, applications.DeviceopsDeviceTransfer, executor); err != nil {
		return fmt.Errorf("yunka assembly: register HTTP deviceops/device_transfer: %w", err)
	}
	if err := deviceopsrpc.RegisterDeviceTransferOperationExecutor(bindings.RPC, applications.DeviceopsDeviceTransfer, executor); err != nil {
		return fmt.Errorf("yunka assembly: register gRPC deviceops/device_transfer: %w", err)
	}
	return nil
}

type RuntimeBindings struct {
	Factories ApplicationFactories
	Executor  operation.Executor
}

// RuntimeBinder constructs consumer-owned execution/application bindings only after kernel.New has prepared the App-owned Platform Provider.
// It does not own lifecycle, discover services, or introduce a second authorization/transaction runtime.
type RuntimeBinder func(context.Context, *platform.Provider) (RuntimeBindings, error)

type BootstrapOptions struct {
	Platform          *platform.Provider
	Factories         ApplicationFactories
	Executor          operation.Executor
	BindRuntime       RuntimeBinder
	Transports        TransportBindings
	RuntimeComponents []core.RuntimeComponent
}

func RuntimeInventory() core.RuntimeInventory {
	return core.RuntimeInventory{
		Routes:              []string{"/v1/devices", "/v1/devices/{id}", "/v1/devices/{id}/transfer", "/v1/tenant/members", "/v1/tenant/members/{user_id}", "/v1/tenant/members/{user_id}/activate", "/v1/tenant/members/{user_id}/remove", "/v1/tenant/members/{user_id}/suspend", "/v1/tenant/roles", "/v1/tenant/roles/{role_id}", "/v1/tenant/roles/{role_id}/disable", "/v1/tenant/roles/{role_id}/enable", "/v1/tenant/roles/{role_id}/members", "/v1/tenant/roles/{role_id}/members/{user_id}/revoke", "/v1/tenant/roles/{role_id}/permissions", "/v1/tenants", "/v1/tenants/{id}", "/v1/tenants/{id}/activate", "/v1/tenants/{id}/close", "/v1/tenants/{id}/suspend"},
		RPCClientConfigured: false,
		RPCServerCount:      1,
	}
}

func Bootstrap(ctx context.Context, options BootstrapOptions) (kernel.BootstrapResult[Applications], error) {
	if options.BindRuntime != nil && (options.Factories != nil || options.Executor != nil) {
		return kernel.BootstrapResult[Applications]{}, fmt.Errorf("yunka assembly: BindRuntime cannot be combined with prebuilt Factories or Executor")
	}
	catalog, err := NewCatalog()
	if err != nil {
		return kernel.BootstrapResult[Applications]{}, fmt.Errorf("yunka assembly: build module catalog: %w", err)
	}
	kernelOptions := KernelOptions(KernelDependencies{Platform: options.Platform, Catalog: catalog})
	kernelOptions.RuntimeComponents = append([]core.RuntimeComponent(nil), options.RuntimeComponents...)
	kernelOptions.RuntimeInventory = RuntimeInventory()
	var runtime RuntimeBindings
	return kernel.Bootstrap(ctx, kernel.BootstrapOptions[Applications]{
		Kernel: kernelOptions,
		Build: func() (Applications, error) {
			if options.BindRuntime == nil {
				runtime = RuntimeBindings{Factories: options.Factories, Executor: options.Executor}
				return BuildApplications(options.Factories, options.Executor)
			}
			if options.Platform == nil {
				return Applications{}, fmt.Errorf("yunka assembly: Platform is required for BindRuntime")
			}
			runtime, err = options.BindRuntime(ctx, options.Platform)
			if err != nil {
				return Applications{}, fmt.Errorf("yunka assembly: bind runtime after Platform preparation: %w", err)
			}
			return BuildApplications(runtime.Factories, runtime.Executor)
		},
		Register: func(applications Applications) error {
			if options.BindRuntime == nil {
				return RegisterTransports(options.Transports, applications, options.Executor)
			}
			return RegisterTransports(options.Transports, applications, runtime.Executor)
		},
	})
}
