// Code generated by yunka assembly compiler; DO NOT EDIT.

package assembly

import (
	fmt "fmt"
	deviceopsmodule "github.com/hvritual/biz/modules/deviceops"
	modulecatalog "yunka.io/framework/core/modulecatalog"
)

func NewCatalog() (*modulecatalog.Catalog, error) {
	catalog := modulecatalog.New()
	if err := catalog.Register(deviceopsmodule.GeneratedDescriptor()); err != nil {
		return nil, fmt.Errorf("yunka assembly: register module deviceops: %w", err)
	}
	if _, err := catalog.Seal(); err != nil {
		return nil, fmt.Errorf("yunka assembly: seal module catalog: %w", err)
	}
	return catalog, nil
}
