// Code generated from contracts/generated/operation-plans.json and contracts/commercial/operation-capabilities.v1.json; DO NOT EDIT.

package authorization

import "yunka.io/gateway/authz"

const CommercialCapabilityMappingVersion = "23"

var generatedActions = []Action{
	{
		Code: "access.audit.export", Domain: "access", Application: "tenant_audit_management", UseCase: "export_tenant_audit_records",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.audit.export")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.lifecycle"},
		RPC: "/access.v1.TenantAuditManagementApplication/ExportTenantAuditRecords", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/audit-logs/exports"}},
	},
	{
		Code: "access.audit.get", Domain: "access", Application: "tenant_audit_management", UseCase: "get_tenant_audit_record",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.audit.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.lifecycle"},
		RPC: "/access.v1.TenantAuditManagementApplication/GetTenantAuditRecord", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/audit-logs/{audit_id}"}},
	},
	{
		Code: "access.audit.list", Domain: "access", Application: "tenant_audit_management", UseCase: "list_tenant_audit_records",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.audit.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.lifecycle"},
		RPC: "/access.v1.TenantAuditManagementApplication/ListTenantAuditRecords", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/audit-logs"}},
	},
	{
		Code: "commercial.entitlement.explain", Domain: "commercial", Application: "entitlement_management", UseCase: "explain_entitlements",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("platform.entitlement.read"), authz.PermissionKey("platform.tenant.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.EntitlementManagementApplication/ExplainEntitlements", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/platform/tenants/{tenant_id}/entitlements"}},
	},
	{
		Code: "commercial.entitlement.get_my", Domain: "commercial", Application: "entitlement_management", UseCase: "get_my_entitlements",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("tenant.entitlement.read")}, PermissionMode: "all",
		Classification: "recovery", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.EntitlementManagementApplication/GetMyEntitlements", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/entitlements"}},
	},
	{
		Code: "commercial.entitlement.override.create", Domain: "commercial", Application: "entitlement_management", UseCase: "create_entitlement_override",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("platform.entitlement.manage"), authz.PermissionKey("platform.tenant.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.EntitlementManagementApplication/CreateEntitlementOverride", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/platform/tenants/{tenant_id}/entitlement-overrides"}},
	},
	{
		Code: "commercial.entitlement.override.list", Domain: "commercial", Application: "entitlement_management", UseCase: "list_entitlement_overrides",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.entitlement.read"), authz.PermissionKey("platform.tenant.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.EntitlementManagementApplication/ListEntitlementOverrides", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/platform/tenants/{tenant_id}/entitlement-overrides"}},
	},
	{
		Code: "commercial.entitlement.override.revoke", Domain: "commercial", Application: "entitlement_management", UseCase: "revoke_entitlement_override",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.entitlement.manage"), authz.PermissionKey("platform.tenant.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.EntitlementManagementApplication/RevokeEntitlementOverride", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/platform/tenants/{tenant_id}/entitlement-overrides/{id}/revoke"}},
	},
	{
		Code: "commercial.module.create", Domain: "commercial", Application: "module_catalog", UseCase: "create_module",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.module.manage")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.ModuleCatalogApplication/CreateModule", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/platform/modules"}},
	},
	{
		Code: "commercial.module.delete", Domain: "commercial", Application: "module_catalog", UseCase: "delete_module",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.module.manage")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.ModuleCatalogApplication/DeleteModule", HTTP: []HTTPBinding{{Method: "DELETE", Path: "/v1/platform/modules/{module_code}"}},
	},
	{
		Code: "commercial.module.entitlement_catalog", Domain: "commercial", Application: "module_catalog", UseCase: "read_entitlement_catalog",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read")}, PermissionMode: "all",
		Classification: "foundation_exempt", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "commercial.module.get", Domain: "commercial", Application: "module_catalog", UseCase: "get_module",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.module.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.ModuleCatalogApplication/GetModule", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/platform/modules/{module_code}"}},
	},
	{
		Code: "commercial.module.list", Domain: "commercial", Application: "module_catalog", UseCase: "list_modules",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.module.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.ModuleCatalogApplication/ListModules", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/platform/modules"}},
	},
	{
		Code: "commercial.module.plan_catalog", Domain: "commercial", Application: "module_catalog", UseCase: "read_plan_catalog",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read")}, PermissionMode: "all",
		Classification: "foundation_exempt", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "commercial.module.set_sales_status", Domain: "commercial", Application: "module_catalog", UseCase: "set_module_sales_status",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.module.manage")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.ModuleCatalogApplication/SetModuleSalesStatus", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/platform/modules/{module_code}/sales-status"}},
	},
	{
		Code: "commercial.module.set_technical_status", Domain: "commercial", Application: "module_catalog", UseCase: "set_module_technical_status",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.module.technical.manage")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.ModuleCatalogApplication/SetModuleTechnicalStatus", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/platform/modules/{module_code}/technical-status"}},
	},
	{
		Code: "commercial.module.update", Domain: "commercial", Application: "module_catalog", UseCase: "update_module",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.module.manage")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.ModuleCatalogApplication/UpdateModule", HTTP: []HTTPBinding{{Method: "PATCH", Path: "/v1/platform/modules/{module_code}"}},
	},
	{
		Code: "commercial.plan.change_target.list", Domain: "commercial", Application: "plan_management", UseCase: "list_tenant_change_targets",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("tenant.subscription.manage")}, PermissionMode: "all",
		Classification: "foundation_exempt", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "commercial.plan.change_target.resolve", Domain: "commercial", Application: "plan_management", UseCase: "resolve_tenant_change_target",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("tenant.subscription.manage")}, PermissionMode: "all",
		Classification: "foundation_exempt", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "commercial.plan.clone", Domain: "commercial", Application: "plan_management", UseCase: "create_plan_version",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("platform.plan.manage")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.PlanManagementApplication/CreatePlanVersion", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/platform/plans/{plan_code}/versions"}},
	},
	{
		Code: "commercial.plan.create", Domain: "commercial", Application: "plan_management", UseCase: "create_plan_draft",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("platform.plan.manage")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.PlanManagementApplication/CreatePlanDraft", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/platform/plans"}},
	},
	{
		Code: "commercial.plan.discover", Domain: "commercial", Application: "plan_management", UseCase: "list_plans",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.plan.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.PlanManagementApplication/ListPlans", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/platform/plans"}},
	},
	{
		Code: "commercial.plan.eligibility", Domain: "commercial", Application: "plan_management", UseCase: "check_plan_eligibility",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("platform.plan.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.PlanManagementApplication/CheckPlanEligibility", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/platform/plans/{plan_code}/versions/{version}/eligibility"}},
	},
	{
		Code: "commercial.plan.get", Domain: "commercial", Application: "plan_management", UseCase: "get_plan_version",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.plan.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.PlanManagementApplication/GetPlanVersion", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/platform/plans/{plan_code}/versions/{version}"}},
	},
	{
		Code: "commercial.plan.list", Domain: "commercial", Application: "plan_management", UseCase: "list_plan_versions",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.plan.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.PlanManagementApplication/ListPlanVersions", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/platform/plans/{plan_code}/versions"}},
	},
	{
		Code: "commercial.plan.publish", Domain: "commercial", Application: "plan_management", UseCase: "publish_plan_version",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("platform.plan.publish")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.PlanManagementApplication/PublishPlanVersion", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/platform/plans/{plan_code}/versions/{version}/publish"}},
	},
	{
		Code: "commercial.plan.retire", Domain: "commercial", Application: "plan_management", UseCase: "retire_plan_version",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("platform.plan.publish")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.PlanManagementApplication/RetirePlanVersion", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/platform/plans/{plan_code}/versions/{version}/retire"}},
	},
	{
		Code: "commercial.plan.subscription_snapshot", Domain: "commercial", Application: "plan_management", UseCase: "read_tenant_subscription_plan_version",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.subscription.manage")}, PermissionMode: "all",
		Classification: "foundation_exempt", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "commercial.plan.update", Domain: "commercial", Application: "plan_management", UseCase: "update_plan_draft",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("platform.plan.manage")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.PlanManagementApplication/UpdatePlanDraft", HTTP: []HTTPBinding{{Method: "PATCH", Path: "/v1/platform/plans/{plan_code}/versions/{version}"}},
	},
	{
		Code: "commercial.provisioning.delivery.claim", Domain: "commercial", Application: "provisioning", UseCase: "claim_provisioning_delivery",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.provisioning.execute")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "commercial.provisioning.delivery.complete", Domain: "commercial", Application: "provisioning", UseCase: "complete_provisioning_delivery",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.provisioning.execute")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "commercial.provisioning.delivery.fail", Domain: "commercial", Application: "provisioning", UseCase: "fail_provisioning_delivery",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.provisioning.execute")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "commercial.provisioning.delivery.list", Domain: "commercial", Application: "provisioning", UseCase: "list_provisioning_deliveries",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.provisioning.read"), authz.PermissionKey("platform.tenant.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.ProvisioningApplication/ListProvisioningDeliveries", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/platform/tenants/{tenant_id}/provisioning/deliveries"}},
	},
	{
		Code: "commercial.provisioning.task.cancel", Domain: "commercial", Application: "provisioning", UseCase: "cancel_provisioning_task",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("platform.plan.read"), authz.PermissionKey("platform.provisioning.cancel"), authz.PermissionKey("platform.tenant.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.ProvisioningApplication/CancelProvisioningTask", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/platform/tenants/{tenant_id}/provisioning/tasks/{task_id}/cancel"}},
	},
	{
		Code: "commercial.provisioning.task.get", Domain: "commercial", Application: "provisioning", UseCase: "get_provisioning_task",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.provisioning.read"), authz.PermissionKey("platform.tenant.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.ProvisioningApplication/GetProvisioningTask", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/platform/tenants/{tenant_id}/provisioning/tasks/{task_id}"}},
	},
	{
		Code: "commercial.provisioning.task.list", Domain: "commercial", Application: "provisioning", UseCase: "list_provisioning_tasks",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.provisioning.read"), authz.PermissionKey("platform.tenant.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.ProvisioningApplication/ListProvisioningTasks", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/platform/tenants/{tenant_id}/provisioning/tasks"}},
	},
	{
		Code: "commercial.provisioning.task.retry", Domain: "commercial", Application: "provisioning", UseCase: "retry_provisioning_task",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.provisioning.manage"), authz.PermissionKey("platform.tenant.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.ProvisioningApplication/RetryProvisioningTask", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/platform/tenants/{tenant_id}/provisioning/tasks/{task_id}/retry"}},
	},
	{
		Code: "commercial.provisioning.work.claim", Domain: "commercial", Application: "provisioning", UseCase: "claim_provisioning_work",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.provisioning.execute")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "commercial.provisioning.work.finalize", Domain: "commercial", Application: "provisioning", UseCase: "finalize_provisioning_work",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("platform.plan.read"), authz.PermissionKey("platform.provisioning.execute")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "commercial.provisioning.work.record", Domain: "commercial", Application: "provisioning", UseCase: "record_provisioning_work",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.provisioning.execute")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "commercial.subscription.bootstrap_base", Domain: "commercial", Application: "subscription_management", UseCase: "bootstrap_base_subscription",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("platform.plan.read"), authz.PermissionKey("platform.tenant.create")}, PermissionMode: "all",
		Classification: "foundation_exempt", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "commercial.subscription.change.confirm", Domain: "commercial", Application: "subscription_changes", UseCase: "confirm_subscription_change",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("platform.plan.read"), authz.PermissionKey("platform.subscription.confirm"), authz.PermissionKey("platform.tenant.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.SubscriptionChangesApplication/ConfirmSubscriptionChange", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/platform/tenants/{tenant_id}/subscription/changes/{change_id}/confirm"}},
	},
	{
		Code: "commercial.subscription.change.confirm_my", Domain: "commercial", Application: "subscription_changes", UseCase: "confirm_my_subscription_change",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("tenant.subscription.manage")}, PermissionMode: "all",
		Classification: "recovery", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.SubscriptionChangesApplication/ConfirmMySubscriptionChange", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/subscription/changes/{change_id}/confirm"}},
	},
	{
		Code: "commercial.subscription.change.get", Domain: "commercial", Application: "subscription_changes", UseCase: "get_subscription_change_receipt",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.subscription.read"), authz.PermissionKey("platform.tenant.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.SubscriptionChangesApplication/GetSubscriptionChangeReceipt", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/platform/tenants/{tenant_id}/subscription/changes/{change_id}"}},
	},
	{
		Code: "commercial.subscription.change.get_my", Domain: "commercial", Application: "subscription_changes", UseCase: "get_my_subscription_change_receipt",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.subscription.manage")}, PermissionMode: "all",
		Classification: "recovery", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.SubscriptionChangesApplication/GetMySubscriptionChangeReceipt", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/subscription/changes/{change_id}"}},
	},
	{
		Code: "commercial.subscription.change.preparation.cancel", Domain: "commercial", Application: "subscription_changes", UseCase: "cancel_prepared_subscription_change",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("platform.plan.read"), authz.PermissionKey("platform.provisioning.cancel")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "commercial.subscription.change.prepared", Domain: "commercial", Application: "subscription_changes", UseCase: "complete_prepared_subscription_change",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("platform.plan.read"), authz.PermissionKey("platform.provisioning.execute")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "commercial.subscription.change.preview", Domain: "commercial", Application: "subscription_changes", UseCase: "preview_subscription_change",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("platform.plan.read"), authz.PermissionKey("platform.subscription.manage"), authz.PermissionKey("platform.tenant.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.SubscriptionChangesApplication/PreviewSubscriptionChange", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/platform/tenants/{tenant_id}/subscription/change-previews"}},
	},
	{
		Code: "commercial.subscription.change.preview.get", Domain: "commercial", Application: "subscription_changes", UseCase: "get_subscription_change_preview",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.subscription.read"), authz.PermissionKey("platform.tenant.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.SubscriptionChangesApplication/GetSubscriptionChangePreview", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/platform/tenants/{tenant_id}/subscription/change-previews/{change_id}"}},
	},
	{
		Code: "commercial.subscription.change.preview_my", Domain: "commercial", Application: "subscription_changes", UseCase: "preview_my_subscription_change",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("tenant.subscription.manage")}, PermissionMode: "all",
		Classification: "recovery", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.SubscriptionChangesApplication/PreviewMySubscriptionChange", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/subscription/change-previews"}},
	},
	{
		Code: "commercial.subscription.change.preview_my.get", Domain: "commercial", Application: "subscription_changes", UseCase: "get_my_subscription_change_preview",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.subscription.manage")}, PermissionMode: "all",
		Classification: "recovery", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.SubscriptionChangesApplication/GetMySubscriptionChangePreview", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/subscription/change-previews/{change_id}"}},
	},
	{
		Code: "commercial.subscription.change.targets_my", Domain: "commercial", Application: "subscription_changes", UseCase: "list_my_subscription_change_targets",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("tenant.subscription.manage")}, PermissionMode: "all",
		Classification: "recovery", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.SubscriptionChangesApplication/ListMySubscriptionChangeTargets", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/subscription/change-targets"}},
	},
	{
		Code: "commercial.subscription.get", Domain: "commercial", Application: "subscription_management", UseCase: "get_tenant_subscription",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.subscription.read"), authz.PermissionKey("platform.tenant.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.SubscriptionManagementApplication/GetTenantSubscription", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/platform/tenants/{tenant_id}/subscription"}},
	},
	{
		Code: "commercial.subscription.get_my", Domain: "commercial", Application: "subscription_management", UseCase: "get_my_subscription",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.entitlement.read")}, PermissionMode: "all",
		Classification: "recovery", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.SubscriptionManagementApplication/GetMySubscription", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/subscription"}},
	},
	{
		Code: "commercial.subscription.get_my_usage", Domain: "commercial", Application: "subscription_management", UseCase: "get_my_tenant_usage",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.entitlement.read")}, PermissionMode: "all",
		Classification: "recovery", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.SubscriptionManagementApplication/GetMyTenantUsage", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/usage"}},
	},
	{
		Code: "commercial.subscription.rule.list", Domain: "commercial", Application: "subscription_management", UseCase: "list_default_subscription_rules",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.subscription.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.SubscriptionManagementApplication/ListDefaultSubscriptionRules", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/platform/subscription-default-rules"}},
	},
	{
		Code: "commercial.subscription.rule.put", Domain: "commercial", Application: "subscription_management", UseCase: "put_default_subscription_rule",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("platform.plan.read"), authz.PermissionKey("platform.subscription.manage")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "/commercial.v1.SubscriptionManagementApplication/PutDefaultSubscriptionRule", HTTP: []HTTPBinding{{Method: "PUT", Path: "/v1/platform/subscription-default-rules/{rule_id}"}},
	},
	{
		Code: "commercial.subscription.transition.claim", Domain: "commercial", Application: "subscription_changes", UseCase: "claim_commercial_time_transition",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.provisioning.execute")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "commercial.subscription.transition.complete", Domain: "commercial", Application: "subscription_changes", UseCase: "complete_commercial_time_transition",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("platform.plan.read"), authz.PermissionKey("platform.provisioning.execute")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "device.assert_owned_by_actor_tenant", Domain: "deviceops", Application: "device_management", UseCase: "assert_device_owned_by_actor_tenant",
		TenantRequired: true, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.delegation.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "device-operations", CapabilityCodes: []string{"device.lifecycle"},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "device.create", Domain: "deviceops", Application: "device_management", UseCase: "create_device",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("device.create")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "device-operations", CapabilityCodes: []string{"device.lifecycle"},
		RPC: "/deviceops.v1.DeviceApplication/CreateDevice", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/devices"}},
	},
	{
		Code: "device.delegated_get", Domain: "deviceops", Application: "delegated_device_access", UseCase: "get_delegated_device",
		TenantRequired: true, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("device.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "device-operations", CapabilityCodes: []string{"device.lifecycle"},
		RPC: "/deviceops.v1.DelegatedDeviceAccessApplication/GetDelegatedDevice", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/delegated/devices/{id}"}},
	},
	{
		Code: "device.delegated_update", Domain: "deviceops", Application: "delegated_device_access", UseCase: "update_delegated_device",
		TenantRequired: true, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("device.update")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "device-operations", CapabilityCodes: []string{"device.lifecycle"},
		RPC: "/deviceops.v1.DelegatedDeviceAccessApplication/UpdateDelegatedDevice", HTTP: []HTTPBinding{{Method: "PATCH", Path: "/v1/delegated/devices/{id}"}},
	},
	{
		Code: "device.delete", Domain: "deviceops", Application: "device_management", UseCase: "delete_device",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("device.delete")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "device-operations", CapabilityCodes: []string{"device.lifecycle"},
		RPC: "/deviceops.v1.DeviceApplication/DeleteDevice", HTTP: []HTTPBinding{{Method: "DELETE", Path: "/v1/devices/{id}"}},
	},
	{
		Code: "device.get", Domain: "deviceops", Application: "device_management", UseCase: "get_device",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("device.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "device-operations", CapabilityCodes: []string{"device.lifecycle"},
		RPC: "/deviceops.v1.DeviceApplication/GetDevice", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/devices/{id}"}},
	},
	{
		Code: "device.list", Domain: "deviceops", Application: "device_management", UseCase: "list_devices",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("device.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "device-operations", CapabilityCodes: []string{"device.lifecycle"},
		RPC: "/deviceops.v1.DeviceApplication/ListDevices", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/devices"}},
	},
	{
		Code: "device.transfer", Domain: "deviceops", Application: "device_transfer", UseCase: "transfer_device",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("device.update"), authz.PermissionKey("site.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "device-operations", CapabilityCodes: []string{"device.transfer"},
		RPC: "/deviceops.v1.DeviceTransferApplication/TransferDevice", HTTP: []HTTPBinding{{Method: "PATCH", Path: "/v1/devices/{id}/transfer"}},
	},
	{
		Code: "device.update", Domain: "deviceops", Application: "device_management", UseCase: "update_device",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("device.update"), authz.PermissionKey("site.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "device-operations", CapabilityCodes: []string{"device.lifecycle"},
		RPC: "/deviceops.v1.DeviceApplication/UpdateDevice", HTTP: []HTTPBinding{{Method: "PATCH", Path: "/v1/devices/{id}"}},
	},
	{
		Code: "site.role_scope_directory", Domain: "deviceops", Application: "site_management", UseCase: "list_assignable_role_sites",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.role.manage")}, PermissionMode: "all",
		Classification: "foundation_exempt", ModuleCode: "", CapabilityCodes: []string{},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "site.validate_transfer_target", Domain: "deviceops", Application: "site_management", UseCase: "validate_transfer_target",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("site.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "device-operations", CapabilityCodes: []string{"device.transfer"},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "tenant.activate", Domain: "access", Application: "tenant_lifecycle", UseCase: "activate_tenant",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.tenant.manage")}, PermissionMode: "all",
		Classification: "recovery", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.lifecycle"},
		RPC: "/access.v1.TenantLifecycleApplication/ActivateTenant", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenants/{id}/activate"}},
	},
	{
		Code: "tenant.assert_active", Domain: "access", Application: "tenant_lifecycle", UseCase: "assert_tenant_active",
		TenantRequired: true, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.delegation.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "device-operations", CapabilityCodes: []string{"device.lifecycle"},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "tenant.branding.get", Domain: "access", Application: "tenant_profile_management", UseCase: "get_tenant_branding",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.branding.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.lifecycle"},
		RPC: "/access.v1.TenantProfileManagementApplication/GetTenantBranding", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/branding"}},
	},
	{
		Code: "tenant.branding.update", Domain: "access", Application: "tenant_profile_management", UseCase: "update_tenant_branding",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.organization.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.lifecycle"},
		RPC: "/access.v1.TenantProfileManagementApplication/UpdateTenantBranding", HTTP: []HTTPBinding{{Method: "PATCH", Path: "/v1/tenant/branding"}},
	},
	{
		Code: "tenant.close", Domain: "access", Application: "tenant_lifecycle", UseCase: "close_tenant",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.tenant.manage")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.lifecycle"},
		RPC: "/access.v1.TenantLifecycleApplication/CloseTenant", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenants/{id}/close"}},
	},
	{
		Code: "tenant.create", Domain: "access", Application: "tenant_lifecycle", UseCase: "create_tenant",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("commercial.catalog.read"), authz.PermissionKey("platform.plan.read"), authz.PermissionKey("platform.tenant.create")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.lifecycle"},
		RPC: "/access.v1.TenantLifecycleApplication/CreateTenant", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenants"}},
	},
	{
		Code: "tenant.data_policy.create", Domain: "access", Application: "tenant_role_permission", UseCase: "create_tenant_data_policy",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.role.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.role.permission"},
		RPC: "/access.v1.TenantRolePermissionApplication/CreateTenantDataPolicy", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/data-policies"}},
	},
	{
		Code: "tenant.data_policy.get", Domain: "access", Application: "tenant_role_permission", UseCase: "get_tenant_data_policy",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.role.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.role.permission"},
		RPC: "/access.v1.TenantRolePermissionApplication/GetTenantDataPolicy", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/data-policies/{policy_id}"}},
	},
	{
		Code: "tenant.data_policy.list", Domain: "access", Application: "tenant_role_permission", UseCase: "list_tenant_data_policies",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.role.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.role.permission"},
		RPC: "/access.v1.TenantRolePermissionApplication/ListTenantDataPolicies", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/data-policies"}},
	},
	{
		Code: "tenant.data_policy.revoke", Domain: "access", Application: "tenant_role_permission", UseCase: "revoke_tenant_data_policy",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.role.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.role.permission"},
		RPC: "/access.v1.TenantRolePermissionApplication/RevokeTenantDataPolicy", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/data-policies/{policy_id}/revoke"}},
	},
	{
		Code: "tenant.data_policy.update", Domain: "access", Application: "tenant_role_permission", UseCase: "update_tenant_data_policy",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.role.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.role.permission"},
		RPC: "/access.v1.TenantRolePermissionApplication/UpdateTenantDataPolicy", HTTP: []HTTPBinding{{Method: "PATCH", Path: "/v1/tenant/data-policies/{policy_id}"}},
	},
	{
		Code: "tenant.delegation.get", Domain: "access", Application: "tenant_delegation_management", UseCase: "get_tenant_delegation",
		TenantRequired: true, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.delegation.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "device-operations", CapabilityCodes: []string{"device.lifecycle"},
		RPC: "/access.v1.TenantDelegationApplication/GetTenantDelegation", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/delegations/{id}"}},
	},
	{
		Code: "tenant.delegation.grant_device", Domain: "access", Application: "tenant_delegation_management", UseCase: "grant_tenant_device_delegation",
		TenantRequired: true, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.delegation.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "device-operations", CapabilityCodes: []string{"device.lifecycle"},
		RPC: "/access.v1.TenantDelegationApplication/GrantTenantDeviceDelegation", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/delegations/devices"}},
	},
	{
		Code: "tenant.delegation.list", Domain: "access", Application: "tenant_delegation_management", UseCase: "list_tenant_delegations",
		TenantRequired: true, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.delegation.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "device-operations", CapabilityCodes: []string{"device.lifecycle"},
		RPC: "/access.v1.TenantDelegationApplication/ListTenantDelegations", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/delegations"}},
	},
	{
		Code: "tenant.delegation.revoke", Domain: "access", Application: "tenant_delegation_management", UseCase: "revoke_tenant_delegation",
		TenantRequired: true, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.delegation.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "device-operations", CapabilityCodes: []string{"device.lifecycle"},
		RPC: "/access.v1.TenantDelegationApplication/RevokeTenantDelegation", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/delegations/{id}:revoke"}},
	},
	{
		Code: "tenant.department.assert_member_assignment_allowed", Domain: "access", Application: "tenant_department_management", UseCase: "assert_tenant_member_department_assignment_allowed",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.member.manage")}, PermissionMode: "all",
		Classification: "foundation_exempt", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "tenant.department.create", Domain: "access", Application: "tenant_department_management", UseCase: "create_tenant_department",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.organization.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "/access.v1.TenantDepartmentManagementApplication/CreateTenantDepartment", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/departments"}},
	},
	{
		Code: "tenant.department.disable", Domain: "access", Application: "tenant_department_management", UseCase: "disable_tenant_department",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.organization.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "/access.v1.TenantDepartmentManagementApplication/DisableTenantDepartment", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/departments/{department_id}/disable"}},
	},
	{
		Code: "tenant.department.enable", Domain: "access", Application: "tenant_department_management", UseCase: "enable_tenant_department",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.organization.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "/access.v1.TenantDepartmentManagementApplication/EnableTenantDepartment", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/departments/{department_id}/enable"}},
	},
	{
		Code: "tenant.department.get", Domain: "access", Application: "tenant_department_management", UseCase: "get_tenant_department",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.organization.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "/access.v1.TenantDepartmentManagementApplication/GetTenantDepartment", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/departments/{department_id}"}},
	},
	{
		Code: "tenant.department.list", Domain: "access", Application: "tenant_department_management", UseCase: "list_tenant_departments",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.organization.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "/access.v1.TenantDepartmentManagementApplication/ListTenantDepartments", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/departments"}},
	},
	{
		Code: "tenant.department.update", Domain: "access", Application: "tenant_department_management", UseCase: "update_tenant_department",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.organization.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "/access.v1.TenantDepartmentManagementApplication/UpdateTenantDepartment", HTTP: []HTTPBinding{{Method: "PATCH", Path: "/v1/tenant/departments/{department_id}"}},
	},
	{
		Code: "tenant.get", Domain: "access", Application: "tenant_lifecycle", UseCase: "get_tenant",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.tenant.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.lifecycle"},
		RPC: "/access.v1.TenantLifecycleApplication/GetTenant", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenants/{id}"}},
	},
	{
		Code: "tenant.list", Domain: "access", Application: "tenant_lifecycle", UseCase: "list_tenants",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.tenant.read")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.lifecycle"},
		RPC: "/access.v1.TenantLifecycleApplication/ListTenants", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenants"}},
	},
	{
		Code: "tenant.member.activate", Domain: "access", Application: "tenant_member_lifecycle", UseCase: "activate_tenant_member",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.member.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "/access.v1.TenantMemberLifecycleApplication/ActivateTenantMember", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/members/{user_id}/activate"}},
	},
	{
		Code: "tenant.member.bootstrap_owner", Domain: "access", Application: "tenant_member_lifecycle", UseCase: "bootstrap_tenant_owner_member",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.tenant.create")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "tenant.member.count_quota_usage", Domain: "access", Application: "tenant_member_lifecycle", UseCase: "count_tenant_quota_usage",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.entitlement.read")}, PermissionMode: "all",
		Classification: "foundation_exempt", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "tenant.member.create", Domain: "access", Application: "tenant_member_lifecycle", UseCase: "create_tenant_member",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.member.manage"), authz.PermissionKey("tenant.role.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "/access.v1.TenantMemberLifecycleApplication/CreateTenantMember", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/members/create"}},
	},
	{
		Code: "tenant.member.get", Domain: "access", Application: "tenant_member_lifecycle", UseCase: "get_tenant_member",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.member.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "/access.v1.TenantMemberLifecycleApplication/GetTenantMember", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/members/{user_id}"}},
	},
	{
		Code: "tenant.member.invite", Domain: "access", Application: "tenant_member_lifecycle", UseCase: "invite_tenant_member",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.member.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "/access.v1.TenantMemberLifecycleApplication/InviteTenantMember", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/members"}},
	},
	{
		Code: "tenant.member.list", Domain: "access", Application: "tenant_member_lifecycle", UseCase: "list_tenant_members",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.member.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "/access.v1.TenantMemberLifecycleApplication/ListTenantMembers", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/members"}},
	},
	{
		Code: "tenant.member.list_removed", Domain: "access", Application: "tenant_member_lifecycle", UseCase: "list_removed_tenant_members",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.member.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "/access.v1.TenantMemberLifecycleApplication/ListRemovedTenantMembers", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/members/removed"}},
	},
	{
		Code: "tenant.member.profile.update", Domain: "access", Application: "tenant_member_lifecycle", UseCase: "update_tenant_member_profile",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.member.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "/access.v1.TenantMemberLifecycleApplication/UpdateTenantMemberProfile", HTTP: []HTTPBinding{{Method: "PATCH", Path: "/v1/tenant/members/{user_id}/profile"}},
	},
	{
		Code: "tenant.member.remove", Domain: "access", Application: "tenant_member_lifecycle", UseCase: "remove_tenant_member",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.member.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "/access.v1.TenantMemberLifecycleApplication/RemoveTenantMember", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/members/{user_id}/remove"}},
	},
	{
		Code: "tenant.member.restore", Domain: "access", Application: "tenant_member_lifecycle", UseCase: "restore_tenant_member",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.member.manage"), authz.PermissionKey("tenant.role.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "/access.v1.TenantMemberLifecycleApplication/RestoreTenantMember", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/members/{user_id}/restore"}},
	},
	{
		Code: "tenant.member.suspend", Domain: "access", Application: "tenant_member_lifecycle", UseCase: "suspend_tenant_member",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.member.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "/access.v1.TenantMemberLifecycleApplication/SuspendTenantMember", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/members/{user_id}/suspend"}},
	},
	{
		Code: "tenant.member.update", Domain: "access", Application: "tenant_member_lifecycle", UseCase: "update_tenant_member",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.member.manage"), authz.PermissionKey("tenant.role.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.member.lifecycle"},
		RPC: "/access.v1.TenantMemberLifecycleApplication/UpdateTenantMember", HTTP: []HTTPBinding{{Method: "PATCH", Path: "/v1/tenant/members/{user_id}"}},
	},
	{
		Code: "tenant.profile.get", Domain: "access", Application: "tenant_profile_management", UseCase: "get_tenant_profile",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.organization.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.lifecycle"},
		RPC: "/access.v1.TenantProfileManagementApplication/GetTenantProfile", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/profile"}},
	},
	{
		Code: "tenant.profile.update", Domain: "access", Application: "tenant_profile_management", UseCase: "update_tenant_profile",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.organization.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.lifecycle"},
		RPC: "/access.v1.TenantProfileManagementApplication/UpdateTenantProfile", HTTP: []HTTPBinding{{Method: "PATCH", Path: "/v1/tenant/profile"}},
	},
	{
		Code: "tenant.role.assert_member_deactivation_allowed", Domain: "access", Application: "tenant_role_permission", UseCase: "assert_tenant_member_deactivation_allowed",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.member.manage")}, PermissionMode: "all",
		Classification: "foundation_exempt", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.role.permission"},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "tenant.role.assign_member", Domain: "access", Application: "tenant_role_permission", UseCase: "assign_tenant_role_member",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.role.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.role.permission"},
		RPC: "/access.v1.TenantRolePermissionApplication/AssignTenantRoleMember", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/roles/{role_id}/members"}},
	},
	{
		Code: "tenant.role.bootstrap_owner", Domain: "access", Application: "tenant_role_permission", UseCase: "bootstrap_tenant_owner_role",
		TenantRequired: false, Authentication: []string{"api-key"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.tenant.create")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.role.permission"},
		RPC: "", HTTP: []HTTPBinding{},
	},
	{
		Code: "tenant.role.create", Domain: "access", Application: "tenant_role_permission", UseCase: "create_tenant_role",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.role.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.role.permission"},
		RPC: "/access.v1.TenantRolePermissionApplication/CreateTenantRole", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/roles"}},
	},
	{
		Code: "tenant.role.delete", Domain: "access", Application: "tenant_role_permission", UseCase: "delete_tenant_role",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.role.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.role.permission"},
		RPC: "/access.v1.TenantRolePermissionApplication/DeleteTenantRole", HTTP: []HTTPBinding{{Method: "DELETE", Path: "/v1/tenant/roles/{role_id}"}},
	},
	{
		Code: "tenant.role.disable", Domain: "access", Application: "tenant_role_permission", UseCase: "disable_tenant_role",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.role.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.role.permission"},
		RPC: "/access.v1.TenantRolePermissionApplication/DisableTenantRole", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/roles/{role_id}/disable"}},
	},
	{
		Code: "tenant.role.enable", Domain: "access", Application: "tenant_role_permission", UseCase: "enable_tenant_role",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.role.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.role.permission"},
		RPC: "/access.v1.TenantRolePermissionApplication/EnableTenantRole", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/roles/{role_id}/enable"}},
	},
	{
		Code: "tenant.role.get", Domain: "access", Application: "tenant_role_permission", UseCase: "get_tenant_role",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.role.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.role.permission"},
		RPC: "/access.v1.TenantRolePermissionApplication/GetTenantRole", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/roles/{role_id}"}},
	},
	{
		Code: "tenant.role.list", Domain: "access", Application: "tenant_role_permission", UseCase: "list_tenant_roles",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.role.read")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.role.permission"},
		RPC: "/access.v1.TenantRolePermissionApplication/ListTenantRoles", HTTP: []HTTPBinding{{Method: "GET", Path: "/v1/tenant/roles"}},
	},
	{
		Code: "tenant.role.revoke_member", Domain: "access", Application: "tenant_role_permission", UseCase: "revoke_tenant_role_member",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.role.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.role.permission"},
		RPC: "/access.v1.TenantRolePermissionApplication/RevokeTenantRoleMember", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenant/roles/{role_id}/members/{user_id}/revoke"}},
	},
	{
		Code: "tenant.role.set_data_policy", Domain: "access", Application: "tenant_role_permission", UseCase: "set_tenant_role_data_policy",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.role.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.role.permission"},
		RPC: "/access.v1.TenantRolePermissionApplication/SetTenantRoleDataPolicy", HTTP: []HTTPBinding{{Method: "PUT", Path: "/v1/tenant/roles/{role_id}/data-policy"}},
	},
	{
		Code: "tenant.role.set_permissions", Domain: "access", Application: "tenant_role_permission", UseCase: "set_tenant_role_permissions",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.role.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.role.permission"},
		RPC: "/access.v1.TenantRolePermissionApplication/SetTenantRolePermissions", HTTP: []HTTPBinding{{Method: "PUT", Path: "/v1/tenant/roles/{role_id}/permissions"}},
	},
	{
		Code: "tenant.role.update", Domain: "access", Application: "tenant_role_permission", UseCase: "update_tenant_role",
		TenantRequired: true, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("tenant.role.manage")}, PermissionMode: "all",
		Classification: "tenant_business", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.role.permission"},
		RPC: "/access.v1.TenantRolePermissionApplication/UpdateTenantRole", HTTP: []HTTPBinding{{Method: "PATCH", Path: "/v1/tenant/roles/{role_id}"}},
	},
	{
		Code: "tenant.suspend", Domain: "access", Application: "tenant_lifecycle", UseCase: "suspend_tenant",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.tenant.manage")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.lifecycle"},
		RPC: "/access.v1.TenantLifecycleApplication/SuspendTenant", HTTP: []HTTPBinding{{Method: "POST", Path: "/v1/tenants/{id}/suspend"}},
	},
	{
		Code: "tenant.update", Domain: "access", Application: "tenant_lifecycle", UseCase: "update_tenant",
		TenantRequired: false, Authentication: []string{"api-key", "web-session"},
		Permissions: []authz.PermissionKey{authz.PermissionKey("platform.tenant.manage")}, PermissionMode: "all",
		Classification: "platform_management", ModuleCode: "access-management", CapabilityCodes: []string{"tenant.lifecycle"},
		RPC: "/access.v1.TenantLifecycleApplication/UpdateTenant", HTTP: []HTTPBinding{{Method: "PATCH", Path: "/v1/tenants/{id}"}},
	},
}
