// Code generated by yunka contract; DO NOT EDIT.

package rest

import (
	"errors"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
	application "github.com/hvritual/biz/internal/access/application"
	policy "github.com/hvritual/biz/internal/access/policy"
	protojson "google.golang.org/protobuf/encoding/protojson"
	io "io"
	"net/http"
	execution "yunka.io/framework/execution"
	operation "yunka.io/framework/operation"
	authz "yunka.io/gateway/authz"
)

type TenantDelegationManagementOperationHandler struct {
	application application.TenantDelegationManagementApplication
	executor    operation.Executor
}

func RegisterTenantDelegationManagementOperationExecutor(mux *http.ServeMux, application application.TenantDelegationManagementApplication, executor operation.Executor) error {
	if mux == nil {
		return errors.New("contract C9 REST adapter: mux is required")
	}
	if application == nil {
		return errors.New("contract C9 REST adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 REST adapter: operation executor is required")
	}
	handler := &TenantDelegationManagementOperationHandler{application: application, executor: executor}
	mux.HandleFunc("GET /v1/tenant/delegations/{id}", handler.handleOperationGetTenantDelegation)
	mux.HandleFunc("POST /v1/tenant/delegations/devices", handler.handleOperationGrantTenantDeviceDelegation)
	mux.HandleFunc("GET /v1/tenant/delegations", handler.handleOperationListTenantDelegations)
	mux.HandleFunc("POST /v1/tenant/delegations/{id}:revoke", handler.handleOperationRevokeTenantDelegation)
	return nil
}

func writeTenantDelegationManagementOperationError(writer http.ResponseWriter, err error) {
	if authz.IsDenied(err) {
		statusCode := http.StatusForbidden
		var denied *authz.DeniedError
		if errors.As(err, &denied) && (denied.Decision.Reason == authz.ReasonUnauthenticated || denied.Decision.Reason == authz.ReasonAuthenticationMethod) {
			statusCode = http.StatusUnauthorized
		}
		http.Error(writer, http.StatusText(statusCode), statusCode)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyKeyRequired) {
		http.Error(writer, "idempotency key required", http.StatusBadRequest)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyInProgress) || errors.Is(err, execution.ErrIdempotencyCompleted) {
		http.Error(writer, "idempotency conflict", http.StatusConflict)
		return
	}
	if errors.Is(err, operation.ErrExecutorUnavailable) || errors.Is(err, operation.ErrSecurityUnavailable) || errors.Is(err, operation.ErrSecurityNilContext) || errors.Is(err, operation.ErrIdempotencyUnavailable) {
		http.Error(writer, "operation execution unavailable", http.StatusInternalServerError)
		return
	}
	http.Error(writer, "application request failed", http.StatusBadRequest)
}

func (handler *TenantDelegationManagementOperationHandler) handleOperationGetTenantDelegation(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.GetTenantDelegationRequest{}
	wire.Id = request.PathValue("id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantDelegationManagementGetTenantDelegation(), wire, handler.application.GetTenantDelegation)
	if err != nil {
		writeTenantDelegationManagementOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantDelegationManagementOperationHandler) handleOperationGrantTenantDeviceDelegation(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.GrantTenantDeviceDelegationRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantDelegationManagementGrantTenantDeviceDelegation(), wire, handler.application.GrantTenantDeviceDelegation)
	if err != nil {
		writeTenantDelegationManagementOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantDelegationManagementOperationHandler) handleOperationListTenantDelegations(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.ListTenantDelegationsRequest{}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantDelegationManagementListTenantDelegations(), wire, handler.application.ListTenantDelegations)
	if err != nil {
		writeTenantDelegationManagementOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantDelegationManagementOperationHandler) handleOperationRevokeTenantDelegation(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.RevokeTenantDelegationRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.Id = request.PathValue("id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantDelegationManagementRevokeTenantDelegation(), wire, handler.application.RevokeTenantDelegation)
	if err != nil {
		writeTenantDelegationManagementOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}
