// Code generated by yunka contract; DO NOT EDIT.

package rest

import (
	"errors"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
	application "github.com/hvritual/biz/internal/access/application"
	policy "github.com/hvritual/biz/internal/access/policy"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protojson "google.golang.org/protobuf/encoding/protojson"
	io "io"
	"net/http"
	strconv "strconv"
	execution "yunka.io/framework/execution"
	operation "yunka.io/framework/operation"
	authz "yunka.io/gateway/authz"
	httpbinding "yunka.io/gateway/httpbinding"
)

type TenantMemberLifecycleOperationHandler struct {
	application application.TenantMemberLifecycleApplication
	executor    operation.Executor
}

func RegisterTenantMemberLifecycleOperationExecutor(mux *http.ServeMux, application application.TenantMemberLifecycleApplication, executor operation.Executor) error {
	if mux == nil {
		return errors.New("contract C9 REST adapter: mux is required")
	}
	if application == nil {
		return errors.New("contract C9 REST adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 REST adapter: operation executor is required")
	}
	handler := &TenantMemberLifecycleOperationHandler{application: application, executor: executor}
	if err := httpbinding.Register(mux, "POST", "/v1/tenant/members/{user_id}/activate", handler.handleOperationActivateTenantMember); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "POST", "/v1/tenant/members/create", handler.handleOperationCreateTenantMember); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "GET", "/v1/tenant/me/profile", handler.handleOperationGetMyPersonalProfile); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "GET", "/v1/tenant/members/{user_id}", handler.handleOperationGetTenantMember); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "POST", "/v1/tenant/members", handler.handleOperationInviteTenantMember); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "GET", "/v1/tenant/me/avatar-options", handler.handleOperationListMyPersonalAvatarOptions); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "GET", "/v1/tenant/members/removed", handler.handleOperationListRemovedTenantMembers); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "GET", "/v1/tenant/members", handler.handleOperationListTenantMembers); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "POST", "/v1/tenant/members/{user_id}/remove", handler.handleOperationRemoveTenantMember); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "POST", "/v1/tenant/members/{user_id}/restore", handler.handleOperationRestoreTenantMember); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "POST", "/v1/tenant/members/{user_id}/suspend", handler.handleOperationSuspendTenantMember); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "PATCH", "/v1/tenant/me/avatar", handler.handleOperationUpdateMyPersonalAvatar); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "PATCH", "/v1/tenant/members/{user_id}", handler.handleOperationUpdateTenantMember); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "PATCH", "/v1/tenant/members/{user_id}/profile", handler.handleOperationUpdateTenantMemberProfile); err != nil {
		return err
	}
	return nil
}

func writeTenantMemberLifecycleOperationError(writer http.ResponseWriter, err error) {
	if authz.IsDenied(err) {
		statusCode := http.StatusForbidden
		var denied *authz.DeniedError
		if errors.As(err, &denied) && (denied.Decision.Reason == authz.ReasonUnauthenticated || denied.Decision.Reason == authz.ReasonAuthenticationMethod) {
			statusCode = http.StatusUnauthorized
		}
		http.Error(writer, http.StatusText(statusCode), statusCode)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyKeyRequired) {
		http.Error(writer, "idempotency key required", http.StatusBadRequest)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyInProgress) || errors.Is(err, execution.ErrIdempotencyCompleted) {
		http.Error(writer, "idempotency conflict", http.StatusConflict)
		return
	}
	if code := status.Code(err); code == codes.Aborted || code == codes.AlreadyExists {
		http.Error(writer, "application conflict", http.StatusConflict)
		return
	}
	if errors.Is(err, operation.ErrExecutorUnavailable) || errors.Is(err, operation.ErrSecurityUnavailable) || errors.Is(err, operation.ErrSecurityNilContext) || errors.Is(err, operation.ErrIdempotencyUnavailable) {
		http.Error(writer, "operation execution unavailable", http.StatusInternalServerError)
		return
	}
	http.Error(writer, "application request failed", http.StatusBadRequest)
}

func (handler *TenantMemberLifecycleOperationHandler) handleOperationActivateTenantMember(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.ActivateTenantMemberRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.UserId = request.PathValue("user_id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantMemberLifecycleActivateTenantMember(), wire, handler.application.ActivateTenantMember)
	if err != nil {
		writeTenantMemberLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantMemberLifecycleOperationHandler) handleOperationCreateTenantMember(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.CreateTenantMemberRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantMemberLifecycleCreateTenantMember(), wire, handler.application.CreateTenantMember)
	if err != nil {
		writeTenantMemberLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantMemberLifecycleOperationHandler) handleOperationGetMyPersonalProfile(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.GetMyPersonalProfileRequest{}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantMemberLifecycleGetMyPersonalProfile(), wire, handler.application.GetMyPersonalProfile)
	if err != nil {
		writeTenantMemberLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantMemberLifecycleOperationHandler) handleOperationGetTenantMember(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.GetTenantMemberRequest{}
	wire.UserId = request.PathValue("user_id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantMemberLifecycleGetTenantMember(), wire, handler.application.GetTenantMember)
	if err != nil {
		writeTenantMemberLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantMemberLifecycleOperationHandler) handleOperationInviteTenantMember(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.InviteTenantMemberRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantMemberLifecycleInviteTenantMember(), wire, handler.application.InviteTenantMember)
	if err != nil {
		writeTenantMemberLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantMemberLifecycleOperationHandler) handleOperationListMyPersonalAvatarOptions(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.ListMyPersonalAvatarOptionsRequest{}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantMemberLifecycleListMyPersonalAvatarOptions(), wire, handler.application.ListMyPersonalAvatarOptions)
	if err != nil {
		writeTenantMemberLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantMemberLifecycleOperationHandler) handleOperationListRemovedTenantMembers(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.ListRemovedTenantMembersRequest{}
	if raw := request.URL.Query().Get("page"); raw != "" {
		parsed, err := strconv.ParseUint(raw, 10, 32)
		if err != nil {
			http.Error(writer, "invalid request parameter", http.StatusBadRequest)
			return
		}
		wire.Page = uint32(parsed)
	}
	if raw := request.URL.Query().Get("page_size"); raw != "" {
		parsed, err := strconv.ParseUint(raw, 10, 32)
		if err != nil {
			http.Error(writer, "invalid request parameter", http.StatusBadRequest)
			return
		}
		wire.PageSize = uint32(parsed)
	}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantMemberLifecycleListRemovedTenantMembers(), wire, handler.application.ListRemovedTenantMembers)
	if err != nil {
		writeTenantMemberLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantMemberLifecycleOperationHandler) handleOperationListTenantMembers(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.ListTenantMembersRequest{}
	if raw := request.URL.Query().Get("query"); raw != "" {
		wire.Query = raw
	}
	if raw := request.URL.Query().Get("role_id"); raw != "" {
		wire.RoleId = raw
	}
	if raw := request.URL.Query().Get("department_id"); raw != "" {
		wire.DepartmentId = raw
	}
	if raw := request.URL.Query().Get("page"); raw != "" {
		parsed, err := strconv.ParseUint(raw, 10, 32)
		if err != nil {
			http.Error(writer, "invalid request parameter", http.StatusBadRequest)
			return
		}
		wire.Page = uint32(parsed)
	}
	if raw := request.URL.Query().Get("page_size"); raw != "" {
		parsed, err := strconv.ParseUint(raw, 10, 32)
		if err != nil {
			http.Error(writer, "invalid request parameter", http.StatusBadRequest)
			return
		}
		wire.PageSize = uint32(parsed)
	}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantMemberLifecycleListTenantMembers(), wire, handler.application.ListTenantMembers)
	if err != nil {
		writeTenantMemberLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantMemberLifecycleOperationHandler) handleOperationRemoveTenantMember(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.RemoveTenantMemberRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.UserId = request.PathValue("user_id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantMemberLifecycleRemoveTenantMember(), wire, handler.application.RemoveTenantMember)
	if err != nil {
		writeTenantMemberLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantMemberLifecycleOperationHandler) handleOperationRestoreTenantMember(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.RestoreTenantMemberRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.UserId = request.PathValue("user_id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantMemberLifecycleRestoreTenantMember(), wire, handler.application.RestoreTenantMember)
	if err != nil {
		writeTenantMemberLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantMemberLifecycleOperationHandler) handleOperationSuspendTenantMember(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.SuspendTenantMemberRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.UserId = request.PathValue("user_id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantMemberLifecycleSuspendTenantMember(), wire, handler.application.SuspendTenantMember)
	if err != nil {
		writeTenantMemberLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantMemberLifecycleOperationHandler) handleOperationUpdateMyPersonalAvatar(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.UpdateMyPersonalAvatarRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantMemberLifecycleUpdateMyPersonalAvatar(), wire, handler.application.UpdateMyPersonalAvatar)
	if err != nil {
		writeTenantMemberLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantMemberLifecycleOperationHandler) handleOperationUpdateTenantMember(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.UpdateTenantMemberRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.UserId = request.PathValue("user_id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantMemberLifecycleUpdateTenantMember(), wire, handler.application.UpdateTenantMember)
	if err != nil {
		writeTenantMemberLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantMemberLifecycleOperationHandler) handleOperationUpdateTenantMemberProfile(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.UpdateTenantMemberProfileRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.UserId = request.PathValue("user_id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantMemberLifecycleUpdateTenantMemberProfile(), wire, handler.application.UpdateTenantMemberProfile)
	if err != nil {
		writeTenantMemberLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}
