// Code generated by yunka contract; DO NOT EDIT.

package rest

import (
	"errors"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
	application "github.com/hvritual/biz/internal/access/application"
	policy "github.com/hvritual/biz/internal/access/policy"
	protojson "google.golang.org/protobuf/encoding/protojson"
	io "io"
	"net/http"
	execution "yunka.io/framework/execution"
	operation "yunka.io/framework/operation"
	authz "yunka.io/gateway/authz"
)

type TenantRolePermissionOperationHandler struct {
	application application.TenantRolePermissionApplication
	executor    operation.Executor
}

func RegisterTenantRolePermissionOperationExecutor(mux *http.ServeMux, application application.TenantRolePermissionApplication, executor operation.Executor) error {
	if mux == nil {
		return errors.New("contract C9 REST adapter: mux is required")
	}
	if application == nil {
		return errors.New("contract C9 REST adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 REST adapter: operation executor is required")
	}
	handler := &TenantRolePermissionOperationHandler{application: application, executor: executor}
	mux.HandleFunc("POST /v1/tenant/roles/{role_id}/members", handler.handleOperationAssignTenantRoleMember)
	mux.HandleFunc("POST /v1/tenant/roles", handler.handleOperationCreateTenantRole)
	mux.HandleFunc("POST /v1/tenant/roles/{role_id}/disable", handler.handleOperationDisableTenantRole)
	mux.HandleFunc("POST /v1/tenant/roles/{role_id}/enable", handler.handleOperationEnableTenantRole)
	mux.HandleFunc("GET /v1/tenant/roles/{role_id}", handler.handleOperationGetTenantRole)
	mux.HandleFunc("GET /v1/tenant/roles", handler.handleOperationListTenantRoles)
	mux.HandleFunc("POST /v1/tenant/roles/{role_id}/members/{user_id}/revoke", handler.handleOperationRevokeTenantRoleMember)
	mux.HandleFunc("PUT /v1/tenant/roles/{role_id}/permissions", handler.handleOperationSetTenantRolePermissions)
	mux.HandleFunc("PATCH /v1/tenant/roles/{role_id}", handler.handleOperationUpdateTenantRole)
	return nil
}

func writeTenantRolePermissionOperationError(writer http.ResponseWriter, err error) {
	if authz.IsDenied(err) {
		statusCode := http.StatusForbidden
		var denied *authz.DeniedError
		if errors.As(err, &denied) && (denied.Decision.Reason == authz.ReasonUnauthenticated || denied.Decision.Reason == authz.ReasonAuthenticationMethod) {
			statusCode = http.StatusUnauthorized
		}
		http.Error(writer, http.StatusText(statusCode), statusCode)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyKeyRequired) {
		http.Error(writer, "idempotency key required", http.StatusBadRequest)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyInProgress) || errors.Is(err, execution.ErrIdempotencyCompleted) {
		http.Error(writer, "idempotency conflict", http.StatusConflict)
		return
	}
	if errors.Is(err, operation.ErrExecutorUnavailable) || errors.Is(err, operation.ErrSecurityUnavailable) || errors.Is(err, operation.ErrSecurityNilContext) || errors.Is(err, operation.ErrIdempotencyUnavailable) {
		http.Error(writer, "operation execution unavailable", http.StatusInternalServerError)
		return
	}
	http.Error(writer, "application request failed", http.StatusBadRequest)
}

func (handler *TenantRolePermissionOperationHandler) handleOperationAssignTenantRoleMember(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.AssignTenantRoleMemberRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.RoleId = request.PathValue("role_id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantRolePermissionAssignTenantRoleMember(), wire, handler.application.AssignTenantRoleMember)
	if err != nil {
		writeTenantRolePermissionOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantRolePermissionOperationHandler) handleOperationCreateTenantRole(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.CreateTenantRoleRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantRolePermissionCreateTenantRole(), wire, handler.application.CreateTenantRole)
	if err != nil {
		writeTenantRolePermissionOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantRolePermissionOperationHandler) handleOperationDisableTenantRole(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.DisableTenantRoleRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.RoleId = request.PathValue("role_id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantRolePermissionDisableTenantRole(), wire, handler.application.DisableTenantRole)
	if err != nil {
		writeTenantRolePermissionOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantRolePermissionOperationHandler) handleOperationEnableTenantRole(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.EnableTenantRoleRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.RoleId = request.PathValue("role_id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantRolePermissionEnableTenantRole(), wire, handler.application.EnableTenantRole)
	if err != nil {
		writeTenantRolePermissionOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantRolePermissionOperationHandler) handleOperationGetTenantRole(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.GetTenantRoleRequest{}
	wire.RoleId = request.PathValue("role_id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantRolePermissionGetTenantRole(), wire, handler.application.GetTenantRole)
	if err != nil {
		writeTenantRolePermissionOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantRolePermissionOperationHandler) handleOperationListTenantRoles(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.ListTenantRolesRequest{}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantRolePermissionListTenantRoles(), wire, handler.application.ListTenantRoles)
	if err != nil {
		writeTenantRolePermissionOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantRolePermissionOperationHandler) handleOperationRevokeTenantRoleMember(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.RevokeTenantRoleMemberRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.RoleId = request.PathValue("role_id")
	wire.UserId = request.PathValue("user_id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantRolePermissionRevokeTenantRoleMember(), wire, handler.application.RevokeTenantRoleMember)
	if err != nil {
		writeTenantRolePermissionOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantRolePermissionOperationHandler) handleOperationSetTenantRolePermissions(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.SetTenantRolePermissionsRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.RoleId = request.PathValue("role_id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantRolePermissionSetTenantRolePermissions(), wire, handler.application.SetTenantRolePermissions)
	if err != nil {
		writeTenantRolePermissionOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantRolePermissionOperationHandler) handleOperationUpdateTenantRole(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.UpdateTenantRoleRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.RoleId = request.PathValue("role_id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantRolePermissionUpdateTenantRole(), wire, handler.application.UpdateTenantRole)
	if err != nil {
		writeTenantRolePermissionOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}
