// Code generated by yunka contract; DO NOT EDIT.

package rest

import (
	"errors"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
	application "github.com/hvritual/biz/internal/access/application"
	policy "github.com/hvritual/biz/internal/access/policy"
	protojson "google.golang.org/protobuf/encoding/protojson"
	io "io"
	"net/http"
	execution "github.com/hvritual/yunka.io/framework/execution"
	operation "github.com/hvritual/yunka.io/framework/operation"
	authz "github.com/hvritual/yunka.io/gateway/authz"
)

type TenantLifecycleOperationHandler struct {
	application application.TenantLifecycleApplication
	executor    operation.Executor
}

func RegisterTenantLifecycleOperationExecutor(mux *http.ServeMux, application application.TenantLifecycleApplication, executor operation.Executor) error {
	if mux == nil {
		return errors.New("contract C9 REST adapter: mux is required")
	}
	if application == nil {
		return errors.New("contract C9 REST adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 REST adapter: operation executor is required")
	}
	handler := &TenantLifecycleOperationHandler{application: application, executor: executor}
	mux.HandleFunc("POST /v1/tenants/{id}/activate", handler.handleOperationActivateTenant)
	mux.HandleFunc("POST /v1/tenants/{id}/close", handler.handleOperationCloseTenant)
	mux.HandleFunc("POST /v1/tenants", handler.handleOperationCreateTenant)
	mux.HandleFunc("GET /v1/tenants/{id}", handler.handleOperationGetTenant)
	mux.HandleFunc("GET /v1/tenants", handler.handleOperationListTenants)
	mux.HandleFunc("POST /v1/tenants/{id}/suspend", handler.handleOperationSuspendTenant)
	mux.HandleFunc("PATCH /v1/tenants/{id}", handler.handleOperationUpdateTenant)
	return nil
}

func writeTenantLifecycleOperationError(writer http.ResponseWriter, err error) {
	if authz.IsDenied(err) {
		statusCode := http.StatusForbidden
		var denied *authz.DeniedError
		if errors.As(err, &denied) && (denied.Decision.Reason == authz.ReasonUnauthenticated || denied.Decision.Reason == authz.ReasonAuthenticationMethod) {
			statusCode = http.StatusUnauthorized
		}
		http.Error(writer, http.StatusText(statusCode), statusCode)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyKeyRequired) {
		http.Error(writer, "idempotency key required", http.StatusBadRequest)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyInProgress) || errors.Is(err, execution.ErrIdempotencyCompleted) {
		http.Error(writer, "idempotency conflict", http.StatusConflict)
		return
	}
	if errors.Is(err, operation.ErrExecutorUnavailable) || errors.Is(err, operation.ErrSecurityUnavailable) || errors.Is(err, operation.ErrSecurityNilContext) || errors.Is(err, operation.ErrIdempotencyUnavailable) {
		http.Error(writer, "operation execution unavailable", http.StatusInternalServerError)
		return
	}
	http.Error(writer, "application request failed", http.StatusBadRequest)
}

func (handler *TenantLifecycleOperationHandler) handleOperationActivateTenant(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.ActivateTenantRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.Id = request.PathValue("id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantLifecycleActivateTenant(), wire, handler.application.ActivateTenant)
	if err != nil {
		writeTenantLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantLifecycleOperationHandler) handleOperationCloseTenant(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.CloseTenantRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.Id = request.PathValue("id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantLifecycleCloseTenant(), wire, handler.application.CloseTenant)
	if err != nil {
		writeTenantLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantLifecycleOperationHandler) handleOperationCreateTenant(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.CreateTenantRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantLifecycleCreateTenant(), wire, handler.application.CreateTenant)
	if err != nil {
		writeTenantLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantLifecycleOperationHandler) handleOperationGetTenant(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.GetTenantRequest{}
	wire.Id = request.PathValue("id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantLifecycleGetTenant(), wire, handler.application.GetTenant)
	if err != nil {
		writeTenantLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantLifecycleOperationHandler) handleOperationListTenants(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.ListTenantsRequest{}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantLifecycleListTenants(), wire, handler.application.ListTenants)
	if err != nil {
		writeTenantLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantLifecycleOperationHandler) handleOperationSuspendTenant(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.SuspendTenantRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.Id = request.PathValue("id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantLifecycleSuspendTenant(), wire, handler.application.SuspendTenant)
	if err != nil {
		writeTenantLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *TenantLifecycleOperationHandler) handleOperationUpdateTenant(writer http.ResponseWriter, request *http.Request) {
	wire := &accessv1.UpdateTenantRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.Id = request.PathValue("id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanTenantLifecycleUpdateTenant(), wire, handler.application.UpdateTenant)
	if err != nil {
		writeTenantLifecycleOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}
