package capabilitymap

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

func Artifacts(document Document) (map[string][]byte, error) {
	data, err := json.MarshalIndent(document, "", "  ")
	if err != nil {
		return nil, err
	}
	ids, capabilities, modules := []string{}, []string{}, []string{}
	seenModules := map[string]bool{}
	for _, entry := range document.Operations {
		ids = append(ids, entry.OperationID)
	}
	for _, capability := range document.Capabilities {
		capabilities = append(capabilities, capability.Code)
		if !seenModules[capability.ModuleCode] {
			modules = append(modules, capability.ModuleCode)
			seenModules[capability.ModuleCode] = true
		}
	}
	var ts bytes.Buffer
	ts.WriteString("// Generated by commercial-catalog; DO NOT EDIT. Metadata only, not authorization.\n")
	fmt.Fprintf(&ts, "export const mappingVersion = %q as const;\n", document.MappingVersion)
	for _, item := range []struct {
		name, typeName string
		values         []string
	}{
		{"operationIds", "OperationId", ids},
		{"capabilityCodes", "CapabilityCode", capabilities},
		{"moduleCodes", "ModuleCode", modules},
		{"classifications", "Classification", []string{string(TenantBusiness), string(PlatformManagement), string(Recovery), string(FoundationExempt)}},
		{"consumerTypes", "ConsumerType", []string{"tenant", "platform", "internal_child", "worker"}},
	} {
		encoded, err := json.MarshalIndent(sorted(item.values), "", "  ")
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&ts, "export const %s = %s as const;\nexport type %s = typeof %s[number];\n", item.name, encoded, item.typeName, item.name)
	}
	return map[string][]byte{JSONPath: append(data, '\n'), TypesPath: ts.Bytes()}, nil
}

// SyncArtifacts is read-only unless write is explicit. Missing and stale
// generated outputs both fail check mode instead of being silently repaired.
func SyncArtifacts(root string, document Document, write bool) error {
	artifacts, err := Artifacts(document)
	if err != nil {
		return err
	}
	for _, path := range []string{JSONPath, TypesPath} {
		expected := artifacts[path]
		full := filepath.Join(root, path)
		if !write {
			actual, err := os.ReadFile(full)
			if err != nil || !bytes.Equal(actual, expected) {
				return problem("GENERATED_DRIFT", path, "run make commercial-generate and commit the derived outputs")
			}
			continue
		}
		if err := atomicWrite(full, expected); err != nil {
			return err
		}
	}
	return nil
}

func atomicWrite(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	file, err := os.CreateTemp(filepath.Dir(path), ".commercial-*")
	if err != nil {
		return err
	}
	defer os.Remove(file.Name())
	if _, err = file.Write(data); err != nil {
		_ = file.Close()
		return err
	}
	if err = file.Chmod(0644); err != nil {
		_ = file.Close()
		return err
	}
	if err = file.Close(); err != nil {
		return err
	}
	return os.Rename(file.Name(), path)
}
