// Code generated by yunka contract; DO NOT EDIT.

package rpc

import (
	"context"
	"errors"
	commercialv1 "github.com/hvritual/biz/contracts/gen/commercial/v1"
	application "github.com/hvritual/biz/internal/commercial/application"
	policy "github.com/hvritual/biz/internal/commercial/policy"
	grpc "google.golang.org/grpc"
	grpcmetadata "google.golang.org/grpc/metadata"
	execution "yunka.io/framework/execution"
	operation "yunka.io/framework/operation"
	gatewaygrpc "yunka.io/gateway/rpc/transport/grpc"
)

type SubscriptionChangesOperationServer struct {
	commercialv1.UnimplementedSubscriptionChangesApplicationServer
	application application.SubscriptionChangesApplication
	executor    operation.Executor
}

func RegisterSubscriptionChangesOperationExecutor(registrar grpc.ServiceRegistrar, application application.SubscriptionChangesApplication, executor operation.Executor) error {
	if registrar == nil {
		return errors.New("contract C9 RPC adapter: registrar is required")
	}
	if application == nil {
		return errors.New("contract C9 RPC adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 RPC adapter: operation executor is required")
	}
	commercialv1.RegisterSubscriptionChangesApplicationServer(registrar, &SubscriptionChangesOperationServer{application: application, executor: executor})
	return nil
}

func (server *SubscriptionChangesOperationServer) ConfirmSubscriptionChange(ctx context.Context, request *commercialv1.ConfirmSubscriptionChangeRequest) (*commercialv1.SubscriptionChangeReceiptDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanSubscriptionChangesConfirmSubscriptionChange(), request, server.application.ConfirmSubscriptionChange)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *SubscriptionChangesOperationServer) GetSubscriptionChangePreview(ctx context.Context, request *commercialv1.ReadSubscriptionChangeRequest) (*commercialv1.SubscriptionChangePreviewDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanSubscriptionChangesGetSubscriptionChangePreview(), request, server.application.GetSubscriptionChangePreview)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *SubscriptionChangesOperationServer) GetSubscriptionChangeReceipt(ctx context.Context, request *commercialv1.ReadSubscriptionChangeRequest) (*commercialv1.SubscriptionChangeReceiptDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanSubscriptionChangesGetSubscriptionChangeReceipt(), request, server.application.GetSubscriptionChangeReceipt)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *SubscriptionChangesOperationServer) PreviewSubscriptionChange(ctx context.Context, request *commercialv1.PreviewSubscriptionChangeRequest) (*commercialv1.SubscriptionChangePreviewDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanSubscriptionChangesPreviewSubscriptionChange(), request, server.application.PreviewSubscriptionChange)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}
