// Code generated by yunka contract; DO NOT EDIT.

package rpc

import (
	"context"
	"errors"
	commercialv1 "github.com/hvritual/biz/contracts/gen/commercial/v1"
	application "github.com/hvritual/biz/internal/commercial/application"
	policy "github.com/hvritual/biz/internal/commercial/policy"
	grpc "google.golang.org/grpc"
	grpcmetadata "google.golang.org/grpc/metadata"
	execution "yunka.io/framework/execution"
	operation "yunka.io/framework/operation"
	gatewaygrpc "yunka.io/gateway/rpc/transport/grpc"
)

type SubscriptionManagementOperationServer struct {
	commercialv1.UnimplementedSubscriptionManagementApplicationServer
	application application.SubscriptionManagementApplication
	executor    operation.Executor
}

func RegisterSubscriptionManagementOperationExecutor(registrar grpc.ServiceRegistrar, application application.SubscriptionManagementApplication, executor operation.Executor) error {
	if registrar == nil {
		return errors.New("contract C9 RPC adapter: registrar is required")
	}
	if application == nil {
		return errors.New("contract C9 RPC adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 RPC adapter: operation executor is required")
	}
	commercialv1.RegisterSubscriptionManagementApplicationServer(registrar, &SubscriptionManagementOperationServer{application: application, executor: executor})
	return nil
}

func (server *SubscriptionManagementOperationServer) GetTenantSubscription(ctx context.Context, request *commercialv1.GetTenantSubscriptionRequest) (*commercialv1.TenantSubscriptionDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanSubscriptionManagementGetTenantSubscription(), request, server.application.GetTenantSubscription)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *SubscriptionManagementOperationServer) ListDefaultSubscriptionRules(ctx context.Context, request *commercialv1.ListDefaultSubscriptionRulesRequest) (*commercialv1.ListDefaultSubscriptionRulesResponse, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanSubscriptionManagementListDefaultSubscriptionRules(), request, server.application.ListDefaultSubscriptionRules)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *SubscriptionManagementOperationServer) PutDefaultSubscriptionRule(ctx context.Context, request *commercialv1.PutDefaultSubscriptionRuleRequest) (*commercialv1.DefaultSubscriptionRuleDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanSubscriptionManagementPutDefaultSubscriptionRule(), request, server.application.PutDefaultSubscriptionRule)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}
