// Code generated by yunka contract; DO NOT EDIT.

package rpc

import (
	"context"
	"errors"
	commercialv1 "github.com/hvritual/biz/contracts/gen/commercial/v1"
	application "github.com/hvritual/biz/internal/commercial/application"
	policy "github.com/hvritual/biz/internal/commercial/policy"
	grpc "google.golang.org/grpc"
	grpcmetadata "google.golang.org/grpc/metadata"
	execution "yunka.io/framework/execution"
	operation "yunka.io/framework/operation"
	gatewaygrpc "yunka.io/gateway/rpc/transport/grpc"
)

type EntitlementManagementOperationServer struct {
	commercialv1.UnimplementedEntitlementManagementApplicationServer
	application application.EntitlementManagementApplication
	executor    operation.Executor
}

func RegisterEntitlementManagementOperationExecutor(registrar grpc.ServiceRegistrar, application application.EntitlementManagementApplication, executor operation.Executor) error {
	if registrar == nil {
		return errors.New("contract C9 RPC adapter: registrar is required")
	}
	if application == nil {
		return errors.New("contract C9 RPC adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 RPC adapter: operation executor is required")
	}
	commercialv1.RegisterEntitlementManagementApplicationServer(registrar, &EntitlementManagementOperationServer{application: application, executor: executor})
	return nil
}

func (server *EntitlementManagementOperationServer) CreateEntitlementOverride(ctx context.Context, request *commercialv1.CreateEntitlementOverrideRequest) (*commercialv1.EntitlementOverrideReceipt, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanEntitlementManagementCreateEntitlementOverride(), request, server.application.CreateEntitlementOverride)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *EntitlementManagementOperationServer) ExplainEntitlements(ctx context.Context, request *commercialv1.ExplainEntitlementsRequest) (*commercialv1.EntitlementView, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanEntitlementManagementExplainEntitlements(), request, server.application.ExplainEntitlements)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *EntitlementManagementOperationServer) GetMyEntitlements(ctx context.Context, request *commercialv1.GetMyEntitlementsRequest) (*commercialv1.EntitlementView, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanEntitlementManagementGetMyEntitlements(), request, server.application.GetMyEntitlements)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *EntitlementManagementOperationServer) ListEntitlementOverrides(ctx context.Context, request *commercialv1.ListEntitlementOverridesRequest) (*commercialv1.ListEntitlementOverridesResponse, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanEntitlementManagementListEntitlementOverrides(), request, server.application.ListEntitlementOverrides)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *EntitlementManagementOperationServer) RevokeEntitlementOverride(ctx context.Context, request *commercialv1.RevokeEntitlementOverrideRequest) (*commercialv1.EntitlementOverrideReceipt, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanEntitlementManagementRevokeEntitlementOverride(), request, server.application.RevokeEntitlementOverride)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}
