import type { CustomerSnapshot } from '@/types/customer'
import type { RentalSite, RentalState, RentalRule } from '@/types/siteRental'
/** Demonstration extension of the existing SITE identities; delivery rows remain event projections. */
export function createRentalSeed(s: CustomerSnapshot): RentalState {
  const profiles: RentalSite[] = s.sites.map((x, i) => ({
    id: x.id,
    customerId: x.customerId,
    name: x.name,
    parent: '苏州运营片区',
    kind: 'site',
    scene: '酒店公共空间',
    address: `苏州市 · ${['园区大堂 / 1F', '新区门店 / 接待区', '高铁新店 / 茶歇区'][i] || '待补充'}`,
    contact: '林悦',
    phone: '136****2908',
    owner: x.owner,
    hours: '每日 07:00—22:00',
    access: '上门前一天预约；进场需联系前台',
    water: '净水接入',
    power: '独立接地电源',
    network: '4G · Wi-Fi 备用',
    cleaning: '客户现场人员',
    supplies: '出租方补货',
    phase: x.accepted ? '服务中' : '安装验收中',
    operation: '正常运营',
    service: x.accepted ? '正常' : '待核实',
    nextAction: x.accepted ? '本周用量回访与清洁检查' : '复验出杯温度与培训结果',
    nextAt: '2026-09-12 10:00',
    version: 1,
  }))
  const customer = s.customers.find((x) => x.id === 'CUS-0186')
  if (!customer)
    return {
      schema: 1,
      operations: [],
      profiles,
      deployments: [],
      usage: [],
      rules: [],
      drafts: {},
      statements: [],
    }
  for (const [id, name, scene] of [
    ['SITE-044', '上海总部 · 接待区', '企业办公'],
    ['SITE-045', '上海总部 · 员工茶水间', '企业办公'],
  ]) {
    profiles.push({
      id: id!,
      customerId: customer.id,
      name: name!,
      parent: '上海总部',
      kind: 'site',
      scene: scene!,
      address: '上海市 · 总部大楼 / 3F',
      contact: '周岚',
      phone: '138****6021',
      owner: '张敏',
      hours: '工作日 09:00—18:00',
      access: '提前预约；货梯进场',
      water: '桶装水',
      power: '独立接地电源',
      network: '以太网',
      cleaning: '客户行政',
      supplies: '客户自行采购',
      phase: '服务中',
      operation: '正常运营',
      service: '正常',
      nextAction: '核对本月租约范围与使用需求',
      nextAt: '2026-09-15 14:00',
      version: 1,
    })
  }
  const rule = (
    id: string,
    groupId: string,
    name: string,
    siteIds: string[],
    mode: RentalRule['mode'],
    scope: RentalRule['scope'],
    contractId: string,
    baseCents: number,
  ): RentalRule => ({
    id,
    groupId,
    version: 1,
    name,
    customerId: customer.id,
    contractId,
    siteIds,
    mode,
    scope,
    fixedUnit: 'site',
    baseCents,
    unitCents: 160,
    includedCups: 2000,
    minimumKind: 'included',
    billingOwner: customer.name,
    billPresentation: '客户汇总',
    effectiveFrom: '2026-09-01',
    reason: '初始合同计费约定（示例）',
  })
  const validIds = new Set(profiles.map((x) => x.id))
  const rules = [
    rule(
      'RV-SZ-1',
      'BG-SZ-01',
      '苏州双点位共享组',
      ['SITE-041', 'SITE-042'],
      'included',
      'shared',
      'HT-2026-041',
      240000,
    ),
    rule(
      'RV-SH-1',
      'BG-SH-01',
      '上海接待区月租',
      ['SITE-044'],
      'fixed',
      'independent',
      'HT-2026-018',
      120000,
    ),
    rule(
      'RV-SH-2',
      'BG-SH-02',
      '上海员工茶水间用量',
      ['SITE-045'],
      'metered',
      'independent',
      'HT-2026-018',
      0,
    ),
  ].filter((x) => x.siteIds.every((id) => validIds.has(id)))
  return {
    schema: 1,
    operations: [],
    profiles,
    rules,
    drafts: {},
    statements: [],
    deployments: [
      ...s.sites.map((x) => ({
        id: x.placement,
        siteId: x.id,
        device: x.device,
        model: '全自动咖啡机',
        from: '2026-09-01',
        until: '',
        role: '主机' as const,
        state: '有效' as const,
        online: x.accepted ? true : null,
      })),
      {
        id: 'PD-044',
        siteId: 'SITE-044',
        device: 'CL-SH-044',
        model: '办公室咖啡机',
        from: '2026-01-01',
        until: '',
        role: '主机',
        state: '有效',
        online: true,
      },
      {
        id: 'PD-045',
        siteId: 'SITE-045',
        device: 'CL-SH-045',
        model: '办公室咖啡机',
        from: '2026-01-01',
        until: '',
        role: '主机',
        state: '有效',
        online: true,
      },
      {
        id: 'PD-041-H',
        siteId: 'SITE-041',
        device: 'CL-SZ-009',
        model: '历史替换设备',
        from: '2026-05-01',
        until: '2026-09-01',
        role: '主机',
        state: '历史保留',
        online: null,
      },
    ],
    usage: [
      ['SITE-041', 620, 20],
      ['SITE-042', 1340, 40],
      ['SITE-044', 980, 0],
      ['SITE-045', 1520, 20],
    ].map(([siteId, raw, excluded]) => ({
      siteId: String(siteId),
      period: '2026-09',
      raw: Number(raw),
      excluded: Number(excluded),
      exclusionNote: '按本示例合同排除测试制作；不是所有合同的默认计费规则',
      quality: '完整' as const,
      asOf: '2026-10-01 08:00（示例月末快照）',
      revision: 1,
    })),
  }
}
