<script setup lang="ts">
import { UiButton, UiInput, UiOption, UiSelect } from '@/ui/base'
import { computed, onBeforeUnmount, onMounted, ref, toRaw } from 'vue'
import { useI18n } from 'vue-i18n'
import { formatNumber } from '@/i18n'
import AppIcon from '@/ui/common/AppIcon.vue'
import AppPagination from '@/ui/common/AppPagination.vue'
import PageHeading from '@/ui/common/PageHeading.vue'
import StatusBadge from '@/ui/common/StatusBadge.vue'
import UiDialog from '@/ui/common/UiDialog.vue'
import { loginUrl, logoutSession, readSession, type Tenant, type TrustedSession } from '@/services/runtime/api'
import { executeCommand, fields, loadRows } from '@/services/runtime/commands'

const { t, te } = useI18n()
const session=ref<TrustedSession>({authenticated:false}),tenants=ref<Tenant[]>([]),busy=ref(false),error=ref(''),notice=ref(''),keyword=ref(''),statusFilter=ref('all'),page=ref(1),action=ref(''),selected=ref<Tenant|null>(null),input=ref<Record<string,string>>({}),draftKey=ref(''),submitted=ref(false)
const pageSize=ref(10); let epoch=0
const canRead=computed(()=>session.value.authenticated&&session.value.actor_kind==='platform')
const platformIdentity=computed(()=>session.value.platform_subject||t('tenants.platformIdentity'))
const summary=computed(()=>({total:tenants.value.length,active:tenants.value.filter(i=>i.status.includes('ACTIVE')).length,suspended:tenants.value.filter(i=>i.status.includes('SUSPEND')).length,closed:tenants.value.filter(i=>i.status.includes('CLOSED')).length}))
const filtered=computed(()=>{const q=keyword.value.trim().toLowerCase();return tenants.value.filter(item=>(!q||item.name.toLowerCase().includes(q)||item.id.toLowerCase().includes(q))&&(statusFilter.value==='all'||statusKey(item.status)===statusFilter.value))})
const totalPages=computed(()=>Math.max(1,Math.ceil(filtered.value.length/pageSize.value)))
const visibleTenants=computed(()=>{const safe=Math.min(page.value,totalPages.value),start=(safe-1)*pageSize.value;return filtered.value.slice(start,start+pageSize.value)})
const actionTitle=computed(()=>({create:t('tenants.create'),rename:t('tenants.rename'),activate:t('tenants.activate'),suspend:t('tenants.suspend'),close:t('tenants.closeTenant')} as Record<string,string>)[action.value]??t('tenants.operation'))
function identity(value:TrustedSession){return `${value.actor_kind}/${value.platform_subject}/${value.user_id}/${value.active_tenant_id}`}
function statusKey(status:string){if(status.includes('ACTIVE'))return'active';if(status.includes('SUSPEND'))return'suspended';if(status.includes('CLOSED'))return'closed';return'other'}
function statusLabel(status:string){return t(`tenants.statusLabels.${statusKey(status)}`)}
function statusTone(status:string):'success'|'warning'|'danger'|'neutral'{const key=statusKey(status);return key==='active'?'success':key==='suspended'?'warning':key==='closed'?'danger':'neutral'}
function fieldLabel(key:string,fallback:string){const path=`tenants.field.${key}`;return te(path)?t(path):fallback}
function clearDraft(){action.value='';selected.value=null;input.value={};submitted.value=false;draftKey.value=''}
function resetFilters(){keyword.value='';statusFilter.value='all';page.value=1}
function begin(id:string,tenant:Tenant|null=null){clearDraft();action.value=id;selected.value=tenant?structuredClone(toRaw(tenant)):null;input.value=tenant?{name:tenant.name}:{};draftKey.value=crypto.randomUUID();error.value='';notice.value=''}
async function refresh(){const token=++epoch;busy.value=true;error.value='';notice.value='';tenants.value=[];clearDraft();try{const current=await readSession();if(token!==epoch)return false;session.value=current;if(current.authenticated&&current.actor_kind==='platform'){tenants.value=(await loadRows('tenants',current)) as Tenant[];page.value=Math.min(page.value,Math.max(1,Math.ceil(filtered.value.length/pageSize.value)))}return token===epoch}catch(caught){if(token===epoch)error.value=caught instanceof Error?caught.message:t('tenants.readFailed');return false}finally{if(token===epoch)busy.value=false}}
async function logout(){++epoch;busy.value=true;tenants.value=[];clearDraft();try{await logoutSession();session.value={authenticated:false}}catch(caught){error.value=caught instanceof Error?caught.message:t('tenants.logoutFailed')}finally{busy.value=false}}
async function submit(){const token=epoch,originalIdentity=identity(session.value);busy.value=true;error.value='';submitted.value=true;try{const current=await readSession();if(token!==epoch)return;if(!current.authenticated||identity(current)!==originalIdentity){await refresh();error.value=t('tenants.sessionChanged');return}await executeCommand('tenants',action.value,selected.value,input.value,[],draftKey.value,session.value);if(token!==epoch)return;const refreshed=await refresh();notice.value=refreshed?t('tenants.operationReadback'):t('tenants.operationReadbackFailed')}catch(caught){if(token===epoch)error.value=caught instanceof Error?caught.message:t('tenants.operationFailed')}finally{if(token===epoch)busy.value=false}}
onMounted(refresh);onBeforeUnmount(()=>{epoch++})
</script>
<template>
  <div class="page-stack tenant-page" data-ui-template="ListPage" data-testid="platform-tenant-management">
    <div data-ui-region="page-heading"><PageHeading :title="t('tenants.title')" :breadcrumb="t('tenants.breadcrumb')" :description="t('tenants.description')"/></div>
    <section class="identity-strip card" :aria-label="t('tenants.currentIdentity')"><div class="identity-icon"><AppIcon name="shield" :size="20"/></div><div class="flex-1"><strong>{{ session.authenticated?t('tenants.identityValue',{identity:platformIdentity}):t('tenants.noSession') }}</strong><p>{{ canRead?t('tenants.trustedDescription'):t('tenants.tenantDescription') }}</p></div><template v-if="session.authenticated"><StatusBadge :text="canRead?t('tenants.platformIdentity'):t('tenants.nonPlatformIdentity')" :tone="canRead?'primary':'warning'"/><UiButton class="btn" type="button" :disabled="busy" @click="logout">{{ t('common.logout') }}</UiButton></template><a v-else class="btn btn-primary" :href="loginUrl()">{{ t('tenants.loginPlatform') }}</a></section>
    <p v-if="error&&!action" class="notice-box danger" role="alert">{{ error }}</p><p v-if="notice" class="notice-box" role="status">{{ notice }}</p>
    <section v-if="!session.authenticated" class="card empty-state"><AppIcon name="lock" :size="28"/><div><strong>{{ t('tenants.loginRequired') }}</strong><p>{{ t('tenants.loginRequiredDetail') }}</p></div></section>
    <section v-else-if="!canRead" class="card empty-state warning" role="alert"><AppIcon name="shield" :size="28"/><div><strong>{{ t('tenants.platformRequired') }}</strong><p>{{ t('tenants.platformRequiredDetail') }}</p></div></section>
    <template v-else>
      <section class="metric-grid" data-ui-region="metrics" :aria-label="t('tenants.overview')"><article class="card metric-card"><span>{{ t('tenants.total') }}</span><strong>{{ formatNumber(summary.total) }}</strong><small>{{ t('tenants.currentVisible') }}</small></article><article class="card metric-card"><span>{{ t('tenants.active') }}</span><strong>{{ formatNumber(summary.active) }}</strong><small>ACTIVE</small></article><article class="card metric-card"><span>{{ t('tenants.suspended') }}</span><strong>{{ formatNumber(summary.suspended) }}</strong><small>SUSPENDED</small></article><article class="card metric-card"><span>{{ t('tenants.closed') }}</span><strong>{{ formatNumber(summary.closed) }}</strong><small>CLOSED</small></article></section>
      <section class="card query-panel" data-ui-region="query" :aria-label="t('tenants.filter')"><label class="field search-field"><span>{{ t('tenants.nameOrId') }}</span><div class="input-with-icon"><AppIcon name="search" :size="16"/><UiInput v-model="keyword" class="input" :placeholder="t('tenants.inputNameOrId')" @input="page=1"/></div></label><label class="field status-field"><span>{{ t('tenants.status') }}</span><UiSelect v-model="statusFilter" class="select" @change="page=1"><UiOption value="all">{{ t('tenants.allStatus') }}</UiOption><UiOption value="active">{{ t('tenants.active') }}</UiOption><UiOption value="suspended">{{ t('tenants.suspended') }}</UiOption><UiOption value="closed">{{ t('tenants.closed') }}</UiOption></UiSelect></label><div class="query-actions"><UiButton class="btn" type="button" @click="resetFilters">{{ t('common.reset') }}</UiButton><UiButton class="btn" type="button" :disabled="busy" @click="refresh"><AppIcon name="refresh" :size="15"/>{{ t('common.refresh') }}</UiButton></div></section>
      <section class="card data-panel tenant-data-panel" data-ui-region="data"><div class="table-toolbar row-between wrap"><div><h2>{{ t('tenants.list') }}</h2><p>{{ t('tenants.listDescription') }}</p></div><div class="table-actions"><span class="result-count">{{ t('tenants.resultCount',{count:formatNumber(filtered.length)}) }}</span><UiButton class="btn btn-primary" type="button" :disabled="busy" @click="begin('create')"><AppIcon name="plus" :size="15"/>{{ t('tenants.create') }}</UiButton></div></div>
        <p v-if="busy&&!tenants.length" role="status" class="table-state">{{ t('tenants.loading') }}</p><div v-else class="table-scroll"><table class="data-table"><thead><tr><th>{{ t('tenants.columnTenant') }}</th><th>{{ t('tenants.columnStatus') }}</th><th>{{ t('tenants.columnVersion') }}</th><th>{{ t('tenants.columnCommercial') }}</th><th>{{ t('tenants.columnLifecycle') }}</th></tr></thead><tbody><tr v-for="tenant in visibleTenants" :key="tenant.id"><td><strong class="tenant-name">{{ tenant.name }}</strong><small class="tenant-id">{{ tenant.id }}</small></td><td><StatusBadge :text="statusLabel(tenant.status)" :tone="statusTone(tenant.status)"/></td><td class="numeric">{{ formatNumber(tenant.version) }}</td><td><RouterLink class="btn-link" to="/platform/commercial/tenant-entitlements">{{ t('tenants.manageEntitlements') }} <AppIcon name="right" :size="14"/></RouterLink></td><td><div class="row-actions"><UiButton class="btn-link" type="button" :disabled="busy" @click="begin('rename',tenant)">{{ t('tenants.rename') }}</UiButton><UiButton class="btn-link" type="button" :disabled="busy" @click="begin('activate',tenant)">{{ t('tenants.activate') }}</UiButton><UiButton class="btn-link" type="button" :disabled="busy" @click="begin('suspend',tenant)">{{ t('tenants.suspend') }}</UiButton><UiButton class="btn-link danger-link" type="button" :disabled="busy" @click="begin('close',tenant)">{{ t('tenants.closeTenant') }}</UiButton></div></td></tr><tr v-if="!visibleTenants.length"><td colspan="5" class="no-result">{{ t('tenants.noResult') }}</td></tr></tbody></table></div>
        <AppPagination v-model:page="page" v-model:page-size="pageSize" data-ui-region="pagination" :total="filtered.length" />
      </section>
    </template>
    <UiDialog :open="Boolean(action)" :title="actionTitle" @close="!busy&&clearDraft()"><form class="tenant-action-form" @submit.prevent="submit"><div v-if="selected" class="action-object"><span>{{ t('tenants.operationTarget') }}</span><strong>{{ selected.name }}</strong><small>{{ selected.id }} · {{ t('tenants.columnVersion') }} {{ selected.version }}</small></div><label v-for="field in fields('tenants',action)" :key="field.key" class="field"><span>{{ fieldLabel(field.key,field.label) }}</span><UiInput v-model="input[field.key]" class="input" :required="field.required" :disabled="busy||submitted" :type="field.key.toLowerCase().includes('email')?'email':'text'"/></label><p v-if="action==='suspend'" class="notice-box warning">{{ t('tenants.suspendWarning') }}</p><p v-if="action==='close'" class="notice-box danger">{{ t('tenants.closeWarning') }}</p><p v-if="submitted&&error" class="notice-box warning">{{ t('tenants.retryLocked') }}</p><p v-if="error" role="alert" class="notice-box danger">{{ error }}</p><div class="dialog-actions"><UiButton type="button" class="btn" :disabled="busy" @click="clearDraft">{{ t('common.cancel') }}</UiButton><UiButton class="btn btn-primary" :disabled="busy" type="submit">{{ submitted&&error?t('tenants.retrySame'):t('tenants.confirmOperation') }}</UiButton></div></form></UiDialog>
  </div>
</template>
<style scoped>
.tenant-page{gap:16px}.identity-strip{display:flex;align-items:center;gap:12px;padding:13px 16px}.identity-icon{display:grid;place-items:center;width:38px;height:38px;border-radius:10px;background:var(--color-primary-soft);color:var(--color-primary)}.identity-strip strong{font-size:var(--text-sm)}.identity-strip p{margin-top:2px;color:var(--color-text-muted);font-size:11px}.empty-state{display:flex;align-items:center;gap:16px;min-height:128px;padding:24px;color:var(--color-primary)}.empty-state.warning{color:var(--color-warning)}.empty-state p{margin-top:5px;color:var(--color-text-secondary);font-size:var(--text-sm)}.metric-card{min-height:112px;padding:18px;display:flex;flex-direction:column}.metric-card span{color:var(--color-text-secondary);font-size:12px}.metric-card strong{margin-top:8px;font-size:28px;line-height:1.15;font-variant-numeric:tabular-nums}.metric-card small{margin-top:auto;padding-top:9px;color:var(--color-text-muted)}.query-panel{display:grid;grid-template-columns:minmax(260px,1fr) 180px auto;gap:14px;align-items:end;padding:16px 18px}.input-with-icon{position:relative}.input-with-icon>.icon{position:absolute;left:11px;top:50%;transform:translateY(-50%);color:var(--color-text-muted);pointer-events:none}.input-with-icon .input{padding-left:34px}.query-actions{display:flex;gap:8px;align-items:center}.tenant-data-panel{padding:18px}.table-toolbar{margin-bottom:16px}.table-toolbar h2{font-size:16px}.table-toolbar p{margin-top:4px;color:var(--color-text-muted);font-size:11px}.result-count{color:var(--color-text-muted);font-size:12px}.tenant-name,.tenant-id{display:block}.tenant-name{font-weight:600}.tenant-id{margin-top:3px;color:var(--color-text-muted)}.row-actions{display:flex;align-items:center;gap:6px;flex-wrap:wrap}.danger-link{color:var(--color-danger)}.no-result,.table-state{padding:30px 14px!important;text-align:center!important;color:var(--color-text-muted)}.tenant-action-form{display:flex;flex-direction:column;gap:16px}.action-object{display:flex;flex-direction:column;gap:3px;padding:12px 14px;border-radius:var(--radius-md);background:var(--color-surface-soft)}.action-object span,.action-object small{color:var(--color-text-muted);font-size:11px}.dialog-actions{display:flex;justify-content:flex-end;gap:8px;padding-top:4px}@media(max-width:900px){.query-panel{grid-template-columns:1fr 160px}.query-actions{grid-column:1/-1;justify-content:flex-end}}@media(max-width:767px){.identity-strip{align-items:flex-start;flex-wrap:wrap}.metric-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.query-panel{grid-template-columns:1fr}.query-actions{grid-column:auto;justify-content:flex-start}.table-toolbar{align-items:flex-start}}@media(max-width:460px){.metric-grid{grid-template-columns:1fr}.table-actions{width:100%;justify-content:space-between}}
</style>
