// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	"context"
	commercialv1 "github.com/hvritual/biz/contracts/gen/commercial/v1"
)

// ProvisioningApplication is generated from PB and contains no business implementation.
type ProvisioningApplication interface {
	CancelProvisioningTask(context.Context, *commercialv1.MutateProvisioningTaskRequest) (*commercialv1.ProvisioningTaskDTO, error)
	ClaimProvisioningDelivery(context.Context, *commercialv1.ClaimProvisioningDeliveryRequest) (*commercialv1.ProvisioningDeliveryWorkDTO, error)
	ClaimProvisioningWork(context.Context, *commercialv1.ClaimProvisioningWorkRequest) (*commercialv1.ProvisioningWorkDTO, error)
	CompleteProvisioningDelivery(context.Context, *commercialv1.CompleteProvisioningDeliveryRequest) (*commercialv1.ProvisioningDeliveryResultDTO, error)
	FailProvisioningDelivery(context.Context, *commercialv1.CompleteProvisioningDeliveryRequest) (*commercialv1.ProvisioningDeliveryResultDTO, error)
	FinalizeProvisioningWork(context.Context, *commercialv1.FinalizeProvisioningWorkRequest) (*commercialv1.ProvisioningTaskDTO, error)
	GetProvisioningTask(context.Context, *commercialv1.ReadProvisioningTaskRequest) (*commercialv1.ProvisioningTaskDTO, error)
	ListProvisioningDeliveries(context.Context, *commercialv1.ListProvisioningDeliveriesRequest) (*commercialv1.ListProvisioningDeliveriesResponse, error)
	ListProvisioningTasks(context.Context, *commercialv1.ListProvisioningTasksRequest) (*commercialv1.ListProvisioningTasksResponse, error)
	RecordProvisioningWork(context.Context, *commercialv1.RecordProvisioningWorkRequest) (*commercialv1.ProvisioningTaskDTO, error)
	RetryProvisioningTask(context.Context, *commercialv1.MutateProvisioningTaskRequest) (*commercialv1.ProvisioningTaskDTO, error)
}
