// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	context "context"
	errors "errors"
	commercialv1 "github.com/hvritual/biz/contracts/gen/commercial/v1"
	commercialpolicy "github.com/hvritual/biz/internal/commercial/policy"
	operation "yunka.io/framework/operation"
)

type SubscriptionChangesToCommercialModuleCatalogChildCapability interface {
	ReadPlanCatalog(context.Context, *commercialv1.ListModulesRequest) (*commercialv1.ListModulesResponse, error)
}

type c9SubscriptionChangesToCommercialModuleCatalogChildCapability struct {
	application ModuleCatalogApplication
	executor    operation.Executor
}

func NewSubscriptionChangesToCommercialModuleCatalogChildCapability(application ModuleCatalogApplication, executor operation.Executor) (SubscriptionChangesToCommercialModuleCatalogChildCapability, error) {
	if application == nil {
		return nil, errors.New("contract C9 child capability: target application is required")
	}
	if executor == nil {
		return nil, errors.New("contract C9 child capability: operation executor is required")
	}
	return &c9SubscriptionChangesToCommercialModuleCatalogChildCapability{application: application, executor: executor}, nil
}

func (capability *c9SubscriptionChangesToCommercialModuleCatalogChildCapability) ReadPlanCatalog(ctx context.Context, request *commercialv1.ListModulesRequest) (*commercialv1.ListModulesResponse, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, commercialpolicy.OperationPlanModuleCatalogReadPlanCatalog(), request, capability.application.ReadPlanCatalog)
}

type SubscriptionChangesToCommercialPlanManagementChildCapability interface {
	CheckPlanEligibility(context.Context, *commercialv1.CheckPlanEligibilityRequest) (*commercialv1.PlanEligibilityDTO, error)
	GetPlanVersion(context.Context, *commercialv1.GetPlanVersionRequest) (*commercialv1.PlanVersionDTO, error)
	ListTenantChangeTargets(context.Context, *commercialv1.ListTenantChangeTargetsRequest) (*commercialv1.ListTenantChangeTargetsResponse, error)
	ReadTenantSubscriptionPlanVersion(context.Context, *commercialv1.GetPlanVersionRequest) (*commercialv1.PlanVersionDTO, error)
	ResolveTenantChangeTarget(context.Context, *commercialv1.ResolveTenantChangeTargetRequest) (*commercialv1.PlanEligibilityDTO, error)
}

type c9SubscriptionChangesToCommercialPlanManagementChildCapability struct {
	application PlanManagementApplication
	executor    operation.Executor
}

func NewSubscriptionChangesToCommercialPlanManagementChildCapability(application PlanManagementApplication, executor operation.Executor) (SubscriptionChangesToCommercialPlanManagementChildCapability, error) {
	if application == nil {
		return nil, errors.New("contract C9 child capability: target application is required")
	}
	if executor == nil {
		return nil, errors.New("contract C9 child capability: operation executor is required")
	}
	return &c9SubscriptionChangesToCommercialPlanManagementChildCapability{application: application, executor: executor}, nil
}

func (capability *c9SubscriptionChangesToCommercialPlanManagementChildCapability) CheckPlanEligibility(ctx context.Context, request *commercialv1.CheckPlanEligibilityRequest) (*commercialv1.PlanEligibilityDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, commercialpolicy.OperationPlanPlanManagementCheckPlanEligibility(), request, capability.application.CheckPlanEligibility)
}

func (capability *c9SubscriptionChangesToCommercialPlanManagementChildCapability) GetPlanVersion(ctx context.Context, request *commercialv1.GetPlanVersionRequest) (*commercialv1.PlanVersionDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, commercialpolicy.OperationPlanPlanManagementGetPlanVersion(), request, capability.application.GetPlanVersion)
}

func (capability *c9SubscriptionChangesToCommercialPlanManagementChildCapability) ListTenantChangeTargets(ctx context.Context, request *commercialv1.ListTenantChangeTargetsRequest) (*commercialv1.ListTenantChangeTargetsResponse, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, commercialpolicy.OperationPlanPlanManagementListTenantChangeTargets(), request, capability.application.ListTenantChangeTargets)
}

func (capability *c9SubscriptionChangesToCommercialPlanManagementChildCapability) ReadTenantSubscriptionPlanVersion(ctx context.Context, request *commercialv1.GetPlanVersionRequest) (*commercialv1.PlanVersionDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, commercialpolicy.OperationPlanPlanManagementReadTenantSubscriptionPlanVersion(), request, capability.application.ReadTenantSubscriptionPlanVersion)
}

func (capability *c9SubscriptionChangesToCommercialPlanManagementChildCapability) ResolveTenantChangeTarget(ctx context.Context, request *commercialv1.ResolveTenantChangeTargetRequest) (*commercialv1.PlanEligibilityDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, commercialpolicy.OperationPlanPlanManagementResolveTenantChangeTarget(), request, capability.application.ResolveTenantChangeTarget)
}

// SubscriptionChangesCapabilities exposes edge-owned C9 child-Operation wrappers for declared operation dependencies.
type SubscriptionChangesCapabilities interface {
	CommercialModuleCatalog() SubscriptionChangesToCommercialModuleCatalogChildCapability
	CommercialPlanManagement() SubscriptionChangesToCommercialPlanManagementChildCapability
}
