// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	context "context"
	errors "errors"
	commercialv1 "github.com/hvritual/biz/contracts/gen/commercial/v1"
	commercialpolicy "github.com/hvritual/biz/internal/commercial/policy"
	operation "yunka.io/framework/operation"
)

type ProvisioningToCommercialSubscriptionChangesChildCapability interface {
	CancelPreparedSubscriptionChange(context.Context, *commercialv1.PreparedSubscriptionChangeRequest) (*commercialv1.ProvisioningCompletionDTO, error)
	CompletePreparedSubscriptionChange(context.Context, *commercialv1.PreparedSubscriptionChangeRequest) (*commercialv1.ProvisioningCompletionDTO, error)
}

type c9ProvisioningToCommercialSubscriptionChangesChildCapability struct {
	application SubscriptionChangesApplication
	executor    operation.Executor
}

func NewProvisioningToCommercialSubscriptionChangesChildCapability(application SubscriptionChangesApplication, executor operation.Executor) (ProvisioningToCommercialSubscriptionChangesChildCapability, error) {
	if application == nil {
		return nil, errors.New("contract C9 child capability: target application is required")
	}
	if executor == nil {
		return nil, errors.New("contract C9 child capability: operation executor is required")
	}
	return &c9ProvisioningToCommercialSubscriptionChangesChildCapability{application: application, executor: executor}, nil
}

func (capability *c9ProvisioningToCommercialSubscriptionChangesChildCapability) CancelPreparedSubscriptionChange(ctx context.Context, request *commercialv1.PreparedSubscriptionChangeRequest) (*commercialv1.ProvisioningCompletionDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, commercialpolicy.OperationPlanSubscriptionChangesCancelPreparedSubscriptionChange(), request, capability.application.CancelPreparedSubscriptionChange)
}

func (capability *c9ProvisioningToCommercialSubscriptionChangesChildCapability) CompletePreparedSubscriptionChange(ctx context.Context, request *commercialv1.PreparedSubscriptionChangeRequest) (*commercialv1.ProvisioningCompletionDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, commercialpolicy.OperationPlanSubscriptionChangesCompletePreparedSubscriptionChange(), request, capability.application.CompletePreparedSubscriptionChange)
}

// ProvisioningCapabilities exposes edge-owned C9 child-Operation wrappers for declared operation dependencies.
type ProvisioningCapabilities interface {
	CommercialSubscriptionChanges() ProvisioningToCommercialSubscriptionChangesChildCapability
}
