// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	context "context"
	errors "errors"
	commercialv1 "github.com/hvritual/biz/contracts/gen/commercial/v1"
	commercialpolicy "github.com/hvritual/biz/internal/commercial/policy"
	operation "yunka.io/framework/operation"
)

type PlanManagementToCommercialModuleCatalogChildCapability interface {
	ReadPlanCatalog(context.Context, *commercialv1.ListModulesRequest) (*commercialv1.ListModulesResponse, error)
}

type c9PlanManagementToCommercialModuleCatalogChildCapability struct {
	application ModuleCatalogApplication
	executor    operation.Executor
}

func NewPlanManagementToCommercialModuleCatalogChildCapability(application ModuleCatalogApplication, executor operation.Executor) (PlanManagementToCommercialModuleCatalogChildCapability, error) {
	if application == nil {
		return nil, errors.New("contract C9 child capability: target application is required")
	}
	if executor == nil {
		return nil, errors.New("contract C9 child capability: operation executor is required")
	}
	return &c9PlanManagementToCommercialModuleCatalogChildCapability{application: application, executor: executor}, nil
}

func (capability *c9PlanManagementToCommercialModuleCatalogChildCapability) ReadPlanCatalog(ctx context.Context, request *commercialv1.ListModulesRequest) (*commercialv1.ListModulesResponse, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, commercialpolicy.OperationPlanModuleCatalogReadPlanCatalog(), request, capability.application.ReadPlanCatalog)
}

// PlanManagementCapabilities exposes edge-owned C9 child-Operation wrappers for declared operation dependencies.
type PlanManagementCapabilities interface {
	CommercialModuleCatalog() PlanManagementToCommercialModuleCatalogChildCapability
}
