// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	context "context"
	errors "errors"
	accessv1 "github.com/hvritual/biz/contracts/gen/access/v1"
	commercialv1 "github.com/hvritual/biz/contracts/gen/commercial/v1"
	accesspolicy "github.com/hvritual/biz/internal/access/policy"
	commercialpolicy "github.com/hvritual/biz/internal/commercial/policy"
	operation "yunka.io/framework/operation"
)

type EntitlementManagementToAccessTenantLifecycleChildCapability interface {
	GetTenant(context.Context, *accessv1.GetTenantRequest) (*accessv1.TenantDTO, error)
}

// EntitlementManagementToAccessTenantLifecycleTargetApplication is the consumer-edge-owned view of the target Application.
type EntitlementManagementToAccessTenantLifecycleTargetApplication interface {
	GetTenant(context.Context, *accessv1.GetTenantRequest) (*accessv1.TenantDTO, error)
}

type c9EntitlementManagementToAccessTenantLifecycleChildCapability struct {
	application EntitlementManagementToAccessTenantLifecycleTargetApplication
	executor    operation.Executor
}

func NewEntitlementManagementToAccessTenantLifecycleChildCapability(application EntitlementManagementToAccessTenantLifecycleTargetApplication, executor operation.Executor) (EntitlementManagementToAccessTenantLifecycleChildCapability, error) {
	if application == nil {
		return nil, errors.New("contract C9 child capability: target application is required")
	}
	if executor == nil {
		return nil, errors.New("contract C9 child capability: operation executor is required")
	}
	return &c9EntitlementManagementToAccessTenantLifecycleChildCapability{application: application, executor: executor}, nil
}

func (capability *c9EntitlementManagementToAccessTenantLifecycleChildCapability) GetTenant(ctx context.Context, request *accessv1.GetTenantRequest) (*accessv1.TenantDTO, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, accesspolicy.OperationPlanTenantLifecycleGetTenant(), request, capability.application.GetTenant)
}

type EntitlementManagementToCommercialModuleCatalogChildCapability interface {
	ReadEntitlementCatalog(context.Context, *commercialv1.ListModulesRequest) (*commercialv1.ListModulesResponse, error)
}

type c9EntitlementManagementToCommercialModuleCatalogChildCapability struct {
	application ModuleCatalogApplication
	executor    operation.Executor
}

func NewEntitlementManagementToCommercialModuleCatalogChildCapability(application ModuleCatalogApplication, executor operation.Executor) (EntitlementManagementToCommercialModuleCatalogChildCapability, error) {
	if application == nil {
		return nil, errors.New("contract C9 child capability: target application is required")
	}
	if executor == nil {
		return nil, errors.New("contract C9 child capability: operation executor is required")
	}
	return &c9EntitlementManagementToCommercialModuleCatalogChildCapability{application: application, executor: executor}, nil
}

func (capability *c9EntitlementManagementToCommercialModuleCatalogChildCapability) ReadEntitlementCatalog(ctx context.Context, request *commercialv1.ListModulesRequest) (*commercialv1.ListModulesResponse, error) {
	return operation.ExecuteChildTyped(ctx, capability.executor, commercialpolicy.OperationPlanModuleCatalogReadEntitlementCatalog(), request, capability.application.ReadEntitlementCatalog)
}

// EntitlementManagementCapabilities exposes edge-owned C9 child-Operation wrappers for declared operation dependencies.
type EntitlementManagementCapabilities interface {
	AccessTenantLifecycle() EntitlementManagementToAccessTenantLifecycleChildCapability
	CommercialModuleCatalog() EntitlementManagementToCommercialModuleCatalogChildCapability
}
