// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	"context"
	commercialv1 "github.com/hvritual/biz/contracts/gen/commercial/v1"
)

// ModuleCatalogApplication is generated from PB and contains no business implementation.
type ModuleCatalogApplication interface {
	CreateModule(context.Context, *commercialv1.CreateModuleRequest) (*commercialv1.ModuleDTO, error)
	DeleteModule(context.Context, *commercialv1.DeleteModuleRequest) (*commercialv1.DeleteModuleResponse, error)
	GetModule(context.Context, *commercialv1.GetModuleRequest) (*commercialv1.ModuleDTO, error)
	ListModules(context.Context, *commercialv1.ListModulesRequest) (*commercialv1.ListModulesResponse, error)
	SetModuleSalesStatus(context.Context, *commercialv1.SetModuleSalesStatusRequest) (*commercialv1.ModuleDTO, error)
	SetModuleTechnicalStatus(context.Context, *commercialv1.SetModuleTechnicalStatusRequest) (*commercialv1.ModuleDTO, error)
	UpdateModule(context.Context, *commercialv1.UpdateModuleRequest) (*commercialv1.ModuleDTO, error)
}
