// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	"context"
	commercialv1 "github.com/hvritual/biz/contracts/gen/commercial/v1"
)

// EntitlementManagementApplication is generated from PB and contains no business implementation.
type EntitlementManagementApplication interface {
	CreateEntitlementOverride(context.Context, *commercialv1.CreateEntitlementOverrideRequest) (*commercialv1.EntitlementOverrideReceipt, error)
	ExplainEntitlements(context.Context, *commercialv1.ExplainEntitlementsRequest) (*commercialv1.EntitlementView, error)
	GetMyEntitlements(context.Context, *commercialv1.GetMyEntitlementsRequest) (*commercialv1.EntitlementView, error)
	ListEntitlementOverrides(context.Context, *commercialv1.ListEntitlementOverridesRequest) (*commercialv1.ListEntitlementOverridesResponse, error)
	RevokeEntitlementOverride(context.Context, *commercialv1.RevokeEntitlementOverrideRequest) (*commercialv1.EntitlementOverrideReceipt, error)
}
