import type { ActionDefinition } from '@/types/customer'
import type { ActionId } from './commands'
import {
  field as f,
  ownerField,
  reasonField,
  actionFields,
  followupFields,
  confirmField,
  customerField,
} from './formFields'
export const customerForms: Partial<Record<ActionId, ActionDefinition>> = {
  'create-customer': {
    title: '新建客户',
    description: '客户是长期经营对象；建档不等于签约或授权。',
    primary: '创建客户',
    drawer: true,
    fields: [
      f('name', '客户名称'),
      f('category', '客户类型', 'select', true, [
        '连锁酒店',
        '写字楼 / 园区',
        '企业办公',
        '公寓',
        '商业场馆',
        '连锁零售',
      ]),
      f('mode', '经营模式', 'select', true, ['设备租赁 + 服务', '投放运营', '试用合作']),
      ownerField,
      f('lifecycle', '客户生命周期', 'select', true, ['潜在客户', '试用中']),
      f('area', '区域'),
      f('tenantLink', '关联客户方租户', 'text', false, undefined, '关联租户不会自动共享内部客户档案。'),
      f('title', '首次跟进事项', 'text', false),
      ...actionFields.map((x) => ({ ...x, required: false })),
    ],
    note: '重复检查在保存时再次执行。同一客户的不同合同与点位在客户工作区管理，不重复建档。',
  },
  'edit-customer': {
    title: '编辑客户资料',
    description: '修改档案，不直接改变合同与投放关系。',
    primary: '保存资料',
    drawer: true,
    fields: [
      f('name', '客户名称'),
      f('category', '客户类型', 'select', true, [
        '连锁酒店',
        '写字楼 / 园区',
        '企业办公',
        '公寓',
        '商业场馆',
        '连锁零售',
      ]),
      f('mode', '经营模式'),
      ownerField,
      f('area', '区域'),
    ],
    note: '使用记录版本校验，发生并发更新时保留草稿。',
  },
  contact: {
    title: '新增联系人',
    description: '记录客户侧联系人及协作职责。',
    primary: '保存联系人',
    drawer: true,
    fields: [
      f('name', '姓名'),
      f('role', '职务'),
      f('phone', '联系方式'),
      f('email', '邮箱'),
      f('responsibility', '协作职责', 'select', true, ['采购决策', '日常运营', '现场验收', '财务对账']),
    ],
    note: '保存联系人不会自动创建登录账号；共享范围需独立授权。',
  },
  handover: {
    title: '移交客户与事项',
    description: '客户关系责任与事项执行责任分别处理。',
    primary: '确认移交',
    drawer: true,
    fields: [
      ownerField,
      reasonField,
      f('includeWork', '同步移交原客户负责人名下的未结束事项', 'checkbox', false),
      confirmField,
    ],
    note: '仅处理你有权编辑的事项；其他责任人的事项、已结束事项及历史日志不改写。',
  },
  visit: {
    title: '记录回访与客户承诺',
    description: '沟通记录可以结束，客户承诺必须由具体事项继续跟进。',
    primary: '保存回访并安排后续',
    drawer: true,
    fields: [
      f('channel', '回访方式', 'select', true, ['电话回访', '线上会议', '现场拜访']),
      f('contact', '客户联系人'),
      f('actualAt', '实际联系时间', 'datetime-local'),
      f('feedback', '客户反馈与回访结论', 'textarea'),
      f('promise', '向客户承诺的下一步', 'textarea', false),
      ...followupFields,
      f('closeVisit', '保存后结束本次回访事项', 'checkbox', false),
    ],
    note: '有明确承诺时必须创建后续事项。结束回访不会自动结束后续工作。',
  },
  'create-plan': {
    title: '新建经营计划',
    description: '为一个客户组织阶段目标、里程碑和协作事项。',
    primary: '创建并进入计划',
    drawer: true,
    fields: [
      f('title', '计划名称'),
      customerField,
      ownerField,
      f('start', '开始日期', 'date'),
      f('end', '结束日期', 'date'),
      f('target', '目标名称'),
      f('targetValue', '目标值', 'number'),
      f('unit', '目标单位', 'select', true, ['项', '份', '个', '台']),
      f('description', '计划说明', 'textarea', false),
    ],
    note: '计划进度与目标达成分别核算；不得用任务关闭率代替经营结果。',
  },
  milestone: {
    title: '新增里程碑',
    description: '关联既有事项，不复制工作记录。',
    primary: '保存里程碑',
    drawer: true,
    fields: [
      f('title', '里程碑名称'),
      f('date', '计划完成日期', 'date'),
      f('workId', '关联事项', 'select', true, ['CS-102', 'CS-103', 'CS-104', 'CS-107', 'CS-108']),
    ],
  },
  recap: {
    title: '经营计划结案与复盘',
    description: '计划可以部分达成；未完成事项需要明确去向。',
    primary: '保存复盘并结案',
    drawer: true,
    fields: [
      f('result', '目标达成结果', 'select', true, ['全部达成', '部分达成', '未达成']),
      reasonField,
      f('disposition', '未结束事项继续由原负责人推进，不随计划结案自动关闭', 'checkbox'),
      ...followupFields,
    ],
    note: '原始目标、实际结果、未达成原因和后续改进都保留在计划记录中。',
  },
  triage: {
    title: '风险研判与行动',
    description: '先核对证据与数据完整性，再决定是否创建工作。',
    primary: '保存研判',
    drawer: true,
    fields: [
      f('result', '研判结果', 'select', true, ['关联已有事项', '创建经营检查事项', '持续观察', '排除误报']),
      reasonField,
      f('workId', '已有事项', 'select', false, ['CS-102', 'CS-103', 'CS-104', 'CS-105']),
      ...followupFields,
    ],
    note: '出杯量下降不直接等于客户流失；同一风险优先复用已有事项。',
  },
  archive: {
    title: '客户归档前检查',
    description: '仅在所有业务处置完成后允许归档。',
    primary: '确认归档',
    fields: [reasonField, confirmField],
    note: '有效合同、有效投放、未结应收、未结束事项任一存在时阻止归档。历史数据不删除。',
  },
  restore: {
    title: '恢复已归档客户',
    description: '恢复客户档案入口，不重置历史生命周期。',
    primary: '恢复客户',
    fields: [reasonField],
  },
  'save-view': {
    title: '保存筛选与显示视图',
    description: '筛选控制记录集合，显示设置只影响呈现。',
    primary: '保存视图',
    drawer: true,
    fields: [
      f('name', '视图名称'),
      f('search', '关键词', 'text', false),
      f('kind', '事项类型', 'select', false, [
        '',
        'visit',
        'delivery',
        'service',
        'payment',
        'renewal',
        'return',
        'improvement',
      ]),
      f('owner', '负责人', 'select', false, ['', '张敏', '李川', '陈晓', '王宁']),
      f('density', '显示密度', 'select', true, ['标准', '紧凑']),
      f('columns', '显示字段', 'text', true, undefined, '使用逗号分隔：客户,负责人,期限,下一步'),
    ],
    note: '取消不会应用草稿条件。视图按当前租户及预览用户隔离。',
  },
}
