import type { CustomerSnapshot, Customer, WorkItem, WorkKind, SourceRecord } from '@/types/customer'
export const operators = ['张敏', '李川', '陈晓', '王宁']
export const workKindNames: Record<WorkKind, string> = {
  visit: '客户回访',
  delivery: '投放交付',
  service: '服务协调',
  payment: '回款跟进',
  renewal: '续约推进',
  return: '退租回收',
  improvement: '经营改进',
}
export const workflows: Record<WorkKind, string[]> = {
  visit: ['安排回访', '联系客户', '记录结果', '后续动作', '已结束'],
  delivery: ['确认需求', '排期与现场准备', '安装与试运行', '客户验收', '已结束'],
  service: ['待受理', '分派处理', '运维执行', '恢复验证', '已结束'],
  payment: ['关联应收', '回款沟通', '财务核销', '结果核验', '已结束'],
  renewal: ['续约评估', '方案准备', '客户沟通', '合同办理', '已结束'],
  return: ['确认范围', '回收排期', '现场回收', '结算与终止', '已结束'],
  improvement: ['目标确认', '方案准备', '执行跟进', '成果验收', '已结束'],
}
const customers: Customer[] = [
  ['CUS-0186', '星悦酒店集团', '连锁酒店', '合作中', '张敏', '12', '18', '服务风险'],
  ['CUS-0185', '澜湾商务园', '写字楼 / 园区', '合作中', '李川', '8', '12', '回款风险'],
  ['CUS-0183', '云栖会展中心', '商业场馆', '试用中', '陈晓', '3', '4', '待评估'],
  ['CUS-0181', '江南办公空间', '企业办公', '合作中', '王宁', '6', '8', '无已识别风险'],
  ['CUS-0179', '青禾连锁公寓', '公寓', '合作中', '张敏', '7', '9', '到期风险'],
  ['CUS-0176', '东岸创新中心', '产业园', '合作终止', '李川', '0', '0', '历史保留'],
  ['CUS-0173', '观澜科技园', '写字楼 / 园区', '合作中', '王宁', '5', '6', '无已识别风险'],
  ['CUS-0171', '松庭书店', '连锁零售', '潜在客户', '陈晓', '0', '0', '待评估'],
].map(([id, name, category, lifecycle, owner, sites, devices, risk]) => ({
  id: id!,
  name: name!,
  category: category!,
  lifecycle: lifecycle as Customer['lifecycle'],
  owner: owner!,
  sites: Number(sites),
  devices: Number(devices),
  risk: risk!,
  mode: '设备租赁 + 服务',
  area: '华东 · 上海 / 苏州 / 杭州',
  tenantLink: id === 'CUS-0186' ? 'TN-0471' : '',
  version: 1,
  archived: false,
  lastContact: '2026-09-09 14:10',
  nextContact: '2026-09-12 10:00',
}))
function work(
  id: string,
  title: string,
  kind: WorkKind,
  owner: string,
  status: WorkItem['status'],
  stage: number,
  deadline: string,
  nextAction: string,
): WorkItem {
  return {
    id,
    title,
    kind,
    owner,
    status,
    stage,
    deadline,
    customerId: 'CUS-0186',
    collaborators: ['李川', '陈晓'].filter((x) => x !== owner),
    priority: '高',
    nextAction,
    nextAt: `${deadline < '2026-09-12' ? deadline : '2026-09-12'}T10:00`,
    description:
      '围绕星悦酒店集团的租赁与投放关系推进工作。所有业务结论须关联来源记录，不以事项状态替代真实结果。',
    criteria: ['明确本次工作范围与责任人', '关联有效的业务证据', '记录客户反馈与下一步动作'],
    version: 1,
    workflowVersion: 3,
    resolution: '',
    cycle: 1,
    writable: true,
    dependencies: [],
    evidenceIds: [],
    businessKey: `CUS-0186:${id}`,
  }
}
function source(
  id: string,
  kind: SourceRecord['kind'],
  title: string,
  state: string,
  facts: SourceRecord['facts'],
  verified = true,
): SourceRecord {
  return { id, kind, title, state, facts, verified, customerId: 'CUS-0186' }
}
export function createCustomerSeed(tenant: string): CustomerSnapshot {
  const tasks: WorkItem[] = [
    work('CS-102', '年度合同续约', 'renewal', '张敏', '处理中', 2, '2026-09-25', '确认新增点位与服务条款'),
    work(
      'CS-103',
      '大堂设备恢复验证',
      'service',
      '陈晓',
      '待验收',
      3,
      '2026-09-10',
      '复核出杯运行数据并回访客户',
    ),
    work(
      'CS-104',
      '苏州三点位投放交付',
      'delivery',
      '李川',
      '待验收',
      3,
      '2026-09-12',
      '苏州高铁店整改后重新验收',
    ),
    work('CS-105', '9 月应收回款跟进', 'payment', '王宁', '等待客户', 2, '2026-09-15', '核对尾款 3,000 元'),
    work(
      'CS-106',
      '虹桥点位退租回收',
      'return',
      '李川',
      '处理中',
      3,
      '2026-09-18',
      '确认回收、结算与投放终止范围',
    ),
    work('CS-107', '季度客户回访', 'visit', '张敏', '处理中', 2, '2026-09-12', '完成电话回访并记录客户承诺'),
    work('CS-108', '苏州点位扩展方案', 'improvement', '李川', '待开始', 0, '2026-09-20', '确认现场安装条件'),
    work(
      'CS-109',
      '月度服务质量复盘',
      'improvement',
      '陈晓',
      '处理中',
      2,
      '2026-09-22',
      '整理恢复时效与客户反馈',
    ),
    work('CS-110', '咖啡体验回访', 'visit', '王宁', '已结束', 4, '2026-09-08', '已回访，暂无后续事项'),
    work('CS-111', '企业点位服务跟进', 'service', '王宁', '处理中', 2, '2026-09-16', '协调使用培训'),
    work('CS-112', '连锁公寓续约评估', 'renewal', '张敏', '等待客户', 2, '2026-09-21', '等待采购负责人确认'),
    work('CS-113', '园区回款核对', 'payment', '李川', '待开始', 0, '2026-09-17', '核对应收批次'),
  ]
  tasks[0]!.dependencies = ['CS-103']
  tasks[0]!.businessKey = `${tenant}:HT-2026-018:2026-09`
  tasks[0]!.evidenceIds = ['HT-2026-018']
  tasks[0]!.planId = 'PL-009'
  tasks[1]!.evidenceIds = ['WO-078']
  tasks[2]!.evidenceIds = ['HT-2026-041', 'INST-078']
  tasks[2]!.planId = 'PL-009'
  tasks[3]!.evidenceIds = ['AR-0901']
  tasks[4]!.evidenceIds = ['REC-026']
  tasks[8]!.resolution = '成功'
  tasks[9]!.customerId = 'CUS-0181'
  tasks[9]!.writable = false
  tasks[10]!.customerId = 'CUS-0179'
  tasks[11]!.customerId = 'CUS-0185'
  const sources = [
    source('HT-2026-018', 'contract', '年度设备租赁合同', '生效中', {
      start: '2026-01-01',
      end: '2026-09-30',
      amount: 286000,
      sites: 12,
      renewal: false,
    }),
    source('HT-2026-041', 'contract', '苏州点位租赁合同', '生效中', {
      start: '2026-09-01',
      end: '2027-08-31',
      amount: 36000,
      sites: 3,
    }),
    source('HT-2026-058', 'contract', '年度续约合同', '已生效', {
      start: '2026-10-01',
      end: '2027-09-30',
      amount: 298000,
      sites: 12,
      renewal: true,
      original: 'HT-2026-018',
    }),
    source(
      'HT-DRAFT-01',
      'contract',
      '续约方案草稿',
      '待签署',
      { renewal: true, original: 'HT-2026-018' },
      false,
    ),
    source('INST-078', 'placement', '安装执行记录', '已核验', { active: true, sites: 3 }),
    source('ACC-041', 'acceptance', '首轮逐点验收记录', '部分通过', {
      passed: 2,
      total: 3,
      allPassed: false,
    }),
    source('ACC-042', 'acceptance', '整改后复验记录', '全部通过', {
      passed: 3,
      total: 3,
      allPassed: true,
      scope: 'PD-041 / PD-042 / PD-043',
    }),
    source('PD-041-043', 'placement', '三点位有效投放关系', '生效中', { active: true, sites: 3 }),
    source('WO-078', 'service', '大堂咖啡机维修工单', '处理完成', { workComplete: true, recovered: false }),
    source('RUN-103', 'recovery', '修复后连续运行验证', '验证通过', {
      recovered: true,
      onlineMinutes: 120,
      validCups: 28,
    }),
    source('CONF-103', 'confirmation', '客户确认设备恢复', '已确认', { confirmed: true, workId: 'CS-103' }),
    source('AR-0901', 'receivable', '9 月租赁应收', '部分核销', {
      due: 12000,
      paid: 9000,
      balance: 3000,
      currency: 'CNY',
    }),
    source('AR-0901-F', 'receivable', '9 月应收全额核销回读', '已核销', {
      due: 12000,
      paid: 12000,
      balance: 0,
      currency: 'CNY',
      original: 'AR-0901',
    }),
    source('REC-026', 'recovery', '虹桥点位设备回收', '已回收', {
      returned: true,
      count: 2,
      scope: '虹桥点位 · CL-HQ-026 / CL-HQ-027',
    }),
    source('SET-026', 'settlement', '退租结算核对', '已结清', { settled: true, balance: 0 }),
    source('TERM-026', 'termination', '虹桥投放关系终止回读', '已终止', {
      terminated: true,
      end: '2026-09-18 18:00',
      history: true,
    }),
  ]
  const scopes: Record<string, string> = {
    'ACC-041': 'CS-104',
    'ACC-042': 'CS-104',
    'INST-078': 'CS-104',
    'PD-041-043': 'CS-104',
    'WO-078': 'CS-103',
    'RUN-103': 'CS-103',
    'CONF-103': 'CS-103',
    'AR-0901': 'CS-105',
    'AR-0901-F': 'CS-105',
    'REC-026': 'CS-106',
    'SET-026': 'CS-106',
    'TERM-026': 'CS-106',
  }
  sources.forEach((record) => {
    if (scopes[record.id]) record.facts.workId = scopes[record.id]!
  })
  const state: CustomerSnapshot = {
    schema: 1,
    tenant,
    revision: 1,
    customers: structuredClone(customers),
    contacts: [
      {
        id: 'CT-01',
        customerId: 'CUS-0186',
        name: '周岚',
        role: '采购负责人',
        phone: '138****6021',
        email: 'buyer@example.com',
        responsibility: '合同与商务确认',
        authorized: true,
      },
      {
        id: 'CT-02',
        customerId: 'CUS-0186',
        name: '陆晨',
        role: '运营负责人',
        phone: '139****4832',
        email: 'ops@example.com',
        responsibility: '点位投放与验收',
        authorized: true,
      },
      {
        id: 'CT-03',
        customerId: 'CUS-0186',
        name: '陈安',
        role: '门店联系人',
        phone: '137****9170',
        email: 'site@example.com',
        responsibility: '现场配合与反馈',
        authorized: false,
      },
    ],
    work: tasks,
    sources,
    sites: [
      {
        id: 'SITE-041',
        customerId: 'CUS-0186',
        workId: 'CS-104',
        name: '苏州园区大堂',
        device: 'CL-SZ-021',
        placement: 'PD-041',
        owner: '李川',
        trial: true,
        training: true,
        accepted: true,
      },
      {
        id: 'SITE-042',
        customerId: 'CUS-0186',
        workId: 'CS-104',
        name: '苏州新区店',
        device: 'CL-SZ-022',
        placement: 'PD-042',
        owner: '李川',
        trial: true,
        training: true,
        accepted: true,
      },
      {
        id: 'SITE-043',
        customerId: 'CUS-0186',
        workId: 'CS-104',
        name: '苏州高铁店',
        device: 'CL-SZ-023',
        placement: 'PD-043',
        owner: '陈晓',
        trial: false,
        training: true,
        accepted: false,
      },
    ],
    plans: [
      {
        id: 'PL-009',
        customerId: 'CUS-0186',
        title: 'Q3 星悦酒店续约与扩点计划',
        owner: '张敏',
        start: '2026-07-01',
        end: '2026-09-30',
        state: '进行中',
        conclusion: '',
        version: 1,
        targets: [
          { title: '新增投放点位', baseline: 0, actual: 2, target: 3, unit: '个', source: '逐点投放验收' },
          { title: '到期合同续约', baseline: 0, actual: 0, target: 1, unit: '份', source: '已生效续约合同' },
          {
            title: '客户服务恢复',
            baseline: 0,
            actual: 0,
            target: 1,
            unit: '项',
            source: '运行验证与客户确认',
          },
        ],
        milestones: [
          { title: '需求与范围确认', date: '07-15', status: '已完成', workIds: ['CS-107'] },
          { title: '方案与商务确认', date: '08-10', status: '已完成', workIds: ['CS-102'] },
          { title: '交付与恢复验证', date: '09-12', status: '进行中', workIds: ['CS-103', 'CS-104'] },
          { title: '续约与计划复盘', date: '09-30', status: '待开始', workIds: ['CS-102'] },
        ],
      },
    ],
    rules: [
      {
        id: 'RULE-01',
        name: '合同到期前 60 天创建续约事项',
        trigger: '合同到期',
        days: 60,
        scope: '合作中客户',
        owner: '客户负责人',
        enabled: true,
        version: 3,
        tested: true,
      },
      {
        id: 'RULE-02',
        name: '服务事项超时升级提醒',
        trigger: '服务超时',
        days: 1,
        scope: '未恢复服务',
        owner: '事项负责人',
        enabled: true,
        version: 2,
        tested: true,
      },
      {
        id: 'RULE-03',
        name: '超过维护周期创建回访',
        trigger: '长期未联系',
        days: 30,
        scope: '合作中客户',
        owner: '客户负责人',
        enabled: false,
        version: 1,
        tested: false,
      },
    ],
    executions: [
      {
        id: 'RUN-240',
        ruleId: 'RULE-01',
        businessKey: `${tenant}:HT-2026-018:2026-09`,
        customerId: 'CUS-0186',
        state: '部分失败',
        workId: 'CS-102',
        failedStep: '通知客户负责人',
        time: '2026-09-10 09:20',
        history: ['09:20 业务键校验通过', '09:20 已关联事项 CS-102', '09:20 站内通知步骤失败'],
      },
      {
        id: 'RUN-239',
        ruleId: 'RULE-02',
        businessKey: `${tenant}:CS-103:sla`,
        customerId: 'CUS-0186',
        state: '成功',
        workId: 'CS-103',
        failedStep: '',
        time: '2026-09-10 09:05',
        history: ['09:05 服务未恢复', '09:05 升级提醒已记录（示例）'],
      },
    ],
    grants: [
      {
        id: 'SH-031',
        customerId: 'CUS-0186',
        contactId: 'CT-02',
        workId: 'CS-104',
        fields: ['事项标题', '交付范围', '处理进度', '共享附件'],
        attachments: ['INST-078', 'ACC-041'],
        expires: '2026-10-10',
        revoked: false,
      },
    ],
    notifications: [
      {
        id: 'NT-01',
        title: 'CS-103 服务恢复待验证',
        description: '维修工单已处理，仍需运行证据与客户确认。',
        workId: 'CS-103',
        read: false,
        category: '待决策',
      },
      {
        id: 'NT-02',
        title: 'CS-104 投放验收待整改',
        description: '苏州高铁店试运行未通过，需明确整改期限。',
        workId: 'CS-104',
        read: false,
        category: '验收提醒',
      },
      {
        id: 'NT-03',
        title: 'CS-102 续约推进提醒',
        description: '合同到期前完成条款确认，关联服务问题尚未解除。',
        workId: 'CS-102',
        read: false,
        category: '到期提醒',
      },
    ],
    activities: [
      {
        id: 'ACT-01',
        target: 'CUS-0186',
        action: '更新客户资料',
        actor: '张敏',
        time: '2026-09-10 09:30',
        detail: '补充客户信息，保留客户编号和历史业务关联。',
        visibility: 'internal',
      },
      {
        id: 'ACT-02',
        target: 'CS-102',
        action: '客户沟通',
        actor: '周岚',
        time: '2026-09-09 14:10',
        detail: '确认下次续约沟通时间；优先解决已有服务问题。',
        visibility: 'shared',
      },
      {
        id: 'ACT-03',
        target: 'SH-031',
        action: '共享范围更新',
        actor: '张敏',
        time: '2026-09-08 17:30',
        detail: '交付资料仅向运营负责人共享。',
        visibility: 'internal',
      },
    ],
    receipts: [],
    views: [],
    workflowVersion: 3,
    sla: {
      responseMinutes: 30,
      recoveryHours: 4,
      calendar: '工作日 09:00–18:00',
      pause: '需人工批准后暂停恢复计时',
    },
    drafts: {},
  }
  if (tenant !== 'shanghai') {
    state.customers = state.customers.map((c) => ({
      ...c,
      name: c.id === 'CUS-0186' ? '杭州星澜酒店' : `杭州 · ${c.name}`,
      tenantLink: c.id === 'CUS-0186' ? 'TN-HZ-21' : '',
      owner: '王宁',
    }))
    state.work = state.work.map((w) => ({
      ...w,
      owner: '王宁',
      description: '当前为杭州企业独立示例，不共享上海企业的编辑、授权、回执或草稿。',
    }))
  }
  return state
}
