import type { ActionDefinition } from '@/types/customer'
import type { ActionId } from './commands'
import {
  field as f,
  ownerField,
  reasonField,
  actionFields,
  followupFields,
  confirmField,
  customerField,
} from './formFields'
export const workForms: Partial<Record<ActionId, ActionDefinition>> = {
  'create-work': {
    title: '新建客户事项',
    description: '为客户明确一件有责任人、有期限、有完成依据的工作。',
    primary: '创建事项',
    drawer: true,
    fields: [
      f('kind', '事项类型', 'select', true, [
        'visit',
        'delivery',
        'service',
        'payment',
        'renewal',
        'return',
        'improvement',
      ]),
      f('title', '事项标题'),
      customerField,
      ownerField,
      f('description', '事项说明', 'textarea'),
      f('criteria', '成功标准', 'textarea'),
      ...actionFields,
    ],
    note: '合同、应收与运维工单仍由专业业务模块维护；此处管理推进与协作。',
  },
  assign: {
    title: '批量分配与范围确认',
    description: '逐项校验权限与对象状态，保留跳过原因。',
    primary: '确认分配',
    drawer: true,
    fields: [ownerField, reasonField],
    note: '成功项与失败项分别显示回执，不以一个“成功”提示掩盖部分失败。',
  },
  reschedule: {
    title: '调整行动安排',
    description: '下次行动时间、事项截止时间、服务时限是三个独立的时钟。',
    primary: '保存改期',
    drawer: true,
    fields: [...actionFields, reasonField],
    note: '本次改期不自动暂停服务计时，也不修改合同到期日。',
  },
  dependency: {
    title: '关联依赖与阻塞',
    description: '明确卡在哪里，谁在处理，何时继续。',
    primary: '保存依赖',
    drawer: true,
    fields: [
      f('workId', '依赖事项', 'select', true, ['CS-102', 'CS-103', 'CS-104', 'CS-105', 'CS-106', 'CS-108']),
      reasonField,
      f('nextAction', '解阻后的下一步', 'textarea'),
    ],
    note: '禁止自身依赖及依赖环。事项引用同一条记录，不重复创建服务工单。',
  },
  transition: {
    title: '流转事项',
    description: '目标状态必须符合事项当前权限与业务规则。',
    primary: '确认流转',
    drawer: true,
    fields: [
      f('status', '目标状态', 'select', true, ['待开始', '处理中', '等待客户', '待验收']),
      f('nextAction', '下一步行动', 'textarea'),
      f('nextAt', '下次行动时间', 'datetime-local'),
      f('reason', '流转说明', 'textarea', false),
    ],
    note: '“成功关闭”不在普通流转中，必须经过验收并关联有效业务来源。',
  },
  reject: {
    title: '验收未通过 · 退回整改',
    description: '保留已通过部分，仅为未通过范围安排整改。',
    primary: '退回处理并安排复验',
    drawer: true,
    fields: [
      reasonField,
      ownerField,
      ...actionFields,
      f('shared', '将验收结论设为客户可见', 'checkbox', false),
      f('followup', '另建独立整改子事项', 'checkbox', false),
    ],
    warning: '本次操作不回滚已通过点位，不删除原工单或验收证据。',
  },
  accept: {
    title: '事项验收与成功关闭',
    description: '使用同客户下已核验的业务记录确认结果。',
    primary: '验收并成功关闭',
    fields: [
      f('evidence', '业务来源', 'text', false),
      f('reason', '验收依据与结论', 'textarea'),
      confirmField,
    ],
    note: '文件上传、口头确认和任务关闭不能替代合同生效、财务核销或设备恢复。',
  },
  reopen: {
    title: '重新打开事项',
    description: '开始新一轮处理，同时保留原结束记录和验收证据。',
    primary: '重新打开并分配',
    fields: [reasonField, ownerField, ...actionFields],
    note: '重新打开不是删除历史成功记录。新的处理轮次独立记录责任与期限。',
  },
  nonrenewal: {
    title: '记录未续约结果',
    description: '记录未达成原因与后续处置，不将事项关闭计为续约成功。',
    primary: '以未达成结束',
    drawer: true,
    fields: [
      f('reason', '未续约原因', 'textarea'),
      f('disposition', '已确认当前合同、点位与应收的后续处置', 'checkbox'),
      ...followupFields,
    ],
    warning: '单份合同未续约不意味着整个客户流失；其他有效合同和投放继续保留。',
  },
  comment: {
    title: '添加评论与协作记录',
    description: '区分内部讨论与明确授权的客户可见内容。',
    primary: '发布评论',
    fields: [
      f('comment', '评论内容', 'textarea'),
      f('shared', '此条评论可由已授权客户查看', 'checkbox', false),
    ],
  },
  subtask: {
    title: '新增子事项',
    description: '有独立负责人和期限的工作应有独立记录。',
    primary: '创建并建立依赖',
    drawer: true,
    fields: [f('title', '子事项标题'), ownerField, ...actionFields, f('criteria', '完成依据', 'textarea')],
  },
  'link-source': {
    title: '关联业务来源',
    description: '只关联已核验记录，不直接修改来源模块的状态。',
    primary: '确认关联',
    fields: [f('sourceId', '业务记录', 'select', true, [])],
    note: '来源记录必须属于当前事项的客户。缺少有效来源时禁止伪造成功。',
  },
}
