CREATE TABLE IF NOT EXISTS biz_notification_events (
  event_id VARBINARY(160) NOT NULL,
  tenant_id VARBINARY(64) NOT NULL,
  group_id VARBINARY(64) NOT NULL,
  type_code VARCHAR(64) NOT NULL,
  level VARCHAR(16) NOT NULL,
  trace_id VARBINARY(160) NOT NULL,
  reference_kind VARCHAR(64) NOT NULL,
  reference_id VARBINARY(160) NOT NULL,
  payload_hash VARCHAR(64) NOT NULL,
  state VARCHAR(24) NOT NULL,
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  lease_owner VARCHAR(96) NOT NULL DEFAULT '',
  lease_token BIGINT UNSIGNED NOT NULL DEFAULT 0,
  lease_until DATETIME(6) NULL,
  failure_code VARCHAR(64) NOT NULL DEFAULT '',
  occurred_at DATETIME(6) NOT NULL,
  routed_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (event_id),
  KEY idx_notification_event_tenant (tenant_id),
  KEY idx_notification_event_group (group_id),
  KEY idx_notification_event_state (state),
  KEY idx_notification_event_lease (lease_until),
  KEY idx_notification_event_occurred (occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS biz_notification_in_app (
  message_id VARCHAR(64) NOT NULL,
  tenant_id VARBINARY(64) NOT NULL,
  user_id VARBINARY(64) NOT NULL,
  event_id VARBINARY(160) NOT NULL,
  configuration_id VARBINARY(64) NOT NULL,
  configuration_version BIGINT UNSIGNED NOT NULL,
  group_id VARBINARY(64) NOT NULL,
  type_code VARCHAR(64) NOT NULL,
  level VARCHAR(16) NOT NULL,
  trace_id VARBINARY(160) NOT NULL,
  reference_kind VARCHAR(64) NOT NULL,
  reference_id VARBINARY(160) NOT NULL,
  created_at DATETIME(6) NOT NULL,
  read_at DATETIME(6) NULL,
  PRIMARY KEY (message_id),
  UNIQUE KEY uq_notification_inapp (tenant_id,user_id,event_id),
  KEY idx_notification_inapp_tenant (tenant_id),
  KEY idx_notification_inapp_user (user_id),
  KEY idx_notification_inapp_created (created_at),
  KEY idx_notification_inapp_read (read_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS biz_notification_external_tasks (
  task_id VARCHAR(64) NOT NULL,
  tenant_id VARBINARY(64) NOT NULL,
  user_id VARBINARY(64) NOT NULL,
  event_id VARBINARY(160) NOT NULL,
  channel VARCHAR(16) NOT NULL,
  configuration_id VARBINARY(64) NOT NULL,
  configuration_version BIGINT UNSIGNED NOT NULL,
  group_id VARBINARY(64) NOT NULL,
  type_code VARCHAR(64) NOT NULL,
  level VARCHAR(16) NOT NULL,
  trace_id VARBINARY(160) NOT NULL,
  reference_kind VARCHAR(64) NOT NULL,
  reference_id VARBINARY(160) NOT NULL,
  state VARCHAR(24) NOT NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (task_id),
  UNIQUE KEY uq_notification_external (tenant_id,user_id,event_id,channel),
  KEY idx_notification_external_tenant (tenant_id),
  KEY idx_notification_external_user (user_id),
  KEY idx_notification_external_state (state)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS biz_notification_route_outcomes (
  outcome_id VARCHAR(64) NOT NULL,
  event_id VARBINARY(160) NOT NULL,
  tenant_id VARBINARY(64) NOT NULL,
  configuration_id VARBINARY(64) NOT NULL DEFAULT '',
  configuration_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
  user_id VARBINARY(64) NOT NULL DEFAULT '',
  channel VARCHAR(16) NOT NULL DEFAULT '',
  outcome VARCHAR(40) NOT NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (outcome_id),
  KEY idx_notification_route_event (event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
