import { selectUiOption } from './ui.helpers'
import { expect, test, type Page } from '@playwright/test'
import { mkdirSync } from 'node:fs'
async function ready(page: Page) {
  await page.goto('/#/enterprise/members')
  await expect(page.locator('.member-table')).toBeVisible()
  await page.evaluate(() => document.fonts.ready)
}
test('reference body has four summary cards, explicit filters and independent table tools', async ({
  page,
}) => {
  await ready(page)
  await expect(page.locator('.overview-card')).toHaveCount(4)
  await expect(page.locator('.overview-card').nth(1)).toContainText('部门数')
  await expect(page.locator('.quota-card')).toContainText('368')
  await expect(page.locator('.quota-card')).toContainText('500')
  await expect(page.getByRole('button', { name: '批量启用', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: '批量停用', exact: true })).toBeDisabled()
  await page.getByLabel('搜索成员', { exact: true }).fill('lisi@example.com')
  await expect(page.locator('.member-table tbody tr')).toHaveCount(10)
  await page.getByRole('button', { name: '查询', exact: true }).click()
  await expect(page.locator('.member-table tbody tr')).toHaveCount(1)
  await page.getByRole('button', { name: '重置', exact: true }).click()
  await expect(page.getByLabel('搜索成员', { exact: true })).toHaveValue('')
  await expect(page.locator('.member-table tbody tr')).toHaveCount(10)
  await expect(page.locator('.member-table th')).toHaveCount(10)
})
test('view slides out details without a desktop scrim, preserves art and does not select the row', async ({
  page,
}) => {
  await page.setViewportSize({ width: 1536, height: 1024 })
  await ready(page)
  const art = page.locator('.coffee-hero img'),
    src = await art.getAttribute('src')
  await expect(page.getByRole('dialog', { name: '成员详情', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '查看 李四', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: '成员详情', exact: true })
  await expect(drawer).toBeVisible()
  await expect(drawer).toHaveAttribute('aria-modal', 'false')
  await expect(page.locator('.member-detail-backdrop')).toHaveCount(0)
  await expect(drawer).toContainText('lisi@example.com')
  await expect(drawer).toContainText('个人信息')
  await expect(drawer).toContainText('组织信息')
  await expect(page.locator('.member-table tr.viewing')).toHaveCount(1)
  await expect(page.getByLabel('选择 李四', { exact: true })).not.toBeChecked()
  await expect(art).toBeVisible()
  await expect(art).toHaveAttribute('src', src!)
  await page.waitForTimeout(350)
  const artBox = await art.boundingBox(),
    detailBox = await drawer.boundingBox()
  expect(artBox!.x + artBox!.width).toBeLessThanOrEqual(detailBox!.x)
  await drawer.getByRole('tab', { name: '角色权限', exact: true }).click()
  await expect(drawer).toContainText('查看成员')
  await drawer.getByRole('tab', { name: '数据权限', exact: true }).click()
  await expect(drawer).toContainText('当前数据范围')
  await drawer.getByRole('tab', { name: '操作日志', exact: true }).click()
  await expect(drawer).toContainText('暂无操作记录')
  await page.keyboard.press('Escape')
  await expect(drawer).toHaveCount(0)
  await expect(page.getByRole('button', { name: '查看 李四', exact: true })).toBeFocused()
  await expect(page.locator('.member-table tr.viewing')).toHaveCount(0)
})
test('switching viewed member refreshes the details and resets the active tab', async ({ page }) => {
  await ready(page)
  await page.getByRole('button', { name: '查看 李四', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: '成员详情', exact: true })
  await drawer.getByRole('tab', { name: '数据权限', exact: true }).click()
  await page.getByRole('button', { name: '查看 王五', exact: true }).click()
  await expect(drawer).toContainText('wangwu@example.com')
  await expect(drawer.getByRole('tab', { name: '基本信息', exact: true })).toHaveAttribute(
    'aria-selected',
    'true',
  )
  await drawer.getByRole('button', { name: '编辑 王五', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '修改成员信息', exact: true })).toBeVisible()
  await expect(drawer).toHaveCount(0)
})
test('batch disable and enable preserve reason validation and current-page scope', async ({ page }) => {
  await ready(page)
  await page.getByLabel('选择 李四', { exact: true }).check()
  await page.getByLabel('选择 王五', { exact: true }).check()
  await expect(page.locator('.selection-label')).toContainText('2')
  await page.getByRole('button', { name: '批量停用', exact: true }).click()
  let d = page.getByRole('dialog', { name: '批量停用成员', exact: true })
  await d.getByRole('button', { name: '确认批量停用', exact: true }).click()
  await expect(d.getByRole('alert')).toContainText('原因')
  await d.getByLabel('操作原因', { exact: true }).fill('暂时离岗')
  await d.getByRole('checkbox').check()
  await d.getByRole('button', { name: '确认批量停用', exact: true }).click()
  await expect(d).toHaveCount(0)
  await expect(page.locator('[data-member-id="member-2"]')).toContainText('已禁用')
  await expect(page.locator('[data-member-id="member-3"]')).toContainText('已禁用')
  await page.getByLabel('选择 李四', { exact: true }).check()
  await page.getByLabel('选择 王五', { exact: true }).check()
  await page.getByRole('button', { name: '批量启用', exact: true }).click()
  d = page.getByRole('dialog', { name: '批量启用成员', exact: true })
  await d.getByLabel('操作原因', { exact: true }).fill('身份复核完成')
  await d.getByRole('checkbox').check()
  await d.getByRole('button', { name: '确认批量启用', exact: true }).click()
  await expect(page.locator('[data-member-id="member-2"]')).toContainText('正常')
  await expect(page.locator('.selection-label')).toContainText('0')
})
test('detail state is isolated on tenant switch and navigation flyout stays an overlay', async ({ page }) => {
  await ready(page)
  await page.getByRole('button', { name: '查看 李四', exact: true }).click()
  await selectUiOption(page.getByLabel('切换企业', { exact: true }), 'hangzhou')
  await expect(page.locator('.member-detail-panel')).toHaveCount(0)
  await expect(page.locator('.member-overview')).toContainText('24')
  await page.locator('[data-module="enterprise"]').click()
  await expect(page.locator('.module-panel')).toBeVisible()
  expect((await page.locator('.module-panel').boundingBox())!.width).toBe(480)
})
test('mobile detail is a dismissible modal with no horizontal page overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await ready(page)
  await page.getByRole('button', { name: '查看 李四', exact: true }).click()
  const d = page.getByRole('dialog', { name: '成员详情', exact: true })
  await expect(d).toHaveAttribute('aria-modal', 'true')
  await expect(d).toContainText('lisi@example.com')
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390)
  await d.getByRole('button', { name: '关闭成员详情', exact: true }).click()
  await expect(d).toHaveCount(0)
  expect(await page.locator('#app').evaluate((el) => (el as HTMLElement).inert)).toBe(false)
})
test('member reference screenshots from actual browser interactions', async ({ page }) => {
  mkdirSync('screenshots/member-reference', { recursive: true })
  const errors: string[] = []
  page.on('pageerror', (e) => errors.push(e.message))
  page.on('console', (m) => {
    if (m.type() === 'error') errors.push(m.text())
  })
  for (const viewport of [
    { width: 1536, height: 1024 },
    { width: 1366, height: 768 },
  ]) {
    await page.setViewportSize(viewport)
    await ready(page)
    await page.screenshot({
      path: `screenshots/member-reference/members-${viewport.width}-closed.png`,
      fullPage: true,
    })
    await page.getByRole('button', { name: '查看 李四', exact: true }).click()
    await expect(page.locator('.member-detail-panel')).toBeVisible()
    await page.waitForTimeout(350)
    await page.screenshot({
      path: `screenshots/member-reference/members-${viewport.width}-detail.png`,
      fullPage: true,
    })
    await page.getByRole('button', { name: '关闭成员详情', exact: true }).click()
    await expect(page.locator('.member-detail-panel')).toHaveCount(0)
  }
  expect(errors).toEqual([])
})

// #313: real Vue interactions over explicitly tenant-isolated demonstration data.
// These checks do not measure human recognition time or certify backend writes.
test('member task: close returns focus to the most recently viewed row without changing selection', async ({ page }) => {
  await page.setViewportSize({ width: 1536, height: 1024 })
  await ready(page)
  await page.getByLabel('选择 李四', { exact: true }).check()
  await page.getByRole('button', { name: '查看 李四', exact: true }).click()
  await page.getByRole('button', { name: '查看 王五', exact: true }).click()
  const trigger = page.getByRole('button', { name: '查看 王五', exact: true })
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await expect(page.getByLabel('选择 李四', { exact: true })).toBeChecked()
  await expect(page.getByLabel('选择 王五', { exact: true })).not.toBeChecked()
})

test('member task: filtered sorted paginated list and scroll survive a keyboard detail round trip', async ({ page }) => {
  await page.setViewportSize({ width: 1536, height: 1024 })
  await ready(page)
  await page.getByLabel('搜索成员', { exact: true }).fill('@example.com')
  await page.getByRole('button', { name: '查询', exact: true }).click()
  await page.getByRole('button', { name: /按.*加入时间.*排序/ }).click()
  await page.getByRole('button', { name: '下一页', exact: true }).click()
  const rows = page.locator('.member-table tbody tr')
  const rowIds = await rows.evaluateAll((items) => items.map((item) => item.getAttribute('data-member-id')))
  const second = rows.nth(1)
  await second.getByRole('checkbox').check()
  const name = await second.locator('.identity-copy strong').innerText()
  const view = second.getByRole('button', { name: `查看 ${name}`, exact: true })
  await view.scrollIntoViewIfNeeded()
  await view.focus()
  const before = await page.getByTestId('main-content').evaluate((el) => ({ top: el.scrollTop, left: el.scrollLeft }))
  await page.keyboard.press('Enter')
  await expect(page.locator('.member-detail-panel')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(view).toBeFocused()
  await expect(second.getByRole('checkbox')).toBeChecked()
  await expect(page.getByLabel('搜索成员', { exact: true })).toHaveValue('@example.com')
  expect(await rows.evaluateAll((items) => items.map((item) => item.getAttribute('data-member-id')))).toEqual(rowIds)
  await expect(page.locator('.page-number[aria-current="page"]')).toHaveText('2')
  const after = await page.getByTestId('main-content').evaluate((el) => ({ top: el.scrollTop, left: el.scrollLeft }))
  expect(Math.abs(after.top - before.top)).toBeLessThanOrEqual(1)
  expect(after.left).toBe(before.left)
})

test('member task: tenant change clears query selection and guidance instead of reusing another tenants context', async ({ page }) => {
  await ready(page)
  await page.getByLabel('搜索成员', { exact: true }).fill('lisi')
  await page.getByRole('button', { name: '查询', exact: true }).click()
  await page.getByLabel('选择 李四', { exact: true }).check()
  await page.getByRole('button', { name: '如何查找和管理成员', exact: true }).click()
  await selectUiOption(page.getByLabel('切换企业', { exact: true }), 'hangzhou')
  await expect(page.getByLabel('搜索成员', { exact: true })).toHaveValue('')
  await expect(page.locator('.selection-label')).toContainText('0')
  await expect(page.locator('#member-task-help')).toHaveCount(0)
  await expect(page.locator('.member-overview')).toContainText('24')
})

test('member task: guidance and state confirmation remain readable at four viewports', async ({ page }, info) => {
  mkdirSync('screenshots/member-task', { recursive: true })
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  for (const viewport of [{ width: 1366, height: 768 }, { width: 1440, height: 900 }, { width: 1536, height: 1024 }, { width: 390, height: 844 }]) {
    await page.setViewportSize(viewport)
    await ready(page)
    const help = page.getByRole('button', { name: '如何查找和管理成员', exact: true })
    await help.focus(); await page.keyboard.press('Enter')
    await expect(help).toHaveAttribute('aria-expanded', 'true')
    await expect(page.locator('#member-task-help')).toContainText('不会勾选')
    await page.screenshot({ path: `screenshots/member-task/members-${viewport.width}-guidance.png`, fullPage: true })
    await page.getByRole('button', { name: '查看 李四', exact: true }).click()
    await expect(page.locator('.member-detail-panel')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
    await page.screenshot({ path: `screenshots/member-task/members-${viewport.width}-detail.png`, fullPage: true })
    await page.keyboard.press('Escape')
    await expect(page.locator('.member-detail-panel')).toHaveCount(0)
    await page.getByLabel('选择 李四', { exact: true }).check()
    await page.getByRole('button', { name: '批量停用', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: '批量停用成员', exact: true })
    await expect(dialog).toContainText('李四')
    await expect(dialog.getByLabel('操作原因', { exact: true })).toBeVisible()
    await page.screenshot({ path: `screenshots/member-task/members-${viewport.width}-confirmation.png`, fullPage: true })
    await dialog.getByRole('button', { name: '取消', exact: true }).click()
    await page.getByLabel('选择 李四', { exact: true }).uncheck()
    await help.click()
  }
  expect(errors).toEqual([])
  await info.attach('member-task-scope', { body: Buffer.from(JSON.stringify({ evidence: 'DEMO_BROWSER_ONLY', viewports: 4, user_measurement: 'NOT_PERFORMED', native_200_percent_zoom: 'NOT_PERFORMED' })), contentType: 'application/json' })
})

test('member task: long bilingual name and numeric identifier remain accessible in details', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await ready(page)
  await page.getByRole('button', { name: '编辑 李四', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '修改成员信息', exact: true })
  const name = '上海客户成功InternationalOperations00012345'
  await dialog.getByLabel('姓名', { exact: true }).fill(name)
  await dialog.getByLabel('员工编号', { exact: true }).fill('EMP-0000000000000000000000313')
  await dialog.getByRole('button', { name: '保存变更', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await page.getByRole('button', { name: `查看 ${name}`, exact: true }).click()
  await expect(page.locator('.profile-title h2')).toHaveText(name)
  await expect(page.locator('.member-detail-panel')).toContainText('EMP-0000000000000000000000313')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
  mkdirSync('screenshots/member-task', { recursive: true })
  await page.screenshot({ path: 'screenshots/member-task/members-390-long-text.png', fullPage: true })
})
