// Code generated by yunka contract; DO NOT EDIT.

package rest

import (
	"errors"
	commercialv1 "github.com/hvritual/biz/contracts/gen/commercial/v1"
	application "github.com/hvritual/biz/internal/commercial/application"
	policy "github.com/hvritual/biz/internal/commercial/policy"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protojson "google.golang.org/protobuf/encoding/protojson"
	io "io"
	"net/http"
	strconv "strconv"
	execution "yunka.io/framework/execution"
	operation "yunka.io/framework/operation"
	authz "yunka.io/gateway/authz"
	httpbinding "yunka.io/gateway/httpbinding"
)

type ModuleCatalogOperationHandler struct {
	application application.ModuleCatalogApplication
	executor    operation.Executor
}

func RegisterModuleCatalogOperationExecutor(mux *http.ServeMux, application application.ModuleCatalogApplication, executor operation.Executor) error {
	if mux == nil {
		return errors.New("contract C9 REST adapter: mux is required")
	}
	if application == nil {
		return errors.New("contract C9 REST adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 REST adapter: operation executor is required")
	}
	handler := &ModuleCatalogOperationHandler{application: application, executor: executor}
	if err := httpbinding.Register(mux, "POST", "/v1/platform/modules", handler.handleOperationCreateModule); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "DELETE", "/v1/platform/modules/{module_code}", handler.handleOperationDeleteModule); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "GET", "/v1/platform/modules/{module_code}", handler.handleOperationGetModule); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "GET", "/v1/platform/modules", handler.handleOperationListModules); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "POST", "/v1/platform/modules/{module_code}/sales-status", handler.handleOperationSetModuleSalesStatus); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "POST", "/v1/platform/modules/{module_code}/technical-status", handler.handleOperationSetModuleTechnicalStatus); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "PATCH", "/v1/platform/modules/{module_code}", handler.handleOperationUpdateModule); err != nil {
		return err
	}
	return nil
}

func writeModuleCatalogOperationError(writer http.ResponseWriter, err error) {
	if authz.IsDenied(err) {
		statusCode := http.StatusForbidden
		var denied *authz.DeniedError
		if errors.As(err, &denied) && (denied.Decision.Reason == authz.ReasonUnauthenticated || denied.Decision.Reason == authz.ReasonAuthenticationMethod) {
			statusCode = http.StatusUnauthorized
		}
		http.Error(writer, http.StatusText(statusCode), statusCode)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyKeyRequired) {
		http.Error(writer, "idempotency key required", http.StatusBadRequest)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyInProgress) || errors.Is(err, execution.ErrIdempotencyCompleted) {
		http.Error(writer, "idempotency conflict", http.StatusConflict)
		return
	}
	if code := status.Code(err); code == codes.Aborted || code == codes.AlreadyExists {
		http.Error(writer, "application conflict", http.StatusConflict)
		return
	}
	if errors.Is(err, operation.ErrExecutorUnavailable) || errors.Is(err, operation.ErrSecurityUnavailable) || errors.Is(err, operation.ErrSecurityNilContext) || errors.Is(err, operation.ErrIdempotencyUnavailable) {
		http.Error(writer, "operation execution unavailable", http.StatusInternalServerError)
		return
	}
	http.Error(writer, "application request failed", http.StatusBadRequest)
}

func (handler *ModuleCatalogOperationHandler) handleOperationCreateModule(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.CreateModuleRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanModuleCatalogCreateModule(), wire, handler.application.CreateModule)
	if err != nil {
		writeModuleCatalogOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *ModuleCatalogOperationHandler) handleOperationDeleteModule(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.DeleteModuleRequest{}
	if raw := request.URL.Query().Get("request_id"); raw != "" {
		wire.RequestId = raw
	}
	if raw := request.URL.Query().Get("version"); raw != "" {
		parsed, err := strconv.ParseUint(raw, 10, 64)
		if err != nil {
			http.Error(writer, "invalid request parameter", http.StatusBadRequest)
			return
		}
		wire.Version = uint64(parsed)
	}
	if raw := request.URL.Query().Get("reason"); raw != "" {
		wire.Reason = raw
	}
	wire.ModuleCode = request.PathValue("module_code")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanModuleCatalogDeleteModule(), wire, handler.application.DeleteModule)
	if err != nil {
		writeModuleCatalogOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *ModuleCatalogOperationHandler) handleOperationGetModule(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.GetModuleRequest{}
	wire.ModuleCode = request.PathValue("module_code")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanModuleCatalogGetModule(), wire, handler.application.GetModule)
	if err != nil {
		writeModuleCatalogOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *ModuleCatalogOperationHandler) handleOperationListModules(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.ListModulesRequest{}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanModuleCatalogListModules(), wire, handler.application.ListModules)
	if err != nil {
		writeModuleCatalogOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *ModuleCatalogOperationHandler) handleOperationSetModuleSalesStatus(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.SetModuleSalesStatusRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.ModuleCode = request.PathValue("module_code")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanModuleCatalogSetModuleSalesStatus(), wire, handler.application.SetModuleSalesStatus)
	if err != nil {
		writeModuleCatalogOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *ModuleCatalogOperationHandler) handleOperationSetModuleTechnicalStatus(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.SetModuleTechnicalStatusRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.ModuleCode = request.PathValue("module_code")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanModuleCatalogSetModuleTechnicalStatus(), wire, handler.application.SetModuleTechnicalStatus)
	if err != nil {
		writeModuleCatalogOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *ModuleCatalogOperationHandler) handleOperationUpdateModule(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.UpdateModuleRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.ModuleCode = request.PathValue("module_code")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanModuleCatalogUpdateModule(), wire, handler.application.UpdateModule)
	if err != nil {
		writeModuleCatalogOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}
