// Code generated by yunka contract; DO NOT EDIT.

package rest

import (
	"errors"
	commercialv1 "github.com/hvritual/biz/contracts/gen/commercial/v1"
	application "github.com/hvritual/biz/internal/commercial/application"
	policy "github.com/hvritual/biz/internal/commercial/policy"
	protojson "google.golang.org/protobuf/encoding/protojson"
	io "io"
	"net/http"
	strconv "strconv"
	execution "yunka.io/framework/execution"
	operation "yunka.io/framework/operation"
	authz "yunka.io/gateway/authz"
)

type OperationHandler struct {
	application application.ModuleCatalogApplication
	executor    operation.Executor
}

func RegisterOperationExecutor(mux *http.ServeMux, application application.ModuleCatalogApplication, executor operation.Executor) error {
	if mux == nil {
		return errors.New("contract C9 REST adapter: mux is required")
	}
	if application == nil {
		return errors.New("contract C9 REST adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 REST adapter: operation executor is required")
	}
	handler := &OperationHandler{application: application, executor: executor}
	mux.HandleFunc("POST /v1/platform/modules", handler.handleOperationCreateModule)
	mux.HandleFunc("DELETE /v1/platform/modules/{module_code}", handler.handleOperationDeleteModule)
	mux.HandleFunc("GET /v1/platform/modules/{module_code}", handler.handleOperationGetModule)
	mux.HandleFunc("GET /v1/platform/modules", handler.handleOperationListModules)
	mux.HandleFunc("POST /v1/platform/modules/{module_code}/sales-status", handler.handleOperationSetModuleSalesStatus)
	mux.HandleFunc("POST /v1/platform/modules/{module_code}/technical-status", handler.handleOperationSetModuleTechnicalStatus)
	mux.HandleFunc("PATCH /v1/platform/modules/{module_code}", handler.handleOperationUpdateModule)
	return nil
}

func writeOperationError(writer http.ResponseWriter, err error) {
	if authz.IsDenied(err) {
		statusCode := http.StatusForbidden
		var denied *authz.DeniedError
		if errors.As(err, &denied) && (denied.Decision.Reason == authz.ReasonUnauthenticated || denied.Decision.Reason == authz.ReasonAuthenticationMethod) {
			statusCode = http.StatusUnauthorized
		}
		http.Error(writer, http.StatusText(statusCode), statusCode)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyKeyRequired) {
		http.Error(writer, "idempotency key required", http.StatusBadRequest)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyInProgress) || errors.Is(err, execution.ErrIdempotencyCompleted) {
		http.Error(writer, "idempotency conflict", http.StatusConflict)
		return
	}
	if errors.Is(err, operation.ErrExecutorUnavailable) || errors.Is(err, operation.ErrSecurityUnavailable) || errors.Is(err, operation.ErrSecurityNilContext) || errors.Is(err, operation.ErrIdempotencyUnavailable) {
		http.Error(writer, "operation execution unavailable", http.StatusInternalServerError)
		return
	}
	http.Error(writer, "application request failed", http.StatusBadRequest)
}

func (handler *OperationHandler) handleOperationCreateModule(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.CreateModuleRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanCreateModule(), wire, handler.application.CreateModule)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *OperationHandler) handleOperationDeleteModule(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.DeleteModuleRequest{}
	if raw := request.URL.Query().Get("request_id"); raw != "" {
		wire.RequestId = raw
	}
	if raw := request.URL.Query().Get("version"); raw != "" {
		parsed, err := strconv.ParseUint(raw, 10, 64)
		if err != nil {
			http.Error(writer, "invalid request parameter", http.StatusBadRequest)
			return
		}
		wire.Version = uint64(parsed)
	}
	if raw := request.URL.Query().Get("reason"); raw != "" {
		wire.Reason = raw
	}
	wire.ModuleCode = request.PathValue("module_code")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanDeleteModule(), wire, handler.application.DeleteModule)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *OperationHandler) handleOperationGetModule(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.GetModuleRequest{}
	wire.ModuleCode = request.PathValue("module_code")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanGetModule(), wire, handler.application.GetModule)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *OperationHandler) handleOperationListModules(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.ListModulesRequest{}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanListModules(), wire, handler.application.ListModules)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *OperationHandler) handleOperationSetModuleSalesStatus(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.SetModuleSalesStatusRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.ModuleCode = request.PathValue("module_code")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanSetModuleSalesStatus(), wire, handler.application.SetModuleSalesStatus)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *OperationHandler) handleOperationSetModuleTechnicalStatus(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.SetModuleTechnicalStatusRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.ModuleCode = request.PathValue("module_code")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanSetModuleTechnicalStatus(), wire, handler.application.SetModuleTechnicalStatus)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *OperationHandler) handleOperationUpdateModule(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.UpdateModuleRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.ModuleCode = request.PathValue("module_code")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanUpdateModule(), wire, handler.application.UpdateModule)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}
