// Code generated by yunka contract; DO NOT EDIT.

package rest

import (
	"errors"
	commercialv1 "github.com/hvritual/biz/contracts/gen/commercial/v1"
	application "github.com/hvritual/biz/internal/commercial/application"
	policy "github.com/hvritual/biz/internal/commercial/policy"
	protojson "google.golang.org/protobuf/encoding/protojson"
	io "io"
	"net/http"
	execution "yunka.io/framework/execution"
	operation "yunka.io/framework/operation"
	authz "yunka.io/gateway/authz"
	httpbinding "yunka.io/gateway/httpbinding"
)

type SubscriptionManagementOperationHandler struct {
	application application.SubscriptionManagementApplication
	executor    operation.Executor
}

func RegisterSubscriptionManagementOperationExecutor(mux *http.ServeMux, application application.SubscriptionManagementApplication, executor operation.Executor) error {
	if mux == nil {
		return errors.New("contract C9 REST adapter: mux is required")
	}
	if application == nil {
		return errors.New("contract C9 REST adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 REST adapter: operation executor is required")
	}
	handler := &SubscriptionManagementOperationHandler{application: application, executor: executor}
	if err := httpbinding.Register(mux, "GET", "/v1/platform/tenants/{tenant_id}/subscription", handler.handleOperationGetTenantSubscription); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "GET", "/v1/platform/subscription-default-rules", handler.handleOperationListDefaultSubscriptionRules); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "PUT", "/v1/platform/subscription-default-rules/{rule_id}", handler.handleOperationPutDefaultSubscriptionRule); err != nil {
		return err
	}
	return nil
}

func writeSubscriptionManagementOperationError(writer http.ResponseWriter, err error) {
	if authz.IsDenied(err) {
		statusCode := http.StatusForbidden
		var denied *authz.DeniedError
		if errors.As(err, &denied) && (denied.Decision.Reason == authz.ReasonUnauthenticated || denied.Decision.Reason == authz.ReasonAuthenticationMethod) {
			statusCode = http.StatusUnauthorized
		}
		http.Error(writer, http.StatusText(statusCode), statusCode)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyKeyRequired) {
		http.Error(writer, "idempotency key required", http.StatusBadRequest)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyInProgress) || errors.Is(err, execution.ErrIdempotencyCompleted) {
		http.Error(writer, "idempotency conflict", http.StatusConflict)
		return
	}
	if errors.Is(err, operation.ErrExecutorUnavailable) || errors.Is(err, operation.ErrSecurityUnavailable) || errors.Is(err, operation.ErrSecurityNilContext) || errors.Is(err, operation.ErrIdempotencyUnavailable) {
		http.Error(writer, "operation execution unavailable", http.StatusInternalServerError)
		return
	}
	http.Error(writer, "application request failed", http.StatusBadRequest)
}

func (handler *SubscriptionManagementOperationHandler) handleOperationGetTenantSubscription(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.GetTenantSubscriptionRequest{}
	wire.TenantId = request.PathValue("tenant_id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanSubscriptionManagementGetTenantSubscription(), wire, handler.application.GetTenantSubscription)
	if err != nil {
		writeSubscriptionManagementOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *SubscriptionManagementOperationHandler) handleOperationListDefaultSubscriptionRules(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.ListDefaultSubscriptionRulesRequest{}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanSubscriptionManagementListDefaultSubscriptionRules(), wire, handler.application.ListDefaultSubscriptionRules)
	if err != nil {
		writeSubscriptionManagementOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *SubscriptionManagementOperationHandler) handleOperationPutDefaultSubscriptionRule(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.PutDefaultSubscriptionRuleRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.RuleId = request.PathValue("rule_id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanSubscriptionManagementPutDefaultSubscriptionRule(), wire, handler.application.PutDefaultSubscriptionRule)
	if err != nil {
		writeSubscriptionManagementOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}
