// Code generated by yunka contract; DO NOT EDIT.

package rest

import (
	"errors"
	commercialv1 "github.com/hvritual/biz/contracts/gen/commercial/v1"
	application "github.com/hvritual/biz/internal/commercial/application"
	policy "github.com/hvritual/biz/internal/commercial/policy"
	protojson "google.golang.org/protobuf/encoding/protojson"
	io "io"
	"net/http"
	strconv "strconv"
	execution "yunka.io/framework/execution"
	operation "yunka.io/framework/operation"
	authz "yunka.io/gateway/authz"
)

type PlanManagementOperationHandler struct {
	application application.PlanManagementApplication
	executor    operation.Executor
}

func RegisterPlanManagementOperationExecutor(mux *http.ServeMux, application application.PlanManagementApplication, executor operation.Executor) error {
	if mux == nil {
		return errors.New("contract C9 REST adapter: mux is required")
	}
	if application == nil {
		return errors.New("contract C9 REST adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 REST adapter: operation executor is required")
	}
	handler := &PlanManagementOperationHandler{application: application, executor: executor}
	mux.HandleFunc("POST /v1/platform/plans/{plan_code}/versions/{version}/eligibility", handler.handleOperationCheckPlanEligibility)
	mux.HandleFunc("POST /v1/platform/plans", handler.handleOperationCreatePlanDraft)
	mux.HandleFunc("POST /v1/platform/plans/{plan_code}/versions", handler.handleOperationCreatePlanVersion)
	mux.HandleFunc("GET /v1/platform/plans/{plan_code}/versions/{version}", handler.handleOperationGetPlanVersion)
	mux.HandleFunc("GET /v1/platform/plans/{plan_code}/versions", handler.handleOperationListPlanVersions)
	mux.HandleFunc("POST /v1/platform/plans/{plan_code}/versions/{version}/publish", handler.handleOperationPublishPlanVersion)
	mux.HandleFunc("POST /v1/platform/plans/{plan_code}/versions/{version}/retire", handler.handleOperationRetirePlanVersion)
	mux.HandleFunc("PATCH /v1/platform/plans/{plan_code}/versions/{version}", handler.handleOperationUpdatePlanDraft)
	return nil
}

func writePlanManagementOperationError(writer http.ResponseWriter, err error) {
	if authz.IsDenied(err) {
		statusCode := http.StatusForbidden
		var denied *authz.DeniedError
		if errors.As(err, &denied) && (denied.Decision.Reason == authz.ReasonUnauthenticated || denied.Decision.Reason == authz.ReasonAuthenticationMethod) {
			statusCode = http.StatusUnauthorized
		}
		http.Error(writer, http.StatusText(statusCode), statusCode)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyKeyRequired) {
		http.Error(writer, "idempotency key required", http.StatusBadRequest)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyInProgress) || errors.Is(err, execution.ErrIdempotencyCompleted) {
		http.Error(writer, "idempotency conflict", http.StatusConflict)
		return
	}
	if errors.Is(err, operation.ErrExecutorUnavailable) || errors.Is(err, operation.ErrSecurityUnavailable) || errors.Is(err, operation.ErrSecurityNilContext) || errors.Is(err, operation.ErrIdempotencyUnavailable) {
		http.Error(writer, "operation execution unavailable", http.StatusInternalServerError)
		return
	}
	http.Error(writer, "application request failed", http.StatusBadRequest)
}

func (handler *PlanManagementOperationHandler) handleOperationCheckPlanEligibility(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.CheckPlanEligibilityRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.PlanCode = request.PathValue("plan_code")
	parsed, err := strconv.ParseUint(request.PathValue("version"), 10, 64)
	if err != nil {
		http.Error(writer, "invalid request parameter", http.StatusBadRequest)
		return
	}
	wire.Version = uint64(parsed)
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanPlanManagementCheckPlanEligibility(), wire, handler.application.CheckPlanEligibility)
	if err != nil {
		writePlanManagementOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *PlanManagementOperationHandler) handleOperationCreatePlanDraft(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.CreatePlanDraftRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanPlanManagementCreatePlanDraft(), wire, handler.application.CreatePlanDraft)
	if err != nil {
		writePlanManagementOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *PlanManagementOperationHandler) handleOperationCreatePlanVersion(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.CreatePlanVersionRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.PlanCode = request.PathValue("plan_code")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanPlanManagementCreatePlanVersion(), wire, handler.application.CreatePlanVersion)
	if err != nil {
		writePlanManagementOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *PlanManagementOperationHandler) handleOperationGetPlanVersion(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.GetPlanVersionRequest{}
	wire.PlanCode = request.PathValue("plan_code")
	parsed, err := strconv.ParseUint(request.PathValue("version"), 10, 64)
	if err != nil {
		http.Error(writer, "invalid request parameter", http.StatusBadRequest)
		return
	}
	wire.Version = uint64(parsed)
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanPlanManagementGetPlanVersion(), wire, handler.application.GetPlanVersion)
	if err != nil {
		writePlanManagementOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *PlanManagementOperationHandler) handleOperationListPlanVersions(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.ListPlanVersionsRequest{}
	if raw := request.URL.Query().Get("after_version"); raw != "" {
		parsed, err := strconv.ParseUint(raw, 10, 64)
		if err != nil {
			http.Error(writer, "invalid request parameter", http.StatusBadRequest)
			return
		}
		wire.AfterVersion = uint64(parsed)
	}
	if raw := request.URL.Query().Get("page_size"); raw != "" {
		parsed, err := strconv.ParseUint(raw, 10, 32)
		if err != nil {
			http.Error(writer, "invalid request parameter", http.StatusBadRequest)
			return
		}
		wire.PageSize = uint32(parsed)
	}
	wire.PlanCode = request.PathValue("plan_code")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanPlanManagementListPlanVersions(), wire, handler.application.ListPlanVersions)
	if err != nil {
		writePlanManagementOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *PlanManagementOperationHandler) handleOperationPublishPlanVersion(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.ChangePlanVersionStateRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.PlanCode = request.PathValue("plan_code")
	parsed, err := strconv.ParseUint(request.PathValue("version"), 10, 64)
	if err != nil {
		http.Error(writer, "invalid request parameter", http.StatusBadRequest)
		return
	}
	wire.Version = uint64(parsed)
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanPlanManagementPublishPlanVersion(), wire, handler.application.PublishPlanVersion)
	if err != nil {
		writePlanManagementOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *PlanManagementOperationHandler) handleOperationRetirePlanVersion(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.ChangePlanVersionStateRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.PlanCode = request.PathValue("plan_code")
	parsed, err := strconv.ParseUint(request.PathValue("version"), 10, 64)
	if err != nil {
		http.Error(writer, "invalid request parameter", http.StatusBadRequest)
		return
	}
	wire.Version = uint64(parsed)
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanPlanManagementRetirePlanVersion(), wire, handler.application.RetirePlanVersion)
	if err != nil {
		writePlanManagementOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *PlanManagementOperationHandler) handleOperationUpdatePlanDraft(writer http.ResponseWriter, request *http.Request) {
	wire := &commercialv1.UpdatePlanDraftRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.PlanCode = request.PathValue("plan_code")
	parsed, err := strconv.ParseUint(request.PathValue("version"), 10, 64)
	if err != nil {
		http.Error(writer, "invalid request parameter", http.StatusBadRequest)
		return
	}
	wire.Version = uint64(parsed)
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanPlanManagementUpdatePlanDraft(), wire, handler.application.UpdatePlanDraft)
	if err != nil {
		writePlanManagementOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}
