// Code generated by yunka contract; DO NOT EDIT.

package rpc

import (
	"context"
	"errors"
	deviceopsv1 "github.com/hvritual/biz/contracts/gen/deviceops/v1"
	application "github.com/hvritual/biz/internal/deviceops/application"
	policy "github.com/hvritual/biz/internal/deviceops/policy"
	grpc "google.golang.org/grpc"
	grpcmetadata "google.golang.org/grpc/metadata"
	execution "yunka.io/framework/execution"
	operation "yunka.io/framework/operation"
	gatewaygrpc "yunka.io/gateway/rpc/transport/grpc"
)

type DelegatedDeviceAccessOperationServer struct {
	deviceopsv1.UnimplementedDelegatedDeviceAccessApplicationServer
	application application.DelegatedDeviceAccessApplication
	executor    operation.Executor
}

func RegisterDelegatedDeviceAccessOperationExecutor(registrar grpc.ServiceRegistrar, application application.DelegatedDeviceAccessApplication, executor operation.Executor) error {
	if registrar == nil {
		return errors.New("contract C9 RPC adapter: registrar is required")
	}
	if application == nil {
		return errors.New("contract C9 RPC adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 RPC adapter: operation executor is required")
	}
	deviceopsv1.RegisterDelegatedDeviceAccessApplicationServer(registrar, &DelegatedDeviceAccessOperationServer{application: application, executor: executor})
	return nil
}

func (server *DelegatedDeviceAccessOperationServer) GetDelegatedDevice(ctx context.Context, request *deviceopsv1.GetDelegatedDeviceRequest) (*deviceopsv1.DeviceDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanDelegatedDeviceAccessGetDelegatedDevice(), request, server.application.GetDelegatedDevice)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *DelegatedDeviceAccessOperationServer) UpdateDelegatedDevice(ctx context.Context, request *deviceopsv1.UpdateDelegatedDeviceRequest) (*deviceopsv1.DeviceDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanDelegatedDeviceAccessUpdateDelegatedDevice(), request, server.application.UpdateDelegatedDevice)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}
