// Code generated by yunka contract; DO NOT EDIT.

package rpc

import (
	"context"
	"errors"
	deviceopsv1 "github.com/hvritual/biz/contracts/gen/deviceops/v1"
	application "github.com/hvritual/biz/internal/deviceops/application"
	policy "github.com/hvritual/biz/internal/deviceops/policy"
	grpc "google.golang.org/grpc"
	operation "yunka.io/framework/operation"
	gatewaygrpc "yunka.io/gateway/rpc/transport/grpc"
)

type OperationServer struct {
	deviceopsv1.UnimplementedDeviceApplicationServer
	application application.DeviceApplication
	executor    operation.Executor
}

func RegisterOperationExecutor(registrar grpc.ServiceRegistrar, application application.DeviceApplication, executor operation.Executor) error {
	if registrar == nil {
		return errors.New("contract C9 RPC adapter: registrar is required")
	}
	if application == nil {
		return errors.New("contract C9 RPC adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 RPC adapter: operation executor is required")
	}
	deviceopsv1.RegisterDeviceApplicationServer(registrar, &OperationServer{application: application, executor: executor})
	return nil
}

func (server *OperationServer) CreateDevice(ctx context.Context, request *deviceopsv1.CreateDeviceRequest) (*deviceopsv1.DeviceDTO, error) {
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanCreateDevice(), request, server.application.CreateDevice)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *OperationServer) DeleteDevice(ctx context.Context, request *deviceopsv1.DeleteDeviceRequest) (*deviceopsv1.DeleteDeviceResponse, error) {
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanDeleteDevice(), request, server.application.DeleteDevice)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *OperationServer) GetDevice(ctx context.Context, request *deviceopsv1.GetDeviceRequest) (*deviceopsv1.DeviceDTO, error) {
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanGetDevice(), request, server.application.GetDevice)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *OperationServer) ListDevices(ctx context.Context, request *deviceopsv1.ListDevicesRequest) (*deviceopsv1.ListDevicesResponse, error) {
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanListDevices(), request, server.application.ListDevices)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *OperationServer) UpdateDevice(ctx context.Context, request *deviceopsv1.UpdateDeviceRequest) (*deviceopsv1.DeviceDTO, error) {
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanUpdateDevice(), request, server.application.UpdateDevice)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}
