// Code generated by yunka module; DO NOT EDIT.

package access

import (
	"fmt"
	"yunka.io/framework/core/modulecatalog"
)

func GeneratedDescriptor() modulecatalog.Descriptor {
	return modulecatalog.Descriptor{
		Name:    ModuleName,
		Version: "v0.1.0",
		Requirements: modulecatalog.Requirements{
			Databases: []modulecatalog.DatabaseRequirement{{Name: "primary"}},
		},
		Build: generatedBuild,
	}
}

func generatedBuild(context modulecatalog.BuildContext) (modulecatalog.Instance, error) {
	dependencies := Dependencies{}
	primaryDatabase, err := context.Databases().GORM("primary")
	if err != nil {
		return nil, fmt.Errorf("%s database primary: %w", ModuleName, err)
	}
	dependencies.PrimaryDatabase = primaryDatabase
	return NewModule(dependencies)
}
