// Code generated by yunka contract; DO NOT EDIT.

package rest

import (
	"errors"
	notificationv1 "github.com/hvritual/biz/contracts/gen/notification/v1"
	application "github.com/hvritual/biz/internal/notification/application"
	policy "github.com/hvritual/biz/internal/notification/policy"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protojson "google.golang.org/protobuf/encoding/protojson"
	io "io"
	"net/http"
	strconv "strconv"
	execution "yunka.io/framework/execution"
	operation "yunka.io/framework/operation"
	authz "yunka.io/gateway/authz"
	httpbinding "yunka.io/gateway/httpbinding"
)

type OperationHandler struct {
	application application.MessageConfigurationApplication
	executor    operation.Executor
}

func RegisterOperationExecutor(mux *http.ServeMux, application application.MessageConfigurationApplication, executor operation.Executor) error {
	if mux == nil {
		return errors.New("contract C9 REST adapter: mux is required")
	}
	if application == nil {
		return errors.New("contract C9 REST adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 REST adapter: operation executor is required")
	}
	handler := &OperationHandler{application: application, executor: executor}
	if err := httpbinding.Register(mux, "POST", "/v1/tenant/notification/configurations", handler.handleOperationCreateMessageConfigurations); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "POST", "/v1/tenant/notification/configurations/{id}/delete", handler.handleOperationDeleteMessageConfiguration); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "GET", "/v1/tenant/notification/configurations/{id}", handler.handleOperationGetMessageConfiguration); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "GET", "/v1/tenant/notification/channels", handler.handleOperationListMessageChannels); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "GET", "/v1/tenant/notification/configurations", handler.handleOperationListMessageConfigurations); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "GET", "/v1/tenant/notification/groups", handler.handleOperationListMessageGroups); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "GET", "/v1/tenant/notification/recipients", handler.handleOperationListMessageRecipients); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "GET", "/v1/tenant/notification/types", handler.handleOperationListMessageTypes); err != nil {
		return err
	}
	if err := httpbinding.Register(mux, "PATCH", "/v1/tenant/notification/configurations/{id}", handler.handleOperationUpdateMessageConfiguration); err != nil {
		return err
	}
	return nil
}

func writeOperationError(writer http.ResponseWriter, err error) {
	if authz.IsDenied(err) {
		statusCode := http.StatusForbidden
		var denied *authz.DeniedError
		if errors.As(err, &denied) && (denied.Decision.Reason == authz.ReasonUnauthenticated || denied.Decision.Reason == authz.ReasonAuthenticationMethod) {
			statusCode = http.StatusUnauthorized
		}
		http.Error(writer, http.StatusText(statusCode), statusCode)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyKeyRequired) {
		http.Error(writer, "idempotency key required", http.StatusBadRequest)
		return
	}
	if errors.Is(err, execution.ErrIdempotencyInProgress) || errors.Is(err, execution.ErrIdempotencyCompleted) {
		http.Error(writer, "idempotency conflict", http.StatusConflict)
		return
	}
	if code := status.Code(err); code == codes.Aborted || code == codes.AlreadyExists {
		http.Error(writer, "application conflict", http.StatusConflict)
		return
	}
	if errors.Is(err, operation.ErrExecutorUnavailable) || errors.Is(err, operation.ErrSecurityUnavailable) || errors.Is(err, operation.ErrSecurityNilContext) || errors.Is(err, operation.ErrIdempotencyUnavailable) {
		http.Error(writer, "operation execution unavailable", http.StatusInternalServerError)
		return
	}
	http.Error(writer, "application request failed", http.StatusBadRequest)
}

func (handler *OperationHandler) handleOperationCreateMessageConfigurations(writer http.ResponseWriter, request *http.Request) {
	wire := &notificationv1.CreateMessageConfigurationsRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanCreateMessageConfigurations(), wire, handler.application.CreateMessageConfigurations)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *OperationHandler) handleOperationDeleteMessageConfiguration(writer http.ResponseWriter, request *http.Request) {
	wire := &notificationv1.DeleteMessageConfigurationRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.Id = request.PathValue("id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanDeleteMessageConfiguration(), wire, handler.application.DeleteMessageConfiguration)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *OperationHandler) handleOperationGetMessageConfiguration(writer http.ResponseWriter, request *http.Request) {
	wire := &notificationv1.GetMessageConfigurationRequest{}
	wire.Id = request.PathValue("id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanGetMessageConfiguration(), wire, handler.application.GetMessageConfiguration)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *OperationHandler) handleOperationListMessageChannels(writer http.ResponseWriter, request *http.Request) {
	wire := &notificationv1.ListMessageChannelsRequest{}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanListMessageChannels(), wire, handler.application.ListMessageChannels)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *OperationHandler) handleOperationListMessageConfigurations(writer http.ResponseWriter, request *http.Request) {
	wire := &notificationv1.ListMessageConfigurationsRequest{}
	if raw := request.URL.Query().Get("group_id"); raw != "" {
		wire.GroupId = raw
	}
	if raw := request.URL.Query().Get("level"); raw != "" {
		wire.Level = raw
	}
	if raw := request.URL.Query().Get("recipient_id"); raw != "" {
		wire.RecipientId = raw
	}
	if raw := request.URL.Query().Get("page"); raw != "" {
		parsed, err := strconv.ParseUint(raw, 10, 32)
		if err != nil {
			http.Error(writer, "invalid request parameter", http.StatusBadRequest)
			return
		}
		wire.Page = uint32(parsed)
	}
	if raw := request.URL.Query().Get("page_size"); raw != "" {
		parsed, err := strconv.ParseUint(raw, 10, 32)
		if err != nil {
			http.Error(writer, "invalid request parameter", http.StatusBadRequest)
			return
		}
		wire.PageSize = uint32(parsed)
	}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanListMessageConfigurations(), wire, handler.application.ListMessageConfigurations)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *OperationHandler) handleOperationListMessageGroups(writer http.ResponseWriter, request *http.Request) {
	wire := &notificationv1.ListMessageDirectoryRequest{}
	if raw := request.URL.Query().Get("query"); raw != "" {
		wire.Query = raw
	}
	if raw := request.URL.Query().Get("page"); raw != "" {
		parsed, err := strconv.ParseUint(raw, 10, 32)
		if err != nil {
			http.Error(writer, "invalid request parameter", http.StatusBadRequest)
			return
		}
		wire.Page = uint32(parsed)
	}
	if raw := request.URL.Query().Get("page_size"); raw != "" {
		parsed, err := strconv.ParseUint(raw, 10, 32)
		if err != nil {
			http.Error(writer, "invalid request parameter", http.StatusBadRequest)
			return
		}
		wire.PageSize = uint32(parsed)
	}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanListMessageGroups(), wire, handler.application.ListMessageGroups)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *OperationHandler) handleOperationListMessageRecipients(writer http.ResponseWriter, request *http.Request) {
	wire := &notificationv1.ListMessageDirectoryRequest{}
	if raw := request.URL.Query().Get("query"); raw != "" {
		wire.Query = raw
	}
	if raw := request.URL.Query().Get("page"); raw != "" {
		parsed, err := strconv.ParseUint(raw, 10, 32)
		if err != nil {
			http.Error(writer, "invalid request parameter", http.StatusBadRequest)
			return
		}
		wire.Page = uint32(parsed)
	}
	if raw := request.URL.Query().Get("page_size"); raw != "" {
		parsed, err := strconv.ParseUint(raw, 10, 32)
		if err != nil {
			http.Error(writer, "invalid request parameter", http.StatusBadRequest)
			return
		}
		wire.PageSize = uint32(parsed)
	}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanListMessageRecipients(), wire, handler.application.ListMessageRecipients)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *OperationHandler) handleOperationListMessageTypes(writer http.ResponseWriter, request *http.Request) {
	wire := &notificationv1.ListMessageTypesRequest{}
	if raw := request.URL.Query().Get("code"); raw != "" {
		wire.Code = raw
	}
	if raw := request.URL.Query().Get("name"); raw != "" {
		wire.Name = raw
	}
	if raw := request.URL.Query().Get("level"); raw != "" {
		wire.Level = raw
	}
	if raw := request.URL.Query().Get("page"); raw != "" {
		parsed, err := strconv.ParseUint(raw, 10, 32)
		if err != nil {
			http.Error(writer, "invalid request parameter", http.StatusBadRequest)
			return
		}
		wire.Page = uint32(parsed)
	}
	if raw := request.URL.Query().Get("page_size"); raw != "" {
		parsed, err := strconv.ParseUint(raw, 10, 32)
		if err != nil {
			http.Error(writer, "invalid request parameter", http.StatusBadRequest)
			return
		}
		wire.PageSize = uint32(parsed)
	}
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanListMessageTypes(), wire, handler.application.ListMessageTypes)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}

func (handler *OperationHandler) handleOperationUpdateMessageConfiguration(writer http.ResponseWriter, request *http.Request) {
	wire := &notificationv1.UpdateMessageConfigurationRequest{}
	body, err := io.ReadAll(request.Body)
	if err != nil {
		http.Error(writer, "invalid request body", http.StatusBadRequest)
		return
	}
	if len(body) > 0 {
		if err := protojson.Unmarshal(body, wire); err != nil {
			http.Error(writer, "invalid request body", http.StatusBadRequest)
			return
		}
	}
	wire.Id = request.PathValue("id")
	callContext := execution.WithIdempotencyKey(request.Context(), request.Header.Get("Idempotency-Key"))
	output, err := operation.ExecuteTyped(callContext, handler.executor, policy.OperationPlanUpdateMessageConfiguration(), wire, handler.application.UpdateMessageConfiguration)
	if err != nil {
		writeOperationError(writer, err)
		return
	}
	payload, err := protojson.Marshal(output)
	if err != nil {
		http.Error(writer, "response encoding failed", http.StatusInternalServerError)
		return
	}
	writer.Header().Set("Content-Type", "application/json")
	_, _ = writer.Write(payload)
}
