// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/gateway/authz"

const OperationPlanManagementCheckPlanEligibility authz.OperationID = "commercial.plan.eligibility"
const OperationPlanManagementCreatePlanDraft authz.OperationID = "commercial.plan.create"
const OperationPlanManagementCreatePlanVersion authz.OperationID = "commercial.plan.clone"
const OperationPlanManagementGetPlanVersion authz.OperationID = "commercial.plan.get"
const OperationPlanManagementListPlanVersions authz.OperationID = "commercial.plan.list"
const OperationPlanManagementPublishPlanVersion authz.OperationID = "commercial.plan.publish"
const OperationPlanManagementRetirePlanVersion authz.OperationID = "commercial.plan.retire"
const OperationPlanManagementUpdatePlanDraft authz.OperationID = "commercial.plan.update"

func PlanManagementPermissions() []authz.PermissionKey {
	return []authz.PermissionKey{"commercial.catalog.read", "platform.plan.manage", "platform.plan.publish", "platform.plan.read"}
}

func PlanManagementResolver() authz.StaticResolver {
	return authz.NewStaticResolver(planManagementPolicies())
}

func planManagementPolicies() map[string]authz.Policy {
	return map[string]authz.Policy{
		"/commercial.v1.PlanManagementApplication/CheckPlanEligibility": {Operation: OperationPlanManagementCheckPlanEligibility, Permissions: []authz.PermissionKey{"commercial.catalog.read", "platform.plan.read"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/commercial.v1.PlanManagementApplication/CreatePlanDraft":      {Operation: OperationPlanManagementCreatePlanDraft, Permissions: []authz.PermissionKey{"commercial.catalog.read", "platform.plan.manage"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/commercial.v1.PlanManagementApplication/CreatePlanVersion":    {Operation: OperationPlanManagementCreatePlanVersion, Permissions: []authz.PermissionKey{"commercial.catalog.read", "platform.plan.manage"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/commercial.v1.PlanManagementApplication/GetPlanVersion":       {Operation: OperationPlanManagementGetPlanVersion, Permissions: []authz.PermissionKey{"platform.plan.read"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/commercial.v1.PlanManagementApplication/ListPlanVersions":     {Operation: OperationPlanManagementListPlanVersions, Permissions: []authz.PermissionKey{"platform.plan.read"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/commercial.v1.PlanManagementApplication/PublishPlanVersion":   {Operation: OperationPlanManagementPublishPlanVersion, Permissions: []authz.PermissionKey{"commercial.catalog.read", "platform.plan.publish"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/commercial.v1.PlanManagementApplication/RetirePlanVersion":    {Operation: OperationPlanManagementRetirePlanVersion, Permissions: []authz.PermissionKey{"commercial.catalog.read", "platform.plan.publish"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/commercial.v1.PlanManagementApplication/UpdatePlanDraft":      {Operation: OperationPlanManagementUpdatePlanDraft, Permissions: []authz.PermissionKey{"commercial.catalog.read", "platform.plan.manage"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
	}
}
