// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/gateway/authz"

const OperationSubscriptionChangesConfirmSubscriptionChange authz.OperationID = "commercial.subscription.change.confirm"
const OperationSubscriptionChangesGetSubscriptionChangePreview authz.OperationID = "commercial.subscription.change.preview.get"
const OperationSubscriptionChangesGetSubscriptionChangeReceipt authz.OperationID = "commercial.subscription.change.get"
const OperationSubscriptionChangesPreviewSubscriptionChange authz.OperationID = "commercial.subscription.change.preview"

func SubscriptionChangesPermissions() []authz.PermissionKey {
	return []authz.PermissionKey{"commercial.catalog.read", "platform.plan.read", "platform.subscription.confirm", "platform.subscription.manage", "platform.subscription.read", "platform.tenant.read"}
}

func SubscriptionChangesResolver() authz.StaticResolver {
	return authz.NewStaticResolver(subscriptionChangesPolicies())
}

func subscriptionChangesPolicies() map[string]authz.Policy {
	return map[string]authz.Policy{
		"/commercial.v1.SubscriptionChangesApplication/ConfirmSubscriptionChange":    {Operation: OperationSubscriptionChangesConfirmSubscriptionChange, Permissions: []authz.PermissionKey{"commercial.catalog.read", "platform.plan.read", "platform.subscription.confirm", "platform.tenant.read"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/commercial.v1.SubscriptionChangesApplication/GetSubscriptionChangePreview": {Operation: OperationSubscriptionChangesGetSubscriptionChangePreview, Permissions: []authz.PermissionKey{"platform.subscription.read", "platform.tenant.read"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/commercial.v1.SubscriptionChangesApplication/GetSubscriptionChangeReceipt": {Operation: OperationSubscriptionChangesGetSubscriptionChangeReceipt, Permissions: []authz.PermissionKey{"platform.subscription.read", "platform.tenant.read"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/commercial.v1.SubscriptionChangesApplication/PreviewSubscriptionChange":    {Operation: OperationSubscriptionChangesPreviewSubscriptionChange, Permissions: []authz.PermissionKey{"commercial.catalog.read", "platform.plan.read", "platform.subscription.manage", "platform.tenant.read"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
	}
}
