// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/gateway/authz"

const OperationSubscriptionManagementGetTenantSubscription authz.OperationID = "commercial.subscription.get"
const OperationSubscriptionManagementListDefaultSubscriptionRules authz.OperationID = "commercial.subscription.rule.list"
const OperationSubscriptionManagementPutDefaultSubscriptionRule authz.OperationID = "commercial.subscription.rule.put"

func SubscriptionManagementPermissions() []authz.PermissionKey {
	return []authz.PermissionKey{"commercial.catalog.read", "platform.plan.read", "platform.subscription.manage", "platform.subscription.read", "platform.tenant.read"}
}

func SubscriptionManagementResolver() authz.StaticResolver {
	return authz.NewStaticResolver(subscriptionManagementPolicies())
}

func subscriptionManagementPolicies() map[string]authz.Policy {
	return map[string]authz.Policy{
		"/commercial.v1.SubscriptionManagementApplication/GetTenantSubscription":        {Operation: OperationSubscriptionManagementGetTenantSubscription, Permissions: []authz.PermissionKey{"platform.subscription.read", "platform.tenant.read"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/commercial.v1.SubscriptionManagementApplication/ListDefaultSubscriptionRules": {Operation: OperationSubscriptionManagementListDefaultSubscriptionRules, Permissions: []authz.PermissionKey{"platform.subscription.read"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/commercial.v1.SubscriptionManagementApplication/PutDefaultSubscriptionRule":   {Operation: OperationSubscriptionManagementPutDefaultSubscriptionRule, Permissions: []authz.PermissionKey{"commercial.catalog.read", "platform.plan.read", "platform.subscription.manage"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
	}
}
