// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/gateway/authz"

const OperationEntitlementManagementCreateEntitlementOverride authz.OperationID = "commercial.entitlement.override.create"
const OperationEntitlementManagementExplainEntitlements authz.OperationID = "commercial.entitlement.explain"
const OperationEntitlementManagementGetMyEntitlements authz.OperationID = "commercial.entitlement.get_my"
const OperationEntitlementManagementListEntitlementOverrides authz.OperationID = "commercial.entitlement.override.list"
const OperationEntitlementManagementRevokeEntitlementOverride authz.OperationID = "commercial.entitlement.override.revoke"

func EntitlementManagementPermissions() []authz.PermissionKey {
	return []authz.PermissionKey{"commercial.catalog.read", "platform.entitlement.manage", "platform.entitlement.read", "platform.tenant.read", "tenant.entitlement.read"}
}

func EntitlementManagementResolver() authz.StaticResolver {
	return authz.NewStaticResolver(entitlementManagementPolicies())
}

func entitlementManagementPolicies() map[string]authz.Policy {
	return map[string]authz.Policy{
		"/commercial.v1.EntitlementManagementApplication/CreateEntitlementOverride": {Operation: OperationEntitlementManagementCreateEntitlementOverride, Permissions: []authz.PermissionKey{"commercial.catalog.read", "platform.entitlement.manage", "platform.tenant.read"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/commercial.v1.EntitlementManagementApplication/ExplainEntitlements":       {Operation: OperationEntitlementManagementExplainEntitlements, Permissions: []authz.PermissionKey{"commercial.catalog.read", "platform.entitlement.read", "platform.tenant.read"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/commercial.v1.EntitlementManagementApplication/GetMyEntitlements":         {Operation: OperationEntitlementManagementGetMyEntitlements, Permissions: []authz.PermissionKey{"commercial.catalog.read", "tenant.entitlement.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/commercial.v1.EntitlementManagementApplication/ListEntitlementOverrides":  {Operation: OperationEntitlementManagementListEntitlementOverrides, Permissions: []authz.PermissionKey{"platform.entitlement.read", "platform.tenant.read"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
		"/commercial.v1.EntitlementManagementApplication/RevokeEntitlementOverride": {Operation: OperationEntitlementManagementRevokeEntitlementOverride, Permissions: []authz.PermissionKey{"platform.entitlement.manage", "platform.tenant.read"}, Mode: authz.PermissionAll, Authentication: []string{"api-key"}},
	}
}
