// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/gateway/authz"

const OperationTenantMemberLifecycleActivateTenantMember authz.OperationID = "tenant.member.activate"
const OperationTenantMemberLifecycleGetTenantMember authz.OperationID = "tenant.member.get"
const OperationTenantMemberLifecycleInviteTenantMember authz.OperationID = "tenant.member.invite"
const OperationTenantMemberLifecycleListTenantMembers authz.OperationID = "tenant.member.list"
const OperationTenantMemberLifecycleRemoveTenantMember authz.OperationID = "tenant.member.remove"
const OperationTenantMemberLifecycleSuspendTenantMember authz.OperationID = "tenant.member.suspend"

func TenantMemberLifecyclePermissions() []authz.PermissionKey {
	return []authz.PermissionKey{"tenant.member.manage", "tenant.member.read"}
}

func TenantMemberLifecycleResolver() authz.StaticResolver {
	return authz.NewStaticResolver(tenantMemberLifecyclePolicies())
}

func tenantMemberLifecyclePolicies() map[string]authz.Policy {
	return map[string]authz.Policy{
		"/access.v1.TenantMemberLifecycleApplication/ActivateTenantMember": {Operation: OperationTenantMemberLifecycleActivateTenantMember, Permissions: []authz.PermissionKey{"tenant.member.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key"}},
		"/access.v1.TenantMemberLifecycleApplication/GetTenantMember":      {Operation: OperationTenantMemberLifecycleGetTenantMember, Permissions: []authz.PermissionKey{"tenant.member.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key"}},
		"/access.v1.TenantMemberLifecycleApplication/InviteTenantMember":   {Operation: OperationTenantMemberLifecycleInviteTenantMember, Permissions: []authz.PermissionKey{"tenant.member.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key"}},
		"/access.v1.TenantMemberLifecycleApplication/ListTenantMembers":    {Operation: OperationTenantMemberLifecycleListTenantMembers, Permissions: []authz.PermissionKey{"tenant.member.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key"}},
		"/access.v1.TenantMemberLifecycleApplication/RemoveTenantMember":   {Operation: OperationTenantMemberLifecycleRemoveTenantMember, Permissions: []authz.PermissionKey{"tenant.member.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key"}},
		"/access.v1.TenantMemberLifecycleApplication/SuspendTenantMember":  {Operation: OperationTenantMemberLifecycleSuspendTenantMember, Permissions: []authz.PermissionKey{"tenant.member.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key"}},
	}
}
