// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/gateway/authz"

func Permissions() []authz.PermissionKey {
	return []authz.PermissionKey{"commercial.catalog.read", "platform.plan.read", "platform.tenant.create", "platform.tenant.manage", "platform.tenant.read", "tenant.audit.export", "tenant.audit.read", "tenant.branding.read", "tenant.delegation.manage", "tenant.delegation.read", "tenant.member.manage", "tenant.member.read", "tenant.organization.manage", "tenant.organization.read", "tenant.personal_profile.self", "tenant.role.manage", "tenant.role.read"}
}

func Resolver() authz.StaticResolver {
	policies := map[string]authz.Policy{}
	for key, value := range tenantAuditManagementPolicies() {
		policies[key] = value
	}
	for key, value := range tenantDelegationManagementPolicies() {
		policies[key] = value
	}
	for key, value := range tenantDepartmentManagementPolicies() {
		policies[key] = value
	}
	for key, value := range tenantLifecyclePolicies() {
		policies[key] = value
	}
	for key, value := range tenantMemberBusinessScopePolicies() {
		policies[key] = value
	}
	for key, value := range tenantMemberLifecyclePolicies() {
		policies[key] = value
	}
	for key, value := range tenantProfileManagementPolicies() {
		policies[key] = value
	}
	for key, value := range tenantRolePermissionPolicies() {
		policies[key] = value
	}
	return authz.NewStaticResolver(policies)
}
