// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/gateway/authz"

const OperationTenantDepartmentManagementCreateTenantDepartment authz.OperationID = "tenant.department.create"
const OperationTenantDepartmentManagementDisableTenantDepartment authz.OperationID = "tenant.department.disable"
const OperationTenantDepartmentManagementEnableTenantDepartment authz.OperationID = "tenant.department.enable"
const OperationTenantDepartmentManagementGetTenantDepartment authz.OperationID = "tenant.department.get"
const OperationTenantDepartmentManagementListTenantDepartments authz.OperationID = "tenant.department.list"
const OperationTenantDepartmentManagementUpdateTenantDepartment authz.OperationID = "tenant.department.update"

func TenantDepartmentManagementPermissions() []authz.PermissionKey {
	return []authz.PermissionKey{"tenant.organization.manage", "tenant.organization.read"}
}

func TenantDepartmentManagementResolver() authz.StaticResolver {
	return authz.NewStaticResolver(tenantDepartmentManagementPolicies())
}

func tenantDepartmentManagementPolicies() map[string]authz.Policy {
	return map[string]authz.Policy{
		"/access.v1.TenantDepartmentManagementApplication/CreateTenantDepartment":  {Operation: OperationTenantDepartmentManagementCreateTenantDepartment, Permissions: []authz.PermissionKey{"tenant.organization.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantDepartmentManagementApplication/DisableTenantDepartment": {Operation: OperationTenantDepartmentManagementDisableTenantDepartment, Permissions: []authz.PermissionKey{"tenant.organization.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantDepartmentManagementApplication/EnableTenantDepartment":  {Operation: OperationTenantDepartmentManagementEnableTenantDepartment, Permissions: []authz.PermissionKey{"tenant.organization.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantDepartmentManagementApplication/GetTenantDepartment":     {Operation: OperationTenantDepartmentManagementGetTenantDepartment, Permissions: []authz.PermissionKey{"tenant.organization.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantDepartmentManagementApplication/ListTenantDepartments":   {Operation: OperationTenantDepartmentManagementListTenantDepartments, Permissions: []authz.PermissionKey{"tenant.organization.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantDepartmentManagementApplication/UpdateTenantDepartment":  {Operation: OperationTenantDepartmentManagementUpdateTenantDepartment, Permissions: []authz.PermissionKey{"tenant.organization.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
	}
}
