// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/gateway/authz"

const OperationTenantMemberLifecycleActivateTenantMember authz.OperationID = "tenant.member.activate"
const OperationTenantMemberLifecycleCreateTenantMember authz.OperationID = "tenant.member.create"
const OperationTenantMemberLifecycleGetTenantMember authz.OperationID = "tenant.member.get"
const OperationTenantMemberLifecycleGetTenantMemberBusinessScope authz.OperationID = "tenant.member.business_scope.get"
const OperationTenantMemberLifecycleInviteTenantMember authz.OperationID = "tenant.member.invite"
const OperationTenantMemberLifecycleListRemovedTenantMembers authz.OperationID = "tenant.member.list_removed"
const OperationTenantMemberLifecycleListTenantMemberScopeCandidates authz.OperationID = "tenant.member.scope_candidates"
const OperationTenantMemberLifecycleListTenantMembers authz.OperationID = "tenant.member.list"
const OperationTenantMemberLifecycleRemoveTenantMember authz.OperationID = "tenant.member.remove"
const OperationTenantMemberLifecycleRestoreTenantMember authz.OperationID = "tenant.member.restore"
const OperationTenantMemberLifecycleSetTenantMemberBusinessScope authz.OperationID = "tenant.member.business_scope.set"
const OperationTenantMemberLifecycleSuspendTenantMember authz.OperationID = "tenant.member.suspend"
const OperationTenantMemberLifecycleUpdateTenantMember authz.OperationID = "tenant.member.update"
const OperationTenantMemberLifecycleUpdateTenantMemberProfile authz.OperationID = "tenant.member.profile.update"

func TenantMemberLifecyclePermissions() []authz.PermissionKey {
	return []authz.PermissionKey{"tenant.member.manage", "tenant.member.read", "tenant.role.manage"}
}

func TenantMemberLifecycleResolver() authz.StaticResolver {
	return authz.NewStaticResolver(tenantMemberLifecyclePolicies())
}

func tenantMemberLifecyclePolicies() map[string]authz.Policy {
	return map[string]authz.Policy{
		"/access.v1.TenantMemberLifecycleApplication/ActivateTenantMember":            {Operation: OperationTenantMemberLifecycleActivateTenantMember, Permissions: []authz.PermissionKey{"tenant.member.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantMemberLifecycleApplication/CreateTenantMember":              {Operation: OperationTenantMemberLifecycleCreateTenantMember, Permissions: []authz.PermissionKey{"tenant.member.manage", "tenant.role.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantMemberLifecycleApplication/GetTenantMember":                 {Operation: OperationTenantMemberLifecycleGetTenantMember, Permissions: []authz.PermissionKey{"tenant.member.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantMemberLifecycleApplication/GetTenantMemberBusinessScope":    {Operation: OperationTenantMemberLifecycleGetTenantMemberBusinessScope, Permissions: []authz.PermissionKey{"tenant.member.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantMemberLifecycleApplication/InviteTenantMember":              {Operation: OperationTenantMemberLifecycleInviteTenantMember, Permissions: []authz.PermissionKey{"tenant.member.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantMemberLifecycleApplication/ListRemovedTenantMembers":        {Operation: OperationTenantMemberLifecycleListRemovedTenantMembers, Permissions: []authz.PermissionKey{"tenant.member.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantMemberLifecycleApplication/ListTenantMemberScopeCandidates": {Operation: OperationTenantMemberLifecycleListTenantMemberScopeCandidates, Permissions: []authz.PermissionKey{"tenant.member.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantMemberLifecycleApplication/ListTenantMembers":               {Operation: OperationTenantMemberLifecycleListTenantMembers, Permissions: []authz.PermissionKey{"tenant.member.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantMemberLifecycleApplication/RemoveTenantMember":              {Operation: OperationTenantMemberLifecycleRemoveTenantMember, Permissions: []authz.PermissionKey{"tenant.member.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantMemberLifecycleApplication/RestoreTenantMember":             {Operation: OperationTenantMemberLifecycleRestoreTenantMember, Permissions: []authz.PermissionKey{"tenant.member.manage", "tenant.role.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantMemberLifecycleApplication/SetTenantMemberBusinessScope":    {Operation: OperationTenantMemberLifecycleSetTenantMemberBusinessScope, Permissions: []authz.PermissionKey{"tenant.member.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantMemberLifecycleApplication/SuspendTenantMember":             {Operation: OperationTenantMemberLifecycleSuspendTenantMember, Permissions: []authz.PermissionKey{"tenant.member.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantMemberLifecycleApplication/UpdateTenantMember":              {Operation: OperationTenantMemberLifecycleUpdateTenantMember, Permissions: []authz.PermissionKey{"tenant.member.manage", "tenant.role.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantMemberLifecycleApplication/UpdateTenantMemberProfile":       {Operation: OperationTenantMemberLifecycleUpdateTenantMemberProfile, Permissions: []authz.PermissionKey{"tenant.member.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
	}
}
