// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/gateway/authz"

const OperationTenantAuditManagementExportTenantAuditRecords authz.OperationID = "access.audit.export"
const OperationTenantAuditManagementGetTenantAuditRecord authz.OperationID = "access.audit.get"
const OperationTenantAuditManagementListTenantAuditRecords authz.OperationID = "access.audit.list"

func TenantAuditManagementPermissions() []authz.PermissionKey {
	return []authz.PermissionKey{"tenant.audit.export", "tenant.audit.read"}
}

func TenantAuditManagementResolver() authz.StaticResolver {
	return authz.NewStaticResolver(tenantAuditManagementPolicies())
}

func tenantAuditManagementPolicies() map[string]authz.Policy {
	return map[string]authz.Policy{
		"/access.v1.TenantAuditManagementApplication/ExportTenantAuditRecords": {Operation: OperationTenantAuditManagementExportTenantAuditRecords, Permissions: []authz.PermissionKey{"tenant.audit.export"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantAuditManagementApplication/GetTenantAuditRecord":     {Operation: OperationTenantAuditManagementGetTenantAuditRecord, Permissions: []authz.PermissionKey{"tenant.audit.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/access.v1.TenantAuditManagementApplication/ListTenantAuditRecords":   {Operation: OperationTenantAuditManagementListTenantAuditRecords, Permissions: []authz.PermissionKey{"tenant.audit.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
	}
}
