// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/gateway/authz"

func Permissions() []authz.PermissionKey {
	return []authz.PermissionKey{"platform.tenant.create", "platform.tenant.manage", "platform.tenant.read", "tenant.delegation.manage", "tenant.delegation.read", "tenant.member.manage", "tenant.member.read", "tenant.role.manage", "tenant.role.read"}
}

func Resolver() authz.StaticResolver {
	policies := map[string]authz.Policy{}
	for key, value := range tenantDelegationManagementPolicies() {
		policies[key] = value
	}
	for key, value := range tenantLifecyclePolicies() {
		policies[key] = value
	}
	for key, value := range tenantMemberLifecyclePolicies() {
		policies[key] = value
	}
	for key, value := range tenantRolePermissionPolicies() {
		policies[key] = value
	}
	return authz.NewStaticResolver(policies)
}
