// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/gateway/authz"

const OperationTenantDelegationManagementGetTenantDelegation authz.OperationID = "tenant.delegation.get"
const OperationTenantDelegationManagementGrantTenantDeviceDelegation authz.OperationID = "tenant.delegation.grant_device"
const OperationTenantDelegationManagementListTenantDelegations authz.OperationID = "tenant.delegation.list"
const OperationTenantDelegationManagementRevokeTenantDelegation authz.OperationID = "tenant.delegation.revoke"

func TenantDelegationManagementPermissions() []authz.PermissionKey {
	return []authz.PermissionKey{"tenant.delegation.manage", "tenant.delegation.read"}
}

func TenantDelegationManagementResolver() authz.StaticResolver {
	return authz.NewStaticResolver(tenantDelegationManagementPolicies())
}

func tenantDelegationManagementPolicies() map[string]authz.Policy {
	return map[string]authz.Policy{
		"/access.v1.TenantDelegationApplication/GetTenantDelegation":         {Operation: OperationTenantDelegationManagementGetTenantDelegation, Permissions: []authz.PermissionKey{"tenant.delegation.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key"}},
		"/access.v1.TenantDelegationApplication/GrantTenantDeviceDelegation": {Operation: OperationTenantDelegationManagementGrantTenantDeviceDelegation, Permissions: []authz.PermissionKey{"tenant.delegation.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key"}},
		"/access.v1.TenantDelegationApplication/ListTenantDelegations":       {Operation: OperationTenantDelegationManagementListTenantDelegations, Permissions: []authz.PermissionKey{"tenant.delegation.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key"}},
		"/access.v1.TenantDelegationApplication/RevokeTenantDelegation":      {Operation: OperationTenantDelegationManagementRevokeTenantDelegation, Permissions: []authz.PermissionKey{"tenant.delegation.manage"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key"}},
	}
}
