// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/pkg/operationplan"

func OperationPlanTenantDelegationManagementGetTenantDelegation() operationplan.Plan {
	return operationplan.Plan{OperationID: "tenant.delegation.get", Domain: "access", Application: "tenant_delegation_management", UseCase: "get_tenant_delegation", RequestType: "access.v1.GetTenantDelegationRequest", ResponseType: "access.v1.TenantDelegationDTO", Execution: operationplan.Execution{Transaction: "read_only", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: true, Authentication: []string{"api-key"}, Permissions: []string{"tenant.delegation.read"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/access.v1.TenantDelegationApplication/GetTenantDelegation", HTTP: []operationplan.HTTPBinding{{Method: "GET", Path: "/v1/tenant/delegations/{id}", Body: "", ResponseBody: ""}}}}
}

func OperationPlanTenantDelegationManagementGrantTenantDeviceDelegation() operationplan.Plan {
	return operationplan.Plan{OperationID: "tenant.delegation.grant_device", Domain: "access", Application: "tenant_delegation_management", UseCase: "grant_tenant_device_delegation", RequestType: "access.v1.GrantTenantDeviceDelegationRequest", ResponseType: "access.v1.TenantDelegationDTO", Execution: operationplan.Execution{Transaction: "local", Idempotency: "required"}, Security: operationplan.Security{Public: false, TenantRequired: true, Authentication: []string{"api-key"}, Permissions: []string{"tenant.delegation.manage"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/access.v1.TenantDelegationApplication/GrantTenantDeviceDelegation", HTTP: []operationplan.HTTPBinding{{Method: "POST", Path: "/v1/tenant/delegations/devices", Body: "*", ResponseBody: ""}}}}
}

func OperationPlanTenantDelegationManagementListTenantDelegations() operationplan.Plan {
	return operationplan.Plan{OperationID: "tenant.delegation.list", Domain: "access", Application: "tenant_delegation_management", UseCase: "list_tenant_delegations", RequestType: "access.v1.ListTenantDelegationsRequest", ResponseType: "access.v1.ListTenantDelegationsResponse", Execution: operationplan.Execution{Transaction: "read_only", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: true, Authentication: []string{"api-key"}, Permissions: []string{"tenant.delegation.read"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/access.v1.TenantDelegationApplication/ListTenantDelegations", HTTP: []operationplan.HTTPBinding{{Method: "GET", Path: "/v1/tenant/delegations", Body: "", ResponseBody: ""}}}}
}

func OperationPlanTenantDelegationManagementRevokeTenantDelegation() operationplan.Plan {
	return operationplan.Plan{OperationID: "tenant.delegation.revoke", Domain: "access", Application: "tenant_delegation_management", UseCase: "revoke_tenant_delegation", RequestType: "access.v1.RevokeTenantDelegationRequest", ResponseType: "access.v1.TenantDelegationDTO", Execution: operationplan.Execution{Transaction: "local", Idempotency: "required"}, Security: operationplan.Security{Public: false, TenantRequired: true, Authentication: []string{"api-key"}, Permissions: []string{"tenant.delegation.manage"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/access.v1.TenantDelegationApplication/RevokeTenantDelegation", HTTP: []operationplan.HTTPBinding{{Method: "POST", Path: "/v1/tenant/delegations/{id}:revoke", Body: "*", ResponseBody: ""}}}}
}
