<script setup lang="ts">
import { computed } from 'vue'
import {
  House,
  MonitorCog,
  MapPin,
  UsersRound,
  ReceiptText,
  Coffee,
  Network,
  Wrench,
  ChartColumnIncreasing,
  Users,
  Building2,
  Settings,
  ShieldCheck,
  GitFork,
  Crown,
  FileText,
  UserRoundPlus,
  Plus,
  PencilLine,
  Search,
  Bell,
  CircleHelp,
  Download,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  X,
  MoreHorizontal,
  SlidersHorizontal,
  Check,
  LogOut,
  KeyRound,
  LockKeyhole,
  Mail,
  ArrowUpRight,
  ArrowLeft,
  Send,
  Copy,
  RefreshCw,
  CircleCheck,
  CircleAlert,
  CircleX,
  CalendarDays,
  Smartphone,
  Eye,
  Upload,
  Folder,
  UserRound,
  Layers,
  Clock,
  Activity,
  Menu,
  Globe,
  Database,
  Link,
  Trash2,
  Circle,
  ArrowRight,
  CheckCheck,
  SquareArrowOutUpRight,
} from 'lucide-vue-next'
const props = withDefaults(defineProps<{ name: string; size?: number; stroke?: number }>(), {
  size: 18,
  stroke: 1.8,
})
const icons: Record<string, typeof House> = {
  home: House,
  device: MonitorCog,
  site: MapPin,
  customer: UsersRound,
  order: ReceiptText,
  coffee: Coffee,
  operations: Network,
  ticket: Wrench,
  chart: ChartColumnIncreasing,
  users: Users,
  company: Building2,
  settings: Settings,
  shield: ShieldCheck,
  organization: GitFork,
  crown: Crown,
  file: FileText,
  invite: UserRoundPlus,
  plus: Plus,
  edit: PencilLine,
  search: Search,
  bell: Bell,
  help: CircleHelp,
  download: Download,
  down: ChevronDown,
  left: ChevronLeft,
  right: ChevronRight,
  collapse: ChevronsLeft,
  expand: ChevronsRight,
  close: X,
  more: MoreHorizontal,
  filter: SlidersHorizontal,
  check: Check,
  logout: LogOut,
  key: KeyRound,
  lock: LockKeyhole,
  mail: Mail,
  up: ArrowUpRight,
  back: ArrowLeft,
  send: Send,
  copy: Copy,
  refresh: RefreshCw,
  success: CircleCheck,
  warning: CircleAlert,
  error: CircleX,
  calendar: CalendarDays,
  phone: Smartphone,
  eye: Eye,
  upload: Upload,
  folder: Folder,
  user: UserRound,
  layers: Layers,
  clock: Clock,
  activity: Activity,
  menu: Menu,
  globe: Globe,
  database: Database,
  link: Link,
  trash: Trash2,
  arrow: ArrowRight,
  checks: CheckCheck,
  external: SquareArrowOutUpRight,
}
const icon = computed(() => icons[props.name] ?? Circle)
</script>
<template>
  <component :is="icon" class="icon" :size="size" :stroke-width="stroke" aria-hidden="true" />
</template>
