// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/gateway/authz"

const OperationCreateMessageConfigurations authz.OperationID = "notification.configuration.create"
const OperationDeleteMessageConfiguration authz.OperationID = "notification.configuration.delete"
const OperationGetMessageConfiguration authz.OperationID = "notification.configuration.get"
const OperationListMessageChannels authz.OperationID = "notification.channel.list"
const OperationListMessageConfigurations authz.OperationID = "notification.configuration.list"
const OperationListMessageGroups authz.OperationID = "notification.group.list"
const OperationListMessageRecipients authz.OperationID = "notification.recipient.list"
const OperationListMessageTypes authz.OperationID = "notification.type.list"
const OperationUpdateMessageConfiguration authz.OperationID = "notification.configuration.update"

func Permissions() []authz.PermissionKey {
	return []authz.PermissionKey{"tenant.notification.create", "tenant.notification.delete", "tenant.notification.read", "tenant.notification.update"}
}

func Resolver() authz.StaticResolver {
	return authz.NewStaticResolver(map[string]authz.Policy{
		"/notification.v1.MessageConfigurationApplication/CreateMessageConfigurations": {Operation: OperationCreateMessageConfigurations, Permissions: []authz.PermissionKey{"tenant.notification.create"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/notification.v1.MessageConfigurationApplication/DeleteMessageConfiguration":  {Operation: OperationDeleteMessageConfiguration, Permissions: []authz.PermissionKey{"tenant.notification.delete"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/notification.v1.MessageConfigurationApplication/GetMessageConfiguration":     {Operation: OperationGetMessageConfiguration, Permissions: []authz.PermissionKey{"tenant.notification.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/notification.v1.MessageConfigurationApplication/ListMessageChannels":         {Operation: OperationListMessageChannels, Permissions: []authz.PermissionKey{"tenant.notification.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/notification.v1.MessageConfigurationApplication/ListMessageConfigurations":   {Operation: OperationListMessageConfigurations, Permissions: []authz.PermissionKey{"tenant.notification.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/notification.v1.MessageConfigurationApplication/ListMessageGroups":           {Operation: OperationListMessageGroups, Permissions: []authz.PermissionKey{"tenant.notification.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/notification.v1.MessageConfigurationApplication/ListMessageRecipients":       {Operation: OperationListMessageRecipients, Permissions: []authz.PermissionKey{"tenant.notification.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/notification.v1.MessageConfigurationApplication/ListMessageTypes":            {Operation: OperationListMessageTypes, Permissions: []authz.PermissionKey{"tenant.notification.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
		"/notification.v1.MessageConfigurationApplication/UpdateMessageConfiguration":  {Operation: OperationUpdateMessageConfiguration, Permissions: []authz.PermissionKey{"tenant.notification.update"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key", "web-session"}},
	})
}
