CREATE TABLE IF NOT EXISTS biz_audit_events (
  event_id VARCHAR(64) NOT NULL,
  audit_id VARCHAR(64) NOT NULL,
  event_type VARCHAR(16) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  actor_subject VARCHAR(200) NOT NULL,
  actor_user_id VARCHAR(64) NOT NULL DEFAULT '',
  auth_method VARCHAR(32) NOT NULL DEFAULT '',
  auth_channel VARCHAR(32) NOT NULL DEFAULT '',
  session_ref VARCHAR(80) NOT NULL DEFAULT '',
  request_id VARCHAR(128) NOT NULL DEFAULT '',
  idempotency_ref VARCHAR(80) NOT NULL DEFAULT '',
  operation_id VARCHAR(160) NOT NULL,
  module VARCHAR(80) NOT NULL DEFAULT '',
  target VARCHAR(320) NOT NULL DEFAULT '',
  request_digest VARCHAR(64) NOT NULL DEFAULT '',
  receipt_ref VARCHAR(128) NOT NULL DEFAULT '',
  reason VARCHAR(500) NOT NULL DEFAULT '',
  risk VARCHAR(16) NOT NULL,
  outcome VARCHAR(16) NOT NULL,
  occurred_at DATETIME(6) NOT NULL,
  PRIMARY KEY (event_id),
  UNIQUE KEY uniq_audit_event_kind (audit_id, event_type),
  KEY idx_audit_tenant_time (tenant_id, occurred_at, audit_id),
  KEY idx_audit_tenant_operation (tenant_id, operation_id)
);
