CREATE TABLE IF NOT EXISTS biz_verification_challenges (
  challenge_id VARCHAR(96) NOT NULL,
  business_event_id VARCHAR(160) NOT NULL,
  binding_hash VARCHAR(64) NOT NULL,
  purpose VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL DEFAULT '',
  flow_id VARCHAR(160) NOT NULL,
  channel VARCHAR(16) NOT NULL,
  destination_hash VARCHAR(64) NOT NULL,
  masked_destination VARCHAR(320) NOT NULL,
  code_hash VARCHAR(64) NOT NULL,
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  max_attempts INT UNSIGNED NOT NULL,
  expires_at DATETIME(6) NOT NULL,
  consumed_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (challenge_id),
  UNIQUE KEY uniq_verification_business_event (business_event_id),
  KEY idx_verification_flow (flow_id),
  KEY idx_verification_expires (expires_at),
  KEY idx_verification_consumed (consumed_at),
  KEY idx_verification_target_time (user_id, purpose, destination_hash, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS biz_one_time_authorizations (
  authorization_hash VARCHAR(64) NOT NULL,
  challenge_id VARCHAR(96) NOT NULL,
  binding_hash VARCHAR(64) NOT NULL,
  purpose VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL DEFAULT '',
  flow_id VARCHAR(160) NOT NULL,
  channel VARCHAR(16) NOT NULL,
  destination_hash VARCHAR(64) NOT NULL,
  expires_at DATETIME(6) NOT NULL,
  consumed_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (authorization_hash),
  UNIQUE KEY uniq_one_time_authorization_challenge (challenge_id),
  KEY idx_one_time_authorization_user (user_id),
  KEY idx_one_time_authorization_flow (flow_id),
  KEY idx_one_time_authorization_expires (expires_at),
  KEY idx_one_time_authorization_consumed (consumed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS biz_security_notification_outbox (
  event_id VARCHAR(64) NOT NULL,
  business_event_id VARCHAR(160) NOT NULL,
  challenge_id VARCHAR(96) NOT NULL DEFAULT '',
  binding_hash VARCHAR(64) NOT NULL,
  kind VARCHAR(64) NOT NULL,
  purpose VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL DEFAULT '',
  flow_id VARCHAR(160) NOT NULL DEFAULT '',
  channel VARCHAR(16) NOT NULL,
  destination_hash VARCHAR(64) NOT NULL,
  masked_destination VARCHAR(320) NOT NULL,
  destination_ciphertext TEXT NULL,
  secret_ciphertext TEXT NULL,
  key_version VARCHAR(64) NOT NULL,
  state VARCHAR(24) NOT NULL,
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  provider_receipt VARCHAR(200) NOT NULL DEFAULT '',
  failure_code VARCHAR(64) NOT NULL DEFAULT '',
  expires_at DATETIME(6) NOT NULL,
  delivered_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (event_id),
  UNIQUE KEY uniq_security_notification_business_event (business_event_id),
  KEY idx_security_notification_challenge (challenge_id),
  KEY idx_security_notification_user (user_id),
  KEY idx_security_notification_state (state),
  KEY idx_security_notification_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
