from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def replace(path: str, old: str, new: str) -> None:
    target = ROOT / path
    text = target.read_text()
    if old not in text:
        raise SystemExit(f"anchor not found: {path}")
    target.write_text(text.replace(old, new, 1))


replace(
    "internal/access/infrastructure/persistence/first_party_idp.go",
    '''func (store *Store) SetUserPassword(ctx context.Context, userID, password string) error {\n\tuserID = strings.TrimSpace(userID)\n\tif store == nil || store.database == nil || userID == "" {\n\t\treturn ErrInvalidUserCredentials\n\t}\n\tif len(password) < 12 || len(password) > 1024 {\n\t\treturn errors.New("access: password must contain between 12 and 1024 bytes")\n\t}\n\tvar user userRecord\n\tif err := store.database.WithContext(ctx).Where("id = ? AND status = ?", userID, "active").First(&user).Error; err != nil {\n\t\tif errors.Is(err, gorm.ErrRecordNotFound) {\n\t\t\treturn ErrInvalidUserCredentials\n\t\t}\n\t\treturn err\n\t}\n\tsalt := make([]byte, 16)\n\tif _, err := rand.Read(salt); err != nil {\n\t\treturn err\n\t}\n\thash := pbkdf2SHA256([]byte(password), salt, defaultPBKDF2Iterations, 32)\n\tnow := time.Now().UTC()\n\trecord := userPasswordCredentialRecord{\n\t\tUserID:            userID,\n\t\tSalt:              base64.RawStdEncoding.EncodeToString(salt),\n\t\tPasswordHash:      base64.RawStdEncoding.EncodeToString(hash),\n\t\tIterations:        defaultPBKDF2Iterations,\n\t\tDisabled:          false,\n\t\tPasswordChangedAt: now,\n\t\tUpdatedAt:         now,\n\t}\n\treturn store.database.WithContext(ctx).Clauses(clause.OnConflict{\n\t\tColumns:   []clause.Column{{Name: "user_id"}},\n\t\tDoUpdates: clause.AssignmentColumns([]string{"salt", "password_hash", "iterations", "disabled", "password_changed_at", "updated_at"}),\n\t}).Create(&record).Error\n}\n''',
    '''func (store *Store) SetUserPassword(ctx context.Context, userID, password string) error {\n\tif store == nil || store.database == nil {\n\t\treturn ErrInvalidUserCredentials\n\t}\n\treturn setUserPassword(ctx, store.database, userID, password)\n}\n\nfunc setUserPassword(ctx context.Context, database *gorm.DB, userID, password string) error {\n\tuserID = strings.TrimSpace(userID)\n\tif database == nil || userID == "" {\n\t\treturn ErrInvalidUserCredentials\n\t}\n\tif len(password) < 12 || len(password) > 1024 {\n\t\treturn errors.New("access: password must contain between 12 and 1024 bytes")\n\t}\n\tvar user userRecord\n\tif err := database.WithContext(ctx).Where("id = ? AND status = ?", userID, "active").First(&user).Error; err != nil {\n\t\tif errors.Is(err, gorm.ErrRecordNotFound) {\n\t\t\treturn ErrInvalidUserCredentials\n\t\t}\n\t\treturn err\n\t}\n\tsalt := make([]byte, 16)\n\tif _, err := rand.Read(salt); err != nil {\n\t\treturn err\n\t}\n\thash := pbkdf2SHA256([]byte(password), salt, defaultPBKDF2Iterations, 32)\n\tnow := time.Now().UTC()\n\trecord := userPasswordCredentialRecord{\n\t\tUserID:            userID,\n\t\tSalt:              base64.RawStdEncoding.EncodeToString(salt),\n\t\tPasswordHash:      base64.RawStdEncoding.EncodeToString(hash),\n\t\tIterations:        defaultPBKDF2Iterations,\n\t\tDisabled:          false,\n\t\tPasswordChangedAt: now,\n\t\tUpdatedAt:         now,\n\t}\n\treturn database.WithContext(ctx).Clauses(clause.OnConflict{\n\t\tColumns:   []clause.Column{{Name: "user_id"}},\n\t\tDoUpdates: clause.AssignmentColumns([]string{"salt", "password_hash", "iterations", "disabled", "password_changed_at", "updated_at"}),\n\t}).Create(&record).Error\n}\n''',
)

replace(
    "internal/access/infrastructure/persistence/first_party_idp_security.go",
    '''func (store *Store) DisableUserPassword(ctx context.Context, userID string) error {\n\tuserID = strings.TrimSpace(userID)\n\tif store == nil || store.database == nil || userID == "" {\n\t\treturn ErrInvalidUserCredentials\n\t}\n\tresult := store.database.WithContext(ctx).Model(&userPasswordCredentialRecord{}).Where("user_id = ?", userID).Update("disabled", true)\n\tif result.Error != nil {\n\t\treturn result.Error\n\t}\n\tif result.RowsAffected != 1 {\n\t\treturn ErrInvalidUserCredentials\n\t}\n\treturn store.RevokeWebSessionsForUser(ctx, userID)\n}\n\nfunc (store *Store) RotateUserPassword(ctx context.Context, userID, password string) error {\n\tif err := store.SetUserPassword(ctx, userID, password); err != nil {\n\t\treturn err\n\t}\n\treturn store.RevokeWebSessionsForUser(ctx, userID)\n}\n\nfunc (store *Store) RevokeWebSessionsForUser(ctx context.Context, userID string) error {\n\tuserID = strings.TrimSpace(userID)\n\tif store == nil || store.database == nil || userID == "" {\n\t\treturn nil\n\t}\n\tnow := time.Now().UTC()\n\treturn store.database.WithContext(ctx).Exec(`\nUPDATE biz_web_sessions s\nJOIN biz_web_identities i ON i.issuer = s.issuer AND i.subject = s.subject\nSET s.revoked_at = ?, s.updated_at = ?\nWHERE i.actor_kind = ? AND i.actor_id = ? AND s.revoked_at IS NULL`, now, now, WebActorUser, userID).Error\n}\n''',
    '''func (store *Store) DisableUserPassword(ctx context.Context, userID string) error {\n\tuserID = strings.TrimSpace(userID)\n\tif store == nil || store.database == nil || userID == "" {\n\t\treturn ErrInvalidUserCredentials\n\t}\n\treturn store.database.WithContext(ctx).Transaction(func(tx *gorm.DB) error {\n\t\tresult := tx.Model(&userPasswordCredentialRecord{}).Where("user_id = ?", userID).Update("disabled", true)\n\t\tif result.Error != nil {\n\t\t\treturn result.Error\n\t\t}\n\t\tif result.RowsAffected != 1 {\n\t\t\treturn ErrInvalidUserCredentials\n\t\t}\n\t\treturn revokeWebSessionsForUser(ctx, tx, userID)\n\t})\n}\n\nfunc (store *Store) RotateUserPassword(ctx context.Context, userID, password string) error {\n\tuserID = strings.TrimSpace(userID)\n\tif store == nil || store.database == nil || userID == "" {\n\t\treturn ErrInvalidUserCredentials\n\t}\n\treturn store.database.WithContext(ctx).Transaction(func(tx *gorm.DB) error {\n\t\tif err := setUserPassword(ctx, tx, userID, password); err != nil {\n\t\t\treturn err\n\t\t}\n\t\treturn revokeWebSessionsForUser(ctx, tx, userID)\n\t})\n}\n\nfunc (store *Store) RevokeWebSessionsForUser(ctx context.Context, userID string) error {\n\tuserID = strings.TrimSpace(userID)\n\tif store == nil || store.database == nil || userID == "" {\n\t\treturn nil\n\t}\n\treturn revokeWebSessionsForUser(ctx, store.database, userID)\n}\n\nfunc revokeWebSessionsForUser(ctx context.Context, database *gorm.DB, userID string) error {\n\tif database == nil {\n\t\treturn errors.New("access: web session revoke store unavailable")\n\t}\n\tnow := time.Now().UTC()\n\treturn database.WithContext(ctx).Exec(`\nUPDATE biz_web_sessions s\nJOIN biz_web_identities i ON i.issuer = s.issuer AND i.subject = s.subject\nSET s.revoked_at = ?, s.updated_at = ?\nWHERE i.actor_kind = ? AND i.actor_id = ? AND s.revoked_at IS NULL`, now, now, WebActorUser, userID).Error\n}\n''',
)

print("CE12_ATOMIC_CREDENTIALS_PATCHED=1")
