// Code generated by yunka contract; DO NOT EDIT.

package policy

import "github.com/hvritual/yunka.io/gateway/authz"

const OperationDeviceTransferTransferDevice authz.OperationID = "device.transfer"

func DeviceTransferPermissions() []authz.PermissionKey {
	return []authz.PermissionKey{"device.update", "site.read"}
}

func DeviceTransferResolver() authz.StaticResolver {
	return authz.NewStaticResolver(deviceTransferPolicies())
}

func deviceTransferPolicies() map[string]authz.Policy {
	return map[string]authz.Policy{
		"/deviceops.v1.DeviceTransferApplication/TransferDevice": {Operation: OperationDeviceTransferTransferDevice, Permissions: []authz.PermissionKey{"device.update", "site.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key"}},
	}
}
