// Code generated by yunka contract; DO NOT EDIT.

package policy

import "github.com/hvritual/yunka.io/pkg/operationplan"

func OperationPlanDeviceTransferTransferDevice() operationplan.Plan {
	return operationplan.Plan{OperationID: "device.transfer", Domain: "deviceops", Application: "device_transfer", UseCase: "transfer_device", RequestType: "deviceops.v1.TransferDeviceRequest", ResponseType: "deviceops.v1.DeviceDTO", Execution: operationplan.Execution{Transaction: "local", Idempotency: "required"}, Security: operationplan.Security{Public: false, TenantRequired: true, Authentication: []string{"api-key"}, Permissions: []string{"device.update", "site.read"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "local", RequiresOperations: []string{"device.update", "site.validate_transfer_target"}, PermissionClosure: []string{"device.update", "site.read"}}, ApplicationRequires: []string{"deviceops/device_management", "deviceops/site_management"}, Bindings: operationplan.Bindings{RPC: "/deviceops.v1.DeviceTransferApplication/TransferDevice", HTTP: []operationplan.HTTPBinding{{Method: "PATCH", Path: "/v1/devices/{id}/transfer", Body: "*", ResponseBody: ""}}}}
}
