// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/gateway/authz"

const OperationDeviceManagementCreateDevice authz.OperationID = "device.create"
const OperationDeviceManagementDeleteDevice authz.OperationID = "device.delete"
const OperationDeviceManagementGetDevice authz.OperationID = "device.get"
const OperationDeviceManagementListDevices authz.OperationID = "device.list"
const OperationDeviceManagementUpdateDevice authz.OperationID = "device.update"

func DeviceManagementPermissions() []authz.PermissionKey {
	return []authz.PermissionKey{"device.create", "device.delete", "device.read", "device.update"}
}

func DeviceManagementResolver() authz.StaticResolver {
	return authz.NewStaticResolver(deviceManagementPolicies())
}

func deviceManagementPolicies() map[string]authz.Policy {
	return map[string]authz.Policy{
		"/deviceops.v1.DeviceApplication/CreateDevice": {Operation: OperationDeviceManagementCreateDevice, Permissions: []authz.PermissionKey{"device.create"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key"}},
		"/deviceops.v1.DeviceApplication/DeleteDevice": {Operation: OperationDeviceManagementDeleteDevice, Permissions: []authz.PermissionKey{"device.delete"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key"}},
		"/deviceops.v1.DeviceApplication/GetDevice":    {Operation: OperationDeviceManagementGetDevice, Permissions: []authz.PermissionKey{"device.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key"}},
		"/deviceops.v1.DeviceApplication/ListDevices":  {Operation: OperationDeviceManagementListDevices, Permissions: []authz.PermissionKey{"device.read"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key"}},
		"/deviceops.v1.DeviceApplication/UpdateDevice": {Operation: OperationDeviceManagementUpdateDevice, Permissions: []authz.PermissionKey{"device.update"}, Mode: authz.PermissionAll, TenantRequired: true, Authentication: []string{"api-key"}},
	}
}
