// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/gateway/authz"

func Permissions() []authz.PermissionKey {
	return []authz.PermissionKey{"device.create", "device.delete", "device.read", "device.update", "site.read"}
}

func Resolver() authz.StaticResolver {
	policies := map[string]authz.Policy{}
	for key, value := range delegatedDeviceAccessPolicies() {
		policies[key] = value
	}
	for key, value := range deviceManagementPolicies() {
		policies[key] = value
	}
	for key, value := range deviceTransferPolicies() {
		policies[key] = value
	}
	for key, value := range siteManagementPolicies() {
		policies[key] = value
	}
	return authz.NewStaticResolver(policies)
}
