// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/pkg/operationplan"

func OperationPlanDeviceManagementAssertDeviceOwnedByActorTenant() operationplan.Plan {
	return operationplan.Plan{OperationID: "device.assert_owned_by_actor_tenant", Domain: "deviceops", Application: "device_management", UseCase: "assert_device_owned_by_actor_tenant", RequestType: "deviceops.v1.AssertDeviceOwnedByActorTenantRequest", ResponseType: "deviceops.v1.AssertDeviceOwnedByActorTenantResponse", Execution: operationplan.Execution{Transaction: "read_only", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: true, Authentication: []string{"api-key"}, Permissions: []string{"tenant.delegation.manage"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "", HTTP: []operationplan.HTTPBinding{}}}
}

func OperationPlanDeviceManagementCreateDevice() operationplan.Plan {
	return operationplan.Plan{OperationID: "device.create", Domain: "deviceops", Application: "device_management", UseCase: "create_device", RequestType: "deviceops.v1.CreateDeviceRequest", ResponseType: "deviceops.v1.DeviceDTO", Execution: operationplan.Execution{Transaction: "local", Idempotency: "required"}, Security: operationplan.Security{Public: false, TenantRequired: true, Authentication: []string{"api-key"}, Permissions: []string{"device.create"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/deviceops.v1.DeviceApplication/CreateDevice", HTTP: []operationplan.HTTPBinding{{Method: "POST", Path: "/v1/devices", Body: "*", ResponseBody: ""}}}}
}

func OperationPlanDeviceManagementDeleteDevice() operationplan.Plan {
	return operationplan.Plan{OperationID: "device.delete", Domain: "deviceops", Application: "device_management", UseCase: "delete_device", RequestType: "deviceops.v1.DeleteDeviceRequest", ResponseType: "deviceops.v1.DeleteDeviceResponse", Execution: operationplan.Execution{Transaction: "local", Idempotency: "required"}, Security: operationplan.Security{Public: false, TenantRequired: true, Authentication: []string{"api-key"}, Permissions: []string{"device.delete"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/deviceops.v1.DeviceApplication/DeleteDevice", HTTP: []operationplan.HTTPBinding{{Method: "DELETE", Path: "/v1/devices/{id}", Body: "", ResponseBody: ""}}}}
}

func OperationPlanDeviceManagementGetDevice() operationplan.Plan {
	return operationplan.Plan{OperationID: "device.get", Domain: "deviceops", Application: "device_management", UseCase: "get_device", RequestType: "deviceops.v1.GetDeviceRequest", ResponseType: "deviceops.v1.DeviceDTO", Execution: operationplan.Execution{Transaction: "read_only", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: true, Authentication: []string{"api-key"}, Permissions: []string{"device.read"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/deviceops.v1.DeviceApplication/GetDevice", HTTP: []operationplan.HTTPBinding{{Method: "GET", Path: "/v1/devices/{id}", Body: "", ResponseBody: ""}}}}
}

func OperationPlanDeviceManagementListDevices() operationplan.Plan {
	return operationplan.Plan{OperationID: "device.list", Domain: "deviceops", Application: "device_management", UseCase: "list_devices", RequestType: "deviceops.v1.ListDevicesRequest", ResponseType: "deviceops.v1.ListDevicesResponse", Execution: operationplan.Execution{Transaction: "read_only", Idempotency: "none"}, Security: operationplan.Security{Public: false, TenantRequired: true, Authentication: []string{"api-key"}, Permissions: []string{"device.read"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/deviceops.v1.DeviceApplication/ListDevices", HTTP: []operationplan.HTTPBinding{{Method: "GET", Path: "/v1/devices", Body: "", ResponseBody: ""}}}}
}

func OperationPlanDeviceManagementUpdateDevice() operationplan.Plan {
	return operationplan.Plan{OperationID: "device.update", Domain: "deviceops", Application: "device_management", UseCase: "update_device", RequestType: "deviceops.v1.UpdateDeviceRequest", ResponseType: "deviceops.v1.DeviceDTO", Execution: operationplan.Execution{Transaction: "local", Idempotency: "required"}, Security: operationplan.Security{Public: false, TenantRequired: true, Authentication: []string{"api-key"}, Permissions: []string{"device.update"}, PermissionMode: "all"}, Composition: operationplan.Composition{Boundary: "", RequiresOperations: []string{}, PermissionClosure: []string{}}, ApplicationRequires: []string{}, Bindings: operationplan.Bindings{RPC: "/deviceops.v1.DeviceApplication/UpdateDevice", HTTP: []operationplan.HTTPBinding{{Method: "PATCH", Path: "/v1/devices/{id}", Body: "*", ResponseBody: ""}}}}
}
