// Code generated by yunka contract; DO NOT EDIT.

package policy

import "yunka.io/gateway/authz"

func SiteManagementPermissions() []authz.PermissionKey {
	return []authz.PermissionKey{}
}

func SiteManagementResolver() authz.StaticResolver {
	return authz.NewStaticResolver(siteManagementPolicies())
}

func siteManagementPolicies() map[string]authz.Policy {
	return map[string]authz.Policy{}
}
