// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	"context"
	deviceopsv1 "github.com/hvritual/biz/contracts/gen/deviceops/v1"
)

// DelegatedDeviceAccessApplication is generated from PB and contains no business implementation.
type DelegatedDeviceAccessApplication interface {
	GetDelegatedDevice(context.Context, *deviceopsv1.GetDelegatedDeviceRequest) (*deviceopsv1.DeviceDTO, error)
	UpdateDelegatedDevice(context.Context, *deviceopsv1.UpdateDelegatedDeviceRequest) (*deviceopsv1.DeviceDTO, error)
}
