// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	"context"
	deviceopsv1 "github.com/hvritual/biz/contracts/gen/deviceops/v1"
)

// DeviceTransferApplication is generated from PB and contains no business implementation.
type DeviceTransferApplication interface {
	TransferDevice(context.Context, *deviceopsv1.TransferDeviceRequest) (*deviceopsv1.DeviceDTO, error)
}
