// Code generated by yunka contract; DO NOT EDIT.

package application

import (
	"context"
	deviceopsv1 "github.com/hvritual/biz/contracts/gen/deviceops/v1"
)

// SiteApplication is generated from PB and contains no business implementation.
type SiteManagementApplication interface {
	ValidateTransferTarget(context.Context, *deviceopsv1.ValidateTransferTargetRequest) (*deviceopsv1.SiteDTO, error)
}
