// Code generated by yunka contract; DO NOT EDIT.

package rpc

import (
	"context"
	"errors"
	notificationv1 "github.com/hvritual/biz/contracts/gen/notification/v1"
	application "github.com/hvritual/biz/internal/notification/application"
	policy "github.com/hvritual/biz/internal/notification/policy"
	grpc "google.golang.org/grpc"
	grpcmetadata "google.golang.org/grpc/metadata"
	execution "yunka.io/framework/execution"
	operation "yunka.io/framework/operation"
	gatewaygrpc "yunka.io/gateway/rpc/transport/grpc"
)

type OperationServer struct {
	notificationv1.UnimplementedMessageConfigurationApplicationServer
	application application.MessageConfigurationApplication
	executor    operation.Executor
}

func RegisterOperationExecutor(registrar grpc.ServiceRegistrar, application application.MessageConfigurationApplication, executor operation.Executor) error {
	if registrar == nil {
		return errors.New("contract C9 RPC adapter: registrar is required")
	}
	if application == nil {
		return errors.New("contract C9 RPC adapter: application is required")
	}
	if executor == nil {
		return errors.New("contract C9 RPC adapter: operation executor is required")
	}
	notificationv1.RegisterMessageConfigurationApplicationServer(registrar, &OperationServer{application: application, executor: executor})
	return nil
}

func (server *OperationServer) CreateMessageConfigurations(ctx context.Context, request *notificationv1.CreateMessageConfigurationsRequest) (*notificationv1.MessageConfigurationReceipt, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanCreateMessageConfigurations(), request, server.application.CreateMessageConfigurations)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *OperationServer) DeleteMessageConfiguration(ctx context.Context, request *notificationv1.DeleteMessageConfigurationRequest) (*notificationv1.MessageConfigurationReceipt, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanDeleteMessageConfiguration(), request, server.application.DeleteMessageConfiguration)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *OperationServer) GetMessageConfiguration(ctx context.Context, request *notificationv1.GetMessageConfigurationRequest) (*notificationv1.MessageConfigurationDTO, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanGetMessageConfiguration(), request, server.application.GetMessageConfiguration)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *OperationServer) ListMessageChannels(ctx context.Context, request *notificationv1.ListMessageChannelsRequest) (*notificationv1.ListMessageChannelsResponse, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanListMessageChannels(), request, server.application.ListMessageChannels)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *OperationServer) ListMessageConfigurations(ctx context.Context, request *notificationv1.ListMessageConfigurationsRequest) (*notificationv1.ListMessageConfigurationsResponse, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanListMessageConfigurations(), request, server.application.ListMessageConfigurations)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *OperationServer) ListMessageGroups(ctx context.Context, request *notificationv1.ListMessageDirectoryRequest) (*notificationv1.ListMessageDirectoryResponse, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanListMessageGroups(), request, server.application.ListMessageGroups)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *OperationServer) ListMessageRecipients(ctx context.Context, request *notificationv1.ListMessageDirectoryRequest) (*notificationv1.ListMessageDirectoryResponse, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanListMessageRecipients(), request, server.application.ListMessageRecipients)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *OperationServer) ListMessageTypes(ctx context.Context, request *notificationv1.ListMessageTypesRequest) (*notificationv1.ListMessageTypesResponse, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanListMessageTypes(), request, server.application.ListMessageTypes)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}

func (server *OperationServer) UpdateMessageConfiguration(ctx context.Context, request *notificationv1.UpdateMessageConfigurationRequest) (*notificationv1.MessageConfigurationReceipt, error) {
	if metadata, ok := grpcmetadata.FromIncomingContext(ctx); ok {
		if values := metadata.Get("idempotency-key"); len(values) > 0 {
			ctx = execution.WithIdempotencyKey(ctx, values[0])
		}
	}
	response, err := operation.ExecuteTyped(ctx, server.executor, policy.OperationPlanUpdateMessageConfiguration(), request, server.application.UpdateMessageConfiguration)
	if err != nil {
		return nil, gatewaygrpc.OperationError(err)
	}
	return response, nil
}
