name: domain-maintenance

on:
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Domain generation is performed with yunka.io main and verified before commit."
